### ISSUE TITLE
If you get an error while scrolling the feed down, you cannot continue

### ISSUE THREAD

**Issue by Die4Ever** [dessalines/jerboa#1003]
**Jerboa Version**
0.0.38 Alpha from GitHub

**Android version + phone**
Pixel 7a, Android 13

**Describe the bug**
If you get an error from the server when scrolling down, there's no way to retry the request to see the next posts

**To Reproduce**

1. Scroll down the feed until it tries to load more posts
2. Get an error from the server
3. Realize there is no way to retry the request

**Comment by MV-GH** [comment]
If you scroll up and then down again, does it not try to load more posts again?
