### ISSUE TITLE
Impossible to Login 

### ISSUE THREAD

**Issue by theRealBassist** [dessalines/jerboa#1004]
**Jerboa Version**
0.0.38

**Android version + phone**
Galaxy s10+ - Android 12

**Describe the bug**
After logging in, the sidebar will appear correct with subscriptions and username. However, the sub feed will not work, and you can not comment or post. After closing and reopening the app, you are logged out. 

Using lemmy.world instance. Have tried both username and email login. No 2FA.

Issue appeared following lemmy.world hack.

**To Reproduce**

1. Go to sidebar
2. Login
3. Restart app or "Switch" to new logged in account

**Comment by MV-GH** [comment]
After the lemmy.world hack all sessions were invalidated, log out and log in again. We don't properly check if a account is still authenticated as of yet.

**Comment by Nawor3565** [comment]
For some reason, when in this phantom login state, there is no option to sign out. How can I sign out to get a new session? 
![Screenshot_20230710-185552509 (1)](https://github.com/dessalines/jerboa/assets/19783632/8170656a-a1e6-4555-887d-64511a71cc91)

**Comment by nguypaul** [comment]
I believe I had this same issue and fixed it by going into my phone's System Settings > Apps > Jerboa > Storage & cache  and clearing both cache and storage.

Logged in again and that weird halfway state was fixed.

**Comment by theRealBassist** [comment]
> After the lemmy.world hack all sessions were invalidated, log out and log in again. We don't properly check if a account is still authenticated as of yet.

Again, 

> After closing and reopening the app, you are logged out.

So, I was already logged out. Logging in and out is literally the problem I am having.

> I believe I had this same issue and fixed it by going into my phone's System Settings > Apps > Jerboa > Storage & cache and clearing both cache and storage.

Yea it ended up resolving itself for literally 2 days, and now the issue has reappeared

**Comment by MV-GH** [comment]
Oh btw @theRealBassist the issue was not that you were being logged out. But that Jerboa made it look like you were logged out because it failed to retrieve your use profile on startup due to network failure (very prominent on lemmy.world) This is now fixed
