### ISSUE TITLE
Swipe to refresh - refresh icon doesn't account for top bar

### ISSUE THREAD

**Issue by machinaeZER0** [dessalines/jerboa#1011]
Hi! I noticed a small visual oddity and figured I'd log it here - I noticed when swiping down on the feed, the circular refresh arrow takes a while to show up? As in, I needed to swipe further down than I'd have expected to make it show up. I believe that this icon is currently set to animate down from the top of the screen, rather than immediately emerging from behind the top bar. Because of this, I frequently refresh the feed having only seen a small portion of the icon, and only for a brief second.

I don't know how easy of a fix it would be, but hopefully updating the refresh icon's starting position to account for the rest of the UI would fix this :)

**Comment by MV-GH** [comment]
Which version are you using?

**Comment by MV-GH** [comment]
Can you include a video of the issue
