### ISSUE TITLE
Left-handed comment mode

### ISSUE THREAD

**Issue by StevenDelich** [dessalines/jerboa#1012]
- [ Yes] Did you check to see if this issue already exists?
- [ Yes] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ No] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **
A left-handed mode when reading comments would be great. As someone who browses Lemmy with my left hand, having all the comment buttons on the right can be frustrating. An option to move them would be amazing, thank you! 

![image](https://github.com/dessalines/jerboa/assets/23245961/47146f14-c1f6-4846-ab25-8b132b0fae91)

**Comment by theshatterstone** [comment]
+1 There are many lemmy clients for Android but none of them have left hand mode. It could make Jerboa the best Lemmy client for left-handed users, and would be incredibly helpful.

**Comment by StevenDelich** [comment]
Definitely!

**Comment by theshatterstone** [comment]
@dessalines Are there any considerations being made to resolve this?

**Comment by dessalines** [comment]
Not by me, I'm swamped with lemmy work.

**Comment by dessalines** [comment]
Can re-open should someone want to work on this.
