### ISSUE TITLE
Change the monochrome theme

### ISSUE THREAD

**Issue by RustoMCSpit** [dessalines/jerboa#1016]
Instead of having the hollow mascot, have it filled in with the eye the color of the background instead. It currently does not match the general aesthetic design philosophy in its current nature of having the grey being the dominant color

**Comment by dessalines** [comment]
I can't tell what this means. Eye color?

**Comment by RustoMCSpit** [comment]
> I can't tell what this means. Eye color?

monochrome icon needs to have its two colors
swapped around

**Comment by dessalines** [comment]
Someone who knows how to generate / handle the icon variants will need to do that.
