### ISSUE TITLE
Holding down a comment should hide it and all children comments

### ISSUE THREAD

**Issue by RustoMCSpit** [dessalines/jerboa#1017]
The app should inform users a short tap collapses comments as a pop-up on first install

**Comment by MV-GH** [comment]
To collapse comments, you have to do a short tap

**Comment by MV-GH** [comment]
See #935

**Comment by RustoMCSpit** [comment]
> To collapse comments, you have to do a short tap

Alright let me change the issue

**Comment by twizmwazin** [comment]
We could do an option to invert the current behavior, or if someone was up to it make tap and long press assignable to one of a set of actions.

**Comment by RustoMCSpit** [comment]
> We could do an option to invert the current behavior, or if someone was up to it make tap and long press assignable to one of a set of actions.

as a setting? sure

**Comment by RustoMCSpit** [comment]
The app should inform users a short tap collapses comments as a pop-up on first install

**Comment by MV-GH** [comment]
We could use a better onboarding experience in general.

**Comment by RustoMCSpit** [comment]
> We could use a better onboarding experience in general.

any update on that?

**Comment by MV-GH** [comment]
Someone will have to design it and someone will have to implement it.

Not a priority for me atm, but everyone is welcome to contribute.

**Comment by RustoMCSpit** [comment]
@dessalines ???

**Comment by dessalines** [comment]
If you want to work on it, go ahead.

**Comment by dessalines** [comment]
You'll have to watch videos / learn how to code for android like I did.

**Comment by RustoMCSpit** [comment]
> You'll have to watch videos / learn how to code for android like I did.

yeah but what foss ides are there

**Comment by MV-GH** [comment]
Android Studio

**Comment by RustoMCSpit** [comment]
> Android Studio

that isnt foss right??

**Comment by RustoMCSpit** [comment]
> It is free and open source https://android.googlesource.com/platform/tools/base/+/studio-master-dev/studio.md

[License](https://en.m.wikipedia.org/wiki/Software_license)
Binaries: [Freeware](https://en.m.wikipedia.org/wiki/Freeware),[[3]](https://en.m.wikipedia.org/wiki/Android_Studio#cite_note-3) [Source code](https://en.m.wikipedia.org/wiki/Source_code):[[4]](https://en.m.wikipedia.org/wiki/Android_Studio#cite_note-4)[[5]](https://en.m.wikipedia.org/wiki/Android_Studio#cite_note-5) [Apache License](https://en.m.wikipedia.org/wiki/Apache_License)

can you explain this to me im confusdd

**Comment by MV-GH** [comment]
I don't understand what you ask from me

**Comment by RustoMCSpit** [comment]
> I don't understand what you ask from me

sorry let me explain better!! can you go here https://en.m.wikipedia.org/wiki/Android_Studio and explain the part under the 'License' that say 'Binaries: Freeware, Source code: Apache License'

Freeware isn't FOSS to my knowlegde and what does it mean by binaries?

**Comment by RustoMCSpit** [comment]
> Binaries are the executables, e.g the .exe you click in Windows. It is the compiled and bundled source code. The binary code that can be executed for that architecture

but isnt freemium a lite version of a premium software??

**Comment by MV-GH** [comment]
I am not sure what you trying to get at? FOSS definition doesn't mention anything regarding the binaries. 

There is only one IDE for Android and it's Android Studio else u just gotta use a plain editor.

**Comment by dessalines** [comment]
@RustoMCSpit Don't clog up the issue tracker with questions that you can easily do searches for on your own. Our time is limited, so don't waste it. I won't hesitate to remove you from here if you can't follow that.
