### ISSUE TITLE
Optionally mark post as Read via long-press or swipe

### ISSUE THREAD

**Issue by jbarr** [dessalines/jerboa#1037]
- [Y ] Did you check to see if this issue already exists?
- [Y] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [N] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **
While browsing through the various lists of posts, I would like to quickly mark selected posts as Read without having to open them. For example, long-pressing on a post or swiping it (based on an option in Settings?) would mark the post as Read. When the list is refreshed, and if Settings > Account Settings > Show Read Posts is unchecked, the resulting refreshed list would show only unread posts.

**Comment by MV-GH** [comment]
There is a mark unread on scroll in progress, would that be enough? Also that show unread option should already work
