### ISSUE TITLE
Extra top and bottom bars after closing image viewer

### ISSUE THREAD

**Issue by sockenklaus** [dessalines/jerboa#1045]
**Jerboa Version**
0.0.40-alpha

**Android version + phone**
Android 10.1, OnePlus 5t

**Describe the bug**
When I close the image viewer an extra bar at the bottom roughly the height of the navigation bar as well as an extra bar at the top the size of the system bar appear. 

See this video:
https://github.com/dessalines/jerboa/assets/870042/5a2b9882-ff35-4985-8507-150d7a8f8a5b

**To Reproduce**

1. Open an image in image viewer
2. Close the image viewer either by using the back button at the top left or swipe up.

**Comment by MV-GH** [comment]
Can you test if this fixes it?

[app-release.zip](https://github.com/dessalines/jerboa/files/12062924/app-release.zip)

**Comment by sockenklaus** [comment]
> Can you test if this fixes it?
> 
> [app-release.zip](https://github.com/dessalines/jerboa/files/12062924/app-release.zip)

Yes, this fixes it!
