### ISSUE TITLE
"not_logged_in" on Inbox in answers, mentions and DM. And I'm connected to my account.

### ISSUE THREAD

**Issue by painkiller1717** [dessalines/jerboa#1079]
### Jerboa Version

0.0.41

### Android Version + Phone

Android 12

### Describe The Bug

The Inbox section with answers, mentions and messages should show the previous answers, mentions and messages, but instead I see a text which put not_logged_in. Obviously I'm connected to my account. I just update to the last version, and I didn't had this issue in previous versions.

I attach screenshot:

![Screenshot_2023-07-21-15-22-59-190-edit_com jerboa](https://github.com/dessalines/jerboa/assets/77559296/899bff88-ff5f-4707-8f39-8d1cc9e5d79c)

Hope this can be solved soon.

### To Reproduce

1. Go to Inbox section
2. Enter on answers, mentions or messages
3. The text "not_logged_in" can be readed and nothing else
4. I'm connected to my account.
5.
![Screenshot_2023-07-21-15-22-59-190-edit_com jerboa](https://github.com/dessalines/jerboa/assets/77559296/c19f7851-2e03-445a-9f8c-758ed18a3c0b)
![Screenshot_2023-07-21-15-29-48-344_com jerboa](https://github.com/dessalines/jerboa/assets/77559296/0958da33-6221-4378-bf26-c0c64bc70545)

**Comment by MV-GH** [comment]
Does it do this consistently? and does it say anonymous in top of the drawer? Either way can we get the full logs?
