### ISSUE TITLE
Other users' profiles have useless drawer button

### ISSUE THREAD

**Issue by twizmwazin** [dessalines/jerboa#1081]
### Jerboa Version

0.0.41

### Android Version + Phone

Android 13, Pixel 5

### Describe The Bug

If you tap a user's profile name to view their profile, there is a hamburger menu to open the drawer in the top left. It doesn't do anything. It probably should be replaced with a back arrow.

### To Reproduce

Click post in home feed, click user name in post

**Comment by MV-GH** [comment]
Hmm it doesn't even work if you use it to navigate to your own profile
