### ISSUE TITLE
Your own posts should always show up under Profile - Posts regardless of setting for Show Read Posts

### ISSUE THREAD

**Issue by MapleSoda** [dessalines/jerboa#1085]
### Jerboa Version

0.0.41

### Android Version + Phone

Android 13, Galaxy S7 Tablet

### Describe The Bug

As the title says, I believe your own posts should always show up in the Profile - Posts section.  There should be no reason to hide your own posts from yourself...  Your own posts currently do not show up in the Posts section if Read Posts are Hidden.
This was mentioned in Lemmy and I was asked to create to bug here for it.

### To Reproduce

See describe the bug section

**Comment by MV-GH** [comment]
I took a look at this, and it is actually a Lemmy BE issue. 

The request itself returns 0 posts but it does still return the comments
![image](https://github.com/dessalines/jerboa/assets/67873169/865faa58-3b46-45c6-8140-35949e50804d)

**Comment by dessalines** [comment]
Fixed by above PR.
