### ISSUE TITLE
Clicking a comment in my inbox doesn't bring up the comment 

### ISSUE THREAD

**Issue by KarkanAlzwayed** [dessalines/jerboa#1089]
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

When I have a reply in my inbox, clicking on the comment doesn't actually bring up the comment, it brings the comment thread the reply is in. To get to that exact reply, I'd have to scroll through the whole thread to find it. If it is a big thread, forget it. 
Clicking the reply should take me straight to it. 
Note: I did search the open issues and couldn't find anything. If this is duplicate, my apologies in advance.

**Comment by twizmwazin** [comment]
It actually depends if you click on the post title where the comment is from, or if you click on the text of the comment. This isn't intuitive though and we should make it always go to the exact comment.

**Comment by KarkanAlzwayed** [comment]
> It actually depends if you click on the post title where the comment is from, or if you click on the text of the comment. This isn't intuitive though and we should make it always go to the exact comment.

I could be doing it wrong, but clicking on the post title brings up the post. Clicking on the comment itself, brings up my comment, not the reply I wanted to get to. This is currently my only reason for not using the app full time. This and another issue I have already reported where typing a reply and moving to a new line doesn't push the page up, then the text I'm typing hides under my keyboard.

**Comment by twizmwazin** [comment]
Yes, you're correct. I think the ideal implementation of this would show only the reply comment and the comment it was replying to. I'll see if I can just have it go directly to the reply comment, and then the user can use the context button if they need to re-read their own comment.

**Comment by KarkanAlzwayed** [comment]
[Here](https://github.com/dessalines/jerboa/issues/999#issuecomment-1627597550) is the other issue I've already reported. Fixing these two would actually force me to use the app full time 😁

**Comment by dessalines** [comment]
This seems fixed now.
