### ISSUE TITLE
Links to source does not work

### ISSUE THREAD

**Issue by eshate** [dessalines/jerboa#109]
Hey, I checked it on 0.0.8 and now on 0.0.10 - I when I'm clicking on the article source it not refirecting ne, only flashing - but nithin else is happening. Got three browsers actually, other apps (f.e. Lemmur) always ask which of them to use - here nothing actually happens.

A11, Lavender, ArrowOS (custom)

**Comment by dessalines** [comment]
What do you mean, article source? View source is for viewing the markdown source.

**Comment by eshate** [comment]
Sorry for being not specific. **I mean link which is redirecting "outside" the app.** 

**For example:** _I'm scrolling the service and see an article from Guardian posted by someone. In Lemmur, or desktop (browser) - it's easy to click on article title and be redirected to Guardian website containing this article._ 

In my case it doesn't work.

**Comment by eshate** [comment]
OKAY, got it. There is one place to tap - a thumbnail picture. 
Sorry for wasting your time, case closed. 

Thanks
