### ISSUE TITLE
Blocked communities are still showing up

### ISSUE THREAD

**Issue by lukini** [dessalines/jerboa#1093]
### Jerboa Version

0.0.41

### Android Version + Phone

Android 13, Google Pixel 7

### Describe The Bug

Beehaw instance

My blocked communities aren't blocked in the app.  Going to the community and selecting "Block Community" inside of the app also does not block it.

This is specifically happening for feddit.de communities if that is related.

### To Reproduce

1. Block a community
2. Go to All and choose Active or Hot
3. Scroll until you find a post from it

**Comment by lukini** [comment]
It works fine on the beehaw frontend.

![image](https://github.com/dessalines/jerboa/assets/948096/0a47128a-6932-4f35-b17a-3f2bb03ab835)

![image](https://github.com/dessalines/jerboa/assets/948096/880a4ff4-0cbe-4287-ac5b-ba0c53cef0cb)

![image](https://github.com/dessalines/jerboa/assets/948096/91b46ee9-e5dd-4cb1-85c4-70e05823f925)

**Comment by MV-GH** [comment]
Do they still show up after a refresh on the feed?

**Comment by lukini** [comment]
A force stop didn't fix it, but clearing all app data and signing back in did.  I'm guessing something was cached or didn't get updated properly from a previous version?  I'll monitor if any new blocks work or not.

**Comment by MV-GH** [comment]
Huh, weird, that does sound more like backend issue, the feed still containing previous posts from that community is normal as we do not delete them yet on blocking. Jerboa does not cache any requests (Except images), the instance itself might tho. If that is the cause then we can do nothing about that.

**Comment by dessalines** [comment]
back-end issue.
