### ISSUE TITLE
Pull to refresh indicator does not adopt the theme

### ISSUE THREAD

**Issue by MV-GH** [dessalines/jerboa#1095]
### Jerboa Version

0.0.41

### Android Version + Phone

11

### Describe The Bug

Pull to refresh indicator does not adopt the theme, it is white with black inner thing on every theme, it should be black with red inner thing according to this theme
![studio64_nOc51JxrEc](https://github.com/dessalines/jerboa/assets/67873169/133d0046-7e4e-4928-997d-8ec8860d04c4)

### To Reproduce

pull the refresh

**Comment by bappitybup** [comment]
also on android 13

**Comment by 0xFOSSMan** [comment]
can confirm on Lemmy 0.0.46-alpha with Android 10

**Comment by MV-GH** [comment]
Yeah I am not sure why google makes some elements not follow the theming out of the box.

**Comment by MV-GH** [comment]
Oh i see why it doesn't work. PullRefresh is from Material. While our theme is for Material3. Ugh

M3 pull to refresh is still nowhere done
https://issuetracker.google.com/issues/261760718
