### ISSUE TITLE
option to share links from local instance by default

### ISSUE THREAD

**Issue by Kommynct** [dessalines/jerboa#1100]
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

I would like a toggle for when you push the share permalink to link on your logged in instance instead of wherever the post is hosted. That would be very helpful for me. 

Currently in order to do that I have to open the link in a web browser.

**Comment by dessalines** [comment]
This is done.
