### ISSUE TITLE
Add "copy to clipboard" on original post

### ISSUE THREAD

**Issue by adRn-s** [dessalines/jerboa#1101]
Currently, the option is available on comments. But it's not possible to copy text from OP.

PS. It would allow me to access foreign language communities as part of my learning experience.

**Comment by MV-GH** [comment]
You can select text to copy once you use the "view source" button

**Comment by adRn-s** [comment]
Thanks!

Maybe adding some of these buttons to the swipe of posts and comments would help.

IIRC, my mobile phone screen size is 6.55 inches. Yet...

- The 'view source' button is under the sandwich menu, and this only is visible if I rotate the phone. Maybe this is a bug?
- Once the sandwich menu is clicked, given I'm on a landscape orientation, all the buttons (incl.'view source') are shown in a short rectangle that it's un-scrollable. I think I can only see the first 3 to 4 options instead of the nearly 8 or 10 that are available. So, I had to re-rotate to a portrait/ vertical landscape to actually get access to tap 'view source' button.
- Only after this cumbersome process, I am able to long-click the text on the post to select, copy, and go to translate...

Hopefully, this can be greatly improved on the many levels that are going awry. This is a matter of accessibility. The situation is more critical now that a solution has been pointed out (again, thanks!), and its limits were experienced.

Also, Is there any reason why the "view source" mode isn't enabled by default? I am unable to distinguish the difference... well maybe I will have to look with more attention.

**Comment by MV-GH** [comment]
We are aware that currently the menus are a problem area, I have already suggested a solution see #1065. It still needs to be implemented. 

View source shows the raw text, no markdown rendered.

**Comment by MV-GH** [comment]
For this "Copy to clipboard", do you just want to copy the entire body? If so that option should already exist

**Comment by dessalines** [comment]
This is done now.
