### ISSUE TITLE
(Spanish Translation) Inbox translation breaks the vertical position of the icon in bottom Navbar

### ISSUE THREAD

**Issue by ogarcia** [dessalines/jerboa#1110]
### Jerboa Version

0.0.41

### Android Version + Phone

Android 10, Moto G8 Plus

### Describe The Bug

With a screen resolution of 1080 x 2280 pixels, the inbox text (in Spanish) completely breaks the layout of the icons in the bottom Navbar:

![jerboa_bottom_Navbar_bug](https://github.com/dessalines/jerboa/assets/572924/b0136bf1-0f75-4474-b457-244b158e6ec4)

Related with #818

### To Reproduce

Simply open the application in Spanish language and see the bottom Navbar.

**Comment by MV-GH** [comment]
What is supposed to happen in these cases?

**Comment by twizmwazin** [comment]
In other translations, users have suggested shorter translations

**Comment by ogarcia** [comment]
Maybe use "Entrada" instead of "Bandeja de Entrada" only in the button label (I think that this is the line):
https://github.com/dessalines/jerboa/blob/efa1aa3c78f3f044c2b925c03efaf5492d630c5b/app/src/main/res/values-es/strings.xml#L280

I can send you a Merge Request if you can confirm me that this is the correct line.

**Comment by twizmwazin** [comment]
Yep that looks right to me
