### ISSUE TITLE
Comment trees indented in opposite order when viewing single comment threads

### ISSUE THREAD

**Issue by Darkassassin07** [dessalines/jerboa#1116]
### Jerboa Version

0.0.41

### Android Version + Phone

Android 13, Samsung A52

### Describe The Bug

When viewing individual comment trees, usually by opening a comment from my own history that has replies on it, or just clicking view context: the original comment is the furthest indented, with the replies indented one less, and further replies to those less indented still until the lowest level comment appears as the oc, but at the bottom of the list.

Here's an example:

https://lemmy.ca/pictrs/image/8822ee10-95b9-4376-a8dc-b57d05077134.jpeg

### To Reproduce

-View your profile 
-open a comment with replies and/or was a reply to another chain
-(optional) click view context to see more of the tree

**Comment by MV-GH** [comment]
Jerboa uses the depth of the first comment to decide how to order, the following comments, Through a bug introduced somewhere in 0.18.3 this order was randomized. Causing jerboa to act weird. Maybe Jerboa should handle this differently but this has been fixed now in Lemmy. Thus I will leave it be
