### ISSUE TITLE
Add setting to disable swipe back from posts

### ISSUE THREAD

**Issue by sthomas727** [dessalines/jerboa#1117]
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

I find the swipe back functionality to be disruptive, as I seem to accidentally activate it when I'm trying to scroll down comments on a post. I would like to have an option in the Look and Feel settings to disable this feature.
I noticed from looking through previous commits that this was actually implemented when the swipe back feature was first merged, but was then later removed for some reason. In my opinion having this option would improve accessibility, whilst still allowing people who use the swipe back functionality to keep doing so.

**Comment by MV-GH** [comment]
We agree on that and there is a PR for that already. It also enables full post swiping gestures. But it is stuck in limbo as the author has not responded yet.
