### ISSUE TITLE
Navigation with "back" button doesn't always work properly

### ISSUE THREAD

**Issue by Aloso** [dessalines/jerboa#113]
When starting the app, a splash screen appears, then the start screen. When pressing the "back" button, the splash screen appears again, then the start screen appears again. Instead, the app should be closed when pressing "back" from the start screen.

When switching the tab at the bottom and then pressing "back", the app goes to the previous tab. Most apps I tried don't switch between tabs when pressing "back", and this is also the behavior I would expect intuitively.

**Comment by Aloso** [comment]
> Those issues would only occur when you haven't yet logged in. Once you log in, there is no back button on the main page.

I'm talking about this one, which is always visible:

![screenshot](https://user-images.githubusercontent.com/15658558/157524267-5ab3d776-0ebc-4c6e-b972-cb4be6a0185b.jpg)

> The 2nd issue I don't see what its doing wrong? Its not switching tabs, its popping back the navigation stack like a back button should. If you were on a different tab previously, its going to go back to that one.

Yeah, I wasn't sure if I should mention this, since it's not a big deal, and the current behavior is ok. What I meant is that many apps don't add an entry to the navigation stack when switching between tabs; instead, they replace the last entry.

**Comment by noodlejetski** [comment]
in addition to the behaviour described above, if you've just installed Jerboa, log in, go to the main view and the try navigating back, it'll move you back to the screen when you're typing in your credentials.

also, when you navigate back from the main screen and have the splash screen show up (as described in the first post of this issue) and quickly try navigating back again, Jerboa will exit, but the next time you try opening it it'll be stuck on the splash screen, and the only way to actually use it then is to clear it from the recent apps list and launch it again.

**Comment by garret** [comment]
I agree, it seems odd that when going back the splash screen appears and it is not possible to exit the app instead. Came here to fill an issue but I am glad someone else has already noticed. It is the only app with this behavior (apart from a bank app I have which is super buggy per se).

**Comment by Porkepix** [comment]
> I agree, it seems odd that when going back the splash screen appears and it is not possible to exit the app instead. Came here to fill an issue but I am glad someone else has already noticed. It is the only app with this behavior (apart from a bank app I have which is super buggy per se).

You actually can, but need to press return twice quickly (quick enough for the splash screen to don't end loading). And yes I agree this is counter-intuitive, as well as some of the comments above.

**Comment by garret** [comment]
@Porkepix I think I am not able to do it quickly because I am using the android gestures to go back (so I don't have the "physical" back button in a navbar on the bottom).

**Comment by dessalines** [comment]
I'd have to look up how to prevent some routes from being added to the stack.

**Comment by twizmwazin** [comment]
Should be fixed as of #383, let me know if I've misunderstood
