### ISSUE TITLE
top comment only mode

### ISSUE THREAD

**Issue by RustoMCSpit** [dessalines/jerboa#1134]
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

a selectable mode where only the parent comment shows, no children comments

**Comment by dessalines** [comment]
If someone wants to work on this, I can re-open.

**Comment by RustoMCSpit** [comment]
> If someone wants to work on this, I can re-open.

add a needs help tag and reopen

**Comment by dessalines** [comment]
See my other comment.

**Comment by RustoMCSpit** [comment]
> See my other comment.

i saw but you didnt add a 'needs help' tag, you just said someone could help. open it and add a 'needs help'
