### ISSUE TITLE
zoom out in comment sections

### ISSUE THREAD

**Issue by RustoMCSpit** [dessalines/jerboa#1135]
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

i want to see more comments at once

**Comment by bappitybup** [comment]
You can adjust the font size in Settings -> Look and Feel -> Font Size (Slider)
this works for me, though at the moment there is only one slider for the font size of the entire app.
