### ISSUE TITLE
Option to Disable 2FA

### ISSUE THREAD

**Issue by RUzOfuz5m** [dessalines/jerboa#1136]
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

I'm looking for a way to disable 2FA within the app. I hit [this](https://github.com/LemmyNet/lemmy/issues/3309) bug and locked myself out everywhere but jerboa.

**Comment by MV-GH** [comment]
Jerboa does not even support the option to enable 2FA yet. In the mean time a possible solution to your problem is, if you can connect it to Android Studio you will be able to read the database that Jerboa uses to store your JWT. Using that token you can disable the option.

**Comment by MV-GH** [comment]
[app-release.zip](https://github.com/dessalines/jerboa/files/12266252/app-release.zip)

Here you go, I added the option

**Comment by RUzOfuz5m** [comment]
Thank you for this but I installed it via F-Droid so they key doesn't match and Android will not let me install/update it. 

My phone isn't rooted but I've looked anyway and I cant find the token. I'm going to try and root, (not sure if I can with GrapheneOS) backup my app data, install this, then restore later today. 

Thanks all!

**Comment by MV-GH** [comment]
> Android will not let me install/update it.

Play protect? you can disable it but the popup also gives an option to install it anyway

> My phone isn't rooted but I've looked anyway and I cant find the token. I'm going to try and root, (not sure if I can with GrapheneOS) backup my app data, install this, then restore later today.

If you have a google account and installed through play store (not sure about Fdroid). It will automatically back up the data. see https://developer.android.com/guide/topics/data/autobackup

You could also wait for the next release which is probably in a week

**Comment by RUzOfuz5m** [comment]
> Play protect? you can disable it but the popup also gives an option to install it anyway

No google account, no google play services or Play Protect. F-Droid doesn't back anything up as far as I know. If I ignore all the warnings and prompts I get "App not installed as package conflicts with an existing package." 

I'll message the admins, Thanks for trying! worst case I'll wait for the F-Droid update.
