### ISSUE TITLE
Animation when clicking the arrow next to the user name in the sidebar

### ISSUE THREAD

**Issue by Aloso** [dessalines/jerboa#114]
In the sidebar, the content moves on a diagonal axis when clicking the arrow next to the username, which I find quite irritating.

**Comment by dessalines** [comment]
Could you take a video of this? I'm not sure what you mean.

**Comment by Aloso** [comment]
https://user-images.githubusercontent.com/15658558/157520690-47366394-f4c6-45e4-a79e-b0df1c155c6e.mp4
