### ISSUE TITLE
ability to view replies in the inbox in separate tabs of what post the replies are to 

### ISSUE THREAD

**Issue by RustoMCSpit** [dessalines/jerboa#1140]
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

replies:
view by community [Y/N]

1) 'what is paper' in asklemmy
14 replies

2) 'dog running' in cutevideos
7 replies

**Comment by dessalines** [comment]
If someone wants to work on this, I can re-open.

**Comment by RustoMCSpit** [comment]
> If someone wants to work on this, I can re-open.

then dont close it and add a 'needs help' tag

**Comment by RustoMCSpit** [comment]
> This is more an issue tracker for ppl that are working on jerboa, and what we want to add. I'll re-open and assign it to you if you want to work on it tho.

how do you even code in kotlin, what foss ide are there? also, can you add a 'needs help' tag

**Comment by dessalines** [comment]
You'll have to watch some videos / learn how to do that. 

If I left issues open that its clear no one is going to work on, then we'd have thousands of open issues. I'll re-open issues only if someone is going to work on them.
