### ISSUE TITLE
add an in-app donate to lemmy

### ISSUE THREAD

**Issue by RustoMCSpit** [dessalines/jerboa#1141]
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

https://join-lemmy.org/donate

**Comment by RustoMCSpit** [comment]
having it hidden in settings is unideal, make it more prominent

**Comment by 0xFOSSMan** [comment]
do you want an extra button in the bottom or a banner on top? If somebody really wants to donate they will find a way into the about section.
