### ISSUE TITLE
integrate these features in-app

### ISSUE THREAD

**Issue by RustoMCSpit** [dessalines/jerboa#1142]
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

integrate these features in-app:

https://github.com/wescode/lemmy_migrate
https://github.com/CMahaff/lasim

also implement these graphs natively
https://fedidb.org/current-events/threadiverse
https://the-federation.info/platform/73#drawer-opened

**Comment by twizmwazin** [comment]
I personally think all of these are outside of the scope of jerboa, except maybe account migration, and even then I'd rather see lemmy implement that as a feature we can integrate rather than doing it ourselves.

**Comment by RustoMCSpit** [comment]
> I personally think all of these are outside of the scope of jerboa, except maybe account migration, and even then I'd rather see lemmy implement that as a feature we can integrate rather than doing it ourselves.

seeing the size of lemmy grow in app is massively interesting and easy to integrate. account migration can exist in more than one way

**Comment by dessalines** [comment]
No multi-issues.
