### ISSUE TITLE
option to make the plus button to the bottom right slightly transparent

### ISSUE THREAD

**Issue by RustoMCSpit** [dessalines/jerboa#1143]
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

.

**Comment by dessalines** [comment]
Doesn't seem like a good idea. FAB defaults are fine.

**Comment by RustoMCSpit** [comment]
> Doesn't seem like a good idea. FAB defaults are fine.

can it be a setting??

**Comment by dessalines** [comment]
I'm not going to do it, but if you were to create a PR for it, I wouldn't be opposed. I imagine it'd require a lot of pointless custom code tho, and its better to just use jetpack compose's defaults.

**Comment by RustoMCSpit** [comment]
> I'm not going to do it, but if you were to create a PR for it, I wouldn't be opposed. I imagine it'd require a lot of pointless custom code tho, and its better to just use jetpack compose's defaults.

you could just hide it under a makeTransparent function
