### ISSUE TITLE
view edit history of other posts and comments

### ISSUE THREAD

**Issue by RustoMCSpit** [dessalines/jerboa#1147]
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

.

**Comment by MV-GH** [comment]
I don't think an API endpoint exists for that

**Comment by MV-GH** [comment]
see https://github.com/LemmyNet/lemmy/issues/3803
