### ISSUE TITLE
Make the bar under posts scrollable left and right

### ISSUE THREAD

**Issue by suoko** [dessalines/jerboa#1154]
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

Since I can't see the  buttton to comment under the posts, making the bar scrollable I could drag to the right and show the button.
The issue appears if you use large fonts

**Comment by MV-GH** [comment]
They have been implemented, closing as this should not be needed
