### ISSUE TITLE
Filter posts per title (blocklist)

### ISSUE THREAD

**Issue by Izheil** [dessalines/jerboa#1162]
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

Right now, if you want to block some post or type of post, you can either block a user or report a post in lemmy.

I think a blocklist of words to block from titles of the posts in the timeline could help when one wants to filter some kind of posts.

For example, let's say someone follows a tech-news community but they don't want to see news related to crypto. They could add the tag "crypto" to the list of blocked words in the title of posts, so that any post that has the word "crypto" in their title will not appear in their timeline nor in the community when browsing it from the app anymore.

This could be added as a global filter for all communities, so that it filters the blocked list of words from any post. That way the filter list settings could be implemented in the "settings" section of the app, as a new section there, so that these settings are linked to an account.

The other option would be adding it in the timeline "filter" popup so that one can add these filters per timeline or per community, which would be more work, and may not make as much sense.

**Comment by dessalines** [comment]
Doesn't exist in the lemmy back-end yet.

**Comment by Izheil** [comment]
It doesn't need to exist in the back-end, since it could be done using regex for filtering, but I understand if you don't want to add the feature.

For anyone else looking for the feature there are alternatives to jerboa for this:

- For android [Eternity for lemmy](https://f-droid.org/es/packages/eu.toldi.infinityforlemmy/) has this functionality. (Menu -> Settings -> Posts filter)
- For desktop you can use a tampermonkey/violentmonkey script like [this one](https://greasyfork.org/es/scripts/470852-lemmy-post-utilities-filter-posts-by-title).

**Comment by dessalines** [comment]
Those are using front-end hacks to manipulate data from the back-end, and they won't work across different lemmy apps and web interfaces. Not a good solution to app-specific functionality where they should exist in the lemmy back-end.
