### ISSUE TITLE
Use AGP 8.2 once Android Studio Hedgehog is released

### ISSUE THREAD

**Issue by MV-GH** [dessalines/jerboa#1177]
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

Can't upgrade yet to AGP 8.2, as only Android Studio Hedgehog supports it which is still in beta.

**Comment by dessalines** [comment]
This is done now.
