### ISSUE TITLE
[Proposal] Concrete backwards compatible API implementation

### ISSUE THREAD

**Issue by MV-GH** [dessalines/jerboa#1179]
This serves as detailed specification for how we want to actually implement a proper backwards compatible API.

*This imo preferable to the stable mainline as backporting fixes will be of significant complexity due to refactors. And allows a much better UX, by smoothly transitioning users between instance versions. Instead of having to physically change apps. Majority of the users are not even capable of downloading a older version from GitHub.*

The idea is that we will have generic API interface that is implemented by all versions of the API. There can be three changes between API routes from different versions:

- API route gets added. Add a function that returns if this feature is supported. Older version implement this route by throwing a error.
 Concrete example: 0.19+ will add instance blocking, Add `API.featureBlockInstanceSupported()`, and add the API route.
- API route gets removed. Similar as above, functionality should be available to check if it is available and the newer version throws a error.
- API routes its request/response changes. For this I propose we transform response/requests to a "universal" type. Concrete this means, it will usually be the modified latest datatypes. So that the response will the be same regardless of which version. Here are some examples from how this will look concrete:
  - [Move admin flag from person to local_user](https://github.com/LemmyNet/lemmy/pull/3403), pre 0.19 version APIs will map their datatype to the latest datatype by moving that field from person to local_user
  - [Ban reason required](https://github.com/LemmyNet/lemmy/pull/3326) -> RequestForm will always require ban, pre 0.19 will not utilize the field. And have featureFlag available to check if this is available.
  - [Offer cursor-based pagination instead of offset pagination](https://github.com/LemmyNet/lemmy/pull/3872) This is more a complex example as it deprecates page field instead it will have a "previous_id". Here we simply can't transform one to another as it requires different mechanics. So here instead we will have Either<oldResponse, newReponse>. The api transforms either to the left or right and the receivers checks which version it gets and uses the appropriate mechanic.

Another point to discuss, do we only create API version every minor change: 0.17, 0.18, 0.19. But then there should no breaking changes in the API in patch versions. Which historically has not been the case, since 0.18.1 added three sort types. 

There is also the issue that there are datatypes which are not automatically generated and live in Utils/Others currently. (UnreadOrAll, RegristrationMode, SortTypes, CommentSortType, ...) For those I propose they will all need to implement a function (as needed only when there is an actual change) `getSupportedTypes(version)`. Each enum field will have a version in which it is introduced and a nullable version in which it was removed. This allows it to retrieve the appropriate entries that are supported for that version. Note that this list might also be empty in case it is entirely removed/added in a newer version.

The mechanism to switch between version will work as follows, Inside changeLemmyInstance, createApi and createTempAPI, we will need a `getVersion(instance)` which calls `instance/nodeinfo/2.0.json`  Using that version we will switch to the appropriate concrete implementation. If the version is not supported we throw a Error, and the UI should display a dialog that this version is not supported. 
There is additional complexity, as this is a network request there will be period where the API will not be in a ready state. Options are:
- We should have a interim API, that indefinitely suspends every API method and cancels when the actual API is switched. There is also the possibility that network request for the version fails (instance down, no internet, ...). This should be integrated with AccountVerification to display a snackbar with a retry option.
- Make API instance nullable and in UI observe changes, Prob will need to become a ApiState itself too to detect failure at creating the api and responding accordingly

This specification makes no demands for how long these version should be supported. That is up to the discretion of the developers as they see fit if the added complexity is worth the prolonged support.

Another note that I have is that Pict-rs should not be part of this API and should be refactored into a separate API.

Feedback? @twizmwazin @dessalines or any others

**Comment by dessalines** [comment]
After writing all this below, again I want to stress that the lemmy API has not yet hit a "stable" / `1.0` status, and the large amount of work this will require would be **far better spent** on other areas / features. Supporting deprecated / dead API actions, only to have them be completely superceded in a *hopefully* short amount of time, will require a lot of work, and complicate the codebase.  

---

First and foremost, this needs to be compatible with the `copy_generated_types` script. We cannot and should not rely on manually adding / editing these types, except in the case of deprecation (and you could also even generate the deprecated types by checkout out that version of `lemmy-js-client`). 

Whether we use an interface or not is up to you, but it seems to me this strategy would be easiest:

- Hard code a `CURRENT_VERSION` in the codebase.
- Add an extra folder for `deprecated_api` content, where types and functions also contain which version number they work for (and assume they don't work on the `CURRENT_VERSION`), probably in a class, with a version, and member functions / API types for the changes.
- Store the back-end version in the API code, lets call this `API_BACKEND_VERSION`.
- On the specific deprecated actions, check the `API_BACKEND_VERSION` against the `CURRENT_VERSION` to do the necessary mappings.

> API route gets added. Add a function that returns if this feature is supported. Older version implement this route by throwing a error.

> API route gets removed. Similar as above, functionality should be available to check if it is available and the newer version throws a error.

These two are good, and simple enough. 

> API routes its request/response changes. For this I propose we transform response/requests to a "universal" type. Concrete this means, it will usually be the modified latest datatypes. So that the response will the be same regardless of which version. Here are some examples from how this will look concrete:

That's fine to me, if you want to map all the older types into new ones, but it may not always be a clean mapping. The examples you gave show some of the complexities, but we can't foresee all of them. Required data might move from one place to another, needing completely different API calls. Another one: Core data types like every timestamp column would need to support non-timezone and timezone versions, once https://github.com/LemmyNet/lemmy/pull/3496 is merged.

> But then there should no breaking changes in the API in patch versions. Which historically has not been the case, since 0.18.1 added three sort types.

You're right that we should really be using minor versions for any API changes, that's my bad. 

> There is also the issue that there are datatypes which are not automatically generated and live in Utils/Others currently. (UnreadOrAll, RegristrationMode, SortTypes, CommentSortType, ...) For those I propose they will all need to implement a function (as needed only when there is an actual change) getSupportedTypes(version)

That sounds fine to me, or a class which contains the API versions supported as a member var.

> Another note that I have is that Pict-rs should not be part of this API and should be refactored into a separate API.

Up to you, lemmy forwards the requests transparently to a locally running pictrs, and we would likely discover any pain-points as we upgrade pict-rs with lemmy-ui on our production installs.

**Comment by MV-GH** [comment]
#1284
