### ISSUE TITLE
List of moderator actions / moderation abilities

### ISSUE THREAD

**Issue by MV-GH** [dessalines/jerboa#1182]
A top-level issue for moderation abilities:

- [x] locking posts
- [x] feature / Unfeature post in community, local.
- [x] removing / restoring posts
- [x] removing / restoring comments
- [x] banning / suspending users
- [x] registration application queue
- [x] report queue
- [x] Admin view votes
- [x] mod priority - e.g. higher mods can kick lower mods
- [ ] locking entire comment chains (select top level and all sublevels are locked)
- [ ] deleting entire comment chains

**Comment by dessalines** [comment]
These are all done now, except for those last two, but they should be added as back-end features first.

**Comment by MV-GH** [comment]
They can be achieved already on the front end though?

**Comment by dessalines** [comment]
Locking specific comments doesn't exist in the back end, so it'd need an issue.

Deleting comment chains seem *could* be done via a front end loop, but I'd prefer that also be a back end ability where you only need to provide a single parent comment.

Both of these need back end issues, and probably separate ones here too.
