### ISSUE TITLE
Tap to close media

### ISSUE THREAD

**Issue by imCalebM** [dessalines/jerboa#1186]
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

When you tap media e.g photo the only way to get out is to use back or the top left back arrow. It would be handy to be able to tap the photo again to close.

This is on android

**Comment by MV-GH** [comment]
You mean the imageviewer? there is a gesture to back out too. Swipe up and it will back out

**Comment by MV-GH** [comment]
I honestly don't think this behaviour is wanted. @twizmwazin what do you think? 

You can make a discussion in c/jerboa to see some opinions. But I'll probably close this

**Comment by twizmwazin** [comment]
This is probably a behavior another reddit app did, where we have chosen to copy boost's behavior. An option is a good idea if people  want it but I don't think it is necessary given the options we already have.

**Comment by MV-GH** [comment]
If someone wants to add a option for it, they are welcome to do so
