### ISSUE TITLE
Error message stuck on top. 

### ISSUE THREAD

**Issue by olafur-palsson** [dessalines/jerboa#1187]
### Jerboa Version

0.0.44

### Android Version + Phone

Android 11, Xiaomi Redmi note 10 pro

### Describe The Bug

Clipped text on top 

"host lemmy.ml. No address associated with hostname"
![Screenshot_2023-08-19-10-53-08-113_com jerboa](https://github.com/dessalines/jerboa/assets/19432526/da8824cd-7edb-438a-bf65-981058c68d08)

### To Reproduce

1. Be offline
2. Load app
3. Go online
4. Load posts.

**Comment by MV-GH** [comment]
Comes from here
https://github.com/dessalines/jerboa/blob/7a90523139bfc499c84b9ff0e22b965ed8978728/app/src/main/java/com/jerboa/ui/components/home/HomeActivity.kt#L218-L228

This error that it shows is intended, it means that It could not load the /site. Which Jerboa needs for lots of things

Jerboa has some checks on startup, you probably saw one of them. A snackbar which showed failed to load instance. This verification triggers for a few things and always on startup. 

Jerboa needs to also do the verification in this specific case. When it loads the post successfully while /site is in a bad state.

**Comment by dessalines** [comment]
Can re-open if this is still an issue, but I don't know a good way to replicate.

**Comment by MV-GH** [comment]
I fixed the case where it hid behind the actionbar. So everything should be as expected
