### ISSUE TITLE
Keeps crashing on Android 8.0

### ISSUE THREAD

**Issue by DetroitLibertyPenguin** [dessalines/jerboa#1199]
### Jerboa Version

0.0.44

### Android Version + Phone

Android 8.0 + SM-.G930V (Galaxy s7?)

### Describe The Bug

As soon as I launch the up it shows GUI for A moment & then exits with error message indicating crash. 

### To Reproduce

Download from F-Droid. In stall.  Select from home screen.

### In the case of a crash or when relevant include the logs

Sorry no access to pc at this time.

**Comment by MV-GH** [comment]
I would really need crash logs for this, as I can not reproduce this on a Android 8. Do you remember some settings maybe? like did have it set to japanese? There was issue with that we fixed.

**Comment by hectorzg** [comment]
I'm also experiencing this on Android 13 and Jerboa 0.0.46 from F-Droid.

**Comment by MV-GH** [comment]
Could I please get the crash logs?

Without it I will not be able to fix this problem.

**Comment by DetroitLibertyPenguin** [comment]
No I didn't have it in Japanese. As far as I'm aware everything is 
more-or-less default on the device for a Samsung Galaxy S7. I had had it 
set to the Microsoft/Bing launcher rather than the default Samsung one, 
but changing that didn't change anything.

**Comment by MV-GH** [comment]
Do you know which locale you have it set to? (Language)

**Comment by MV-GH** [comment]
Wow I think I may found it by accident what caused this crash for android 9 and below on Samsung devices.

see https://issuetracker.google.com/issues/299503067

Though getting a strack trace would be invaluable at confirming if it is the above issue

**Comment by hectorzg** [comment]
Sorry I didn't know how to get the log file but I found that the issue was my lemmy instance (beehaw) so that's why you were unable to reproduce it. Anyway I appreciate your hardwork, the app is great.

**Comment by MV-GH** [comment]
Ah if its Beehaw you can turn off your internet, go to settings > About > crash logs, if it's something with datetime parse failure. Then it is indeed known and fixed

**Comment by MV-GH** [comment]
Does it still happen with the latest 0.0.47 release

**Comment by dessalines** [comment]
Stale.
