### ISSUE TITLE
Sort communities by displayed name rather than by invisible id

### ISSUE THREAD

**Issue by Dakkaron** [dessalines/jerboa#1203]
### Jerboa Version

0.0.44

### Android Version + Phone

Android 12, Fairphone 4

### Describe The Bug

When opening the side drawer (hamburger icon) the communities are sorted by their identification instead of by their display name, even though only the display name is displayed.

For example, the community "Haupteingang" is after "Linux" and before "Mikrocontroller", because main@feddit.de (which has the display name "Haupteingang") comes after linux@feddit.de and before mikrocontroller@feddit.de

### To Reproduce

1. Subscribe to linux@feddit.de, main@feddit.de and microcontroller@feddit.de
2. Open the side drawer
3. Communities are sorted in this order: "Linux", "Haupteingang", "Mikrocontroller"

It should be "Haupteingang", "Linux", "Microcontroller".

**Comment by MV-GH** [comment]
https://github.com/dessalines/jerboa/blob/a5d1b01a6b219ad524d5d97e897e6514058646d5/app/src/main/java/com/jerboa/ui/components/drawer/DrawerActivity.kt#L52

It is already supposed to be sorted by name, what you are suggesting is that we sort by "Title" of a community

**Comment by Dakkaron** [comment]
Ok, sorry for mixing up the terminology.

My suggestion was to sort by what the user actually sees. Otherwise, from the user's point of view, it's basically random sorting.

**Comment by Dakkaron** [comment]
Awesome, thanks!
