### ISSUE TITLE
Woerd image behavior on RTL

### ISSUE THREAD

**Issue by danialbehzadi** [dessalines/jerboa#1212]
### Jerboa Version

0.0.45

### Android Version + Phone

Android 13, Poco F1

### Describe The Bug

When tapping on images on a RTL locale, it places at a random location on canvas, making the user unable to see all of the image and it has weird behavior in zooming, etc.

Sample video: 

https://github.com/dessalines/jerboa/assets/3658678/eb33bb34-b6a1-4364-970e-34703f0eedda

### To Reproduce

Set locale of the app to Persian.

Open some images.

**Comment by MV-GH** [comment]
Hmm it does seem to work for some images, I'll report this to the image viewer we are using
