### ISSUE TITLE
ApiErrorToast shows empty toast

### ISSUE THREAD

**Issue by MV-GH** [dessalines/jerboa#1221]
turn internet off, watch as the empty toasts show up

**Comment by bappitybup** [comment]
do the toasts just show up after a while of doing nothing? I didn't see anything when I tried and when I tried to refresh it would display a toast with "Network error" but no empty ones?

Google Pixel 7 Pro, Android 13

**Comment by MV-GH** [comment]
Hmm can't reproduce this anymore but it was, just turn off internet and start up jerboa. Another issue that needs to be fixed is that it seems to inifinitely spam toasts. Normally it should only display 4 toasts for startup failure. (It does 2 http requests and each requests gets shown twice. one by the general network failure handle and the specific endpoint failure handler toast)

**Comment by bappitybup** [comment]
> Hmm can't reproduce this anymore but it was, just turn off internet and start up jerboa. Another issue that needs to be fixed is that it seems to inifinitely spam toasts. Normally it should only display 4 toasts for startup failure. (It does 2 http requests and each requests gets shown twice. one by the general network failure handle and the specific endpoint failure handler toast)

have you got another issue for this already?

**Comment by dessalines** [comment]
Can't repro...
