### ISSUE TITLE
Browse "local" of specific instance

### ISSUE THREAD

**Issue by jmigual** [dessalines/jerboa#1227]
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

Normally, I can browse all the communities of my local instance (e.g. programming.dev). However, sometimes I would like to browse all the communities of a specific instance. If I use the "all" feature I get all the federated instances instead. 

So, I suggest to add a way to browsing only browse a specific instance.

**Comment by dessalines** [comment]
Lemmy back-end doesn't have this yet.
