### ISSUE TITLE
Links not opening in browser

### ISSUE THREAD

**Issue by NewDark90** [dessalines/jerboa#1228]
### Jerboa Version

0.0.46

### Android Version + Phone

Android 13, pixel 7

### Describe The Bug

Clicking on a post external link forwards to the browser, but link is not used (goes to blank tab). May or may not be relevant, but default browser is Brave

### To Reproduce

Find any post with an external link

Click link

**Comment by Falmarri** [comment]
Could be this https://github.com/dessalines/jerboa/pull/1216 

Not sure why they decided to make this the default, took me a while to figure out what was going on.

**Comment by NewDark90** [comment]
Ah yes, unchecking "use private tabs if available" does fix the issue.

**Comment by ruffy91** [comment]
This also breaks Microsoft Edge as browser. It opens the browser but no link.
