### ISSUE TITLE
Weird PullRefreshIndicator placement on post

### ISSUE THREAD

**Issue by cppxor2arr** [dessalines/jerboa#1241]
### Jerboa Version

0.0.46

### Android Version + Phone

Android 13, Galaxy A52s 5G

### Describe The Bug

When refreshing a post, the refresh indicator is on the top left (it does flicker for a moment on the top center). It should be on the top center.

### To Reproduce

1. Navigate to a post
2. Pull down to refresh
3. See that the refresh indicator is on the top left instead of the top center

**Comment by MV-GH** [comment]
Fixed already in #1220, will be live in 0.0.47
