### ISSUE TITLE
Clicking on long images causes crash

### ISSUE THREAD

**Issue by lelgenio** [dessalines/jerboa#1250]
### Jerboa Version

0.0.46

### Android Version + Phone

Android 11, Moto G20

### Describe The Bug

When posts have big images, they are displayed correctly, but trying to click on them causes the app to crash.

It does not seem to affect everyone using jerboa, but most users, as seen in the comments of https://lemmy.ml/post/5505769

### To Reproduce

1. Go to https://lemmy.ml/post/5505769 or any post with a big image
2. Click on the image

### In the case of a crash or when relevant include the logs

https://gist.github.com/lelgenio/c0d1d97a337ea7f0e578221236c50f0d

**Comment by MV-GH** [comment]
I am pretty sure this is solved with #1246

**Comment by MV-GH** [comment]
I am closing this for now, you can reopen it, if you can reproduce this with 0.0.48
