### ISSUE TITLE
Crash with Lemmy 0.19.0-rc.1

### ISSUE THREAD

**Issue by frebib** [dessalines/jerboa#1251]
The only reason I updated to this Lemmy version is because the Lemmy docker image can't seem to have stable monotonic updates with respect to database migrations.

`` Stacktrace ``

com.google.gson.JsonIOException: java.lang.NumberFormatException: Expected an int but was 0.09256670639086446 at line 1 column 3048 path $.posts[0].counts.hot_rank
	at com.google.gson.Gson$3.read(SourceFile:14)
	at com.google.gson.Gson$3.read(SourceFile:16)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(Unknown Source:49)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(Unknown Source:49)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(Unknown Source:2)
	at com.google.gson.internal.bind.TypeAdapters$26$1.read(Unknown Source:105)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(Unknown Source:49)
	at androidx.compose.ui.platform.WeakCache.convert(Unknown Source:44)
	at retrofit2.OkHttpCall.parseResponse(Unknown Source:58)
	at retrofit2.OkHttpCall$1.onResponse(Unknown Source:4)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(Unknown Source:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@45de060, Dispatchers.Main.immediate]
Caused by: java.lang.NumberFormatException: Expected an int but was 0.09256670639086446 at line 1 column 3048 path $.posts[0].counts.hot_rank
	at com.google.gson.stream.JsonReader.nextInt(Unknown Source:235)
	... 14 more

`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 28
Thread time: 0 hr 0 min, 0 sec

`` END of thread info ``

`` Device info ``

Report ID: 74ed0574-1705-4921-9353-c38f7b72825e
Device ID: 3e4eacd3713e553b
Application version: 47
Default launcher: com.android.settings
Timezone name: Central European Standard Time
Timezone ID: Europe/Madrid
Version release: 13
Version incremental : 362b90b8e9
Version SDK: 33
Board: kona
Bootloader: unknown
Brand: OnePlus
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: OnePlus8
Display: lineage_instantnoodle-userdebug 13 TQ3A.230805.001 362b90b8e9
Fingerprint: OnePlus/OnePlus8/OnePlus8:13/RKQ1.211119.001/Q.129a9e4-1-2:user/release-keys
Hardware: qcom
Host: f72326c314c6
ID: TQ3A.230805.001
Manufacturer: OnePlus
Product: OnePlus8
Build time: 1695447443000
Build time formatted: 23-09-2023 07:37:23
Type: user
Radio: Q_V1_P14,Q_V1_P14
Tags: release-keys
User: root
User IDs: N/A
Is sustained performance mode supported: Yes
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: No
Thermal status: STATUS_NONE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 88
Battery remaining time: N/A
Is battery charging: No
Is device rooted: Yes
CPU Model: Qualcomm Technologies, Inc SM8250
Number of CPU cores: 8
Up time with sleep: 38 hr 8 min, 28 sec
Up time without sleep: 27 hr 7 min, 54 sec

`` END of Device info ``

`` Exit reasons ``

`` Exit reason #1 ``
Description: null
Importance: CACHED
Reason: LOW_MEMORY
Timestamp: 28-09-2023 08:23:52
`` END of exit reason #1 ``

 `` Exit reason #2 ``
Description: remove task
Importance: CACHED
Reason: USER_REQUESTED
Timestamp: 27-09-2023 22:25:49
`` END of exit reason #2 ``

 `` Exit reason #3 ``
Description: null
Importance: PERCEPTIBLE
Reason: SIGNALED
Timestamp: 25-09-2023 13:14:58
`` END of exit reason #3 ``

`` END of exit reasons ``

`` Application info ``

App name: Jerboa
Version code: 47
Version name: 0.0.47
Package name: com.jerboa
Short package name: jerboa
Flavor: N/A
Signatures: KvQuis6lLSzWNkzLFfVFwtoVsyk=
Is debuggable: No
First installed: 23-09-2023 23:18:27
Last updated: 23-09-2023 23:18:27
Requested permissions: android.permission.ACCESS_NETWORK_STATE, android.permission.INTERNET, android.permission.READ_MEDIA_AUDIO, android.permission.READ_MEDIA_IMAGES, android.permission.READ_MEDIA_VIDEO, com.jerboa.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION
Default prefs: N/A
Default prefs: N/A

`` END of Application info ``

`` Currently running foreground/background processes ``

N/A

`` END of running foreground/background processes info ``

**Comment by MV-GH** [comment]
Jerboa does not support yet 0.19. This is expected. Here it fails probably on the rank attribute which changed from a float to int.

**Comment by MV-GH** [comment]
Solved by #1284
