### ISSUE TITLE
Touch/click is registered at the last clicked location

### ISSUE THREAD

**Issue by bjoern-tantau** [dessalines/jerboa#1254]
### Jerboa Version

0.0.48

### Android Version + Phone

Android 13, Fairphone 3

### Describe The Bug

Often, after the app has been running for a while, it starts to register a click not at the location I actually click but where I had clicked before.

See the taps in this video first marking a comment as read and then when touching the home-icon it is marked as unread instead of taking me home:

https://github.com/dessalines/jerboa/assets/8307357/8b049c78-3e52-4093-b35a-d0191bf52167

It happens while scrolling through posts as well. When I want to open a post it opens the one where my finger last was after scrolling.

It goes away after restarting the application.

### To Reproduce

I don't know what triggers it. I only know that it starts happening after a while and then never goes away until I restart the app.

**Comment by dessalines** [comment]
This is just due to that not being an instant button.

**Comment by bjoern-tantau** [comment]
No, it happens with all buttons.

**Comment by dessalines** [comment]
Lemmy version and jerboa version? I can't replicate

**Comment by bjoern-tantau** [comment]
Hadn't been using Jerboa for a while. Tested since yesterday and didn't see this bug anymore. So I guess something fixed it. 👍
