### ISSUE TITLE
automatic link cleaning

### ISSUE THREAD

**Issue by RustoMCSpit** [dessalines/jerboa#1257]
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

remove trackers from links automatically

**Comment by dessalines** [comment]
Already done on the lemmy back-end.
