### ISSUE TITLE
search bar to seatch through saved posts

### ISSUE THREAD

**Issue by RustoMCSpit** [dessalines/jerboa#1261]
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

search bar fot svaed posts tab

**Comment by Snow4DV** [comment]
Went through the current implementation of saved posts' fetching. It is not currently supported by lemmy ([here's what i'm talking about](https://lemmy.readme.io/reference/get_user)) so we can only select saved posts by community id and not by a part of title/post text/etc. 

Should be asked for in lemmy's repo

**Comment by dessalines** [comment]
Ya, open up an issue in the Lemmy back end for this if you would.

**Comment by dessalines** [comment]
No, because this one is my personal github, and lemmynet is a different org.
