### ISSUE TITLE
ability to sort saved posts by the time they were saved at

### ISSUE THREAD

**Issue by RustoMCSpit** [dessalines/jerboa#1262]
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

if i save something today, it should be at the top for example

**Comment by MV-GH** [comment]
This needs a backend change, we dont have the capability as a client to sort by the time they were saved at. Not sure even if the backend even stores that timestamp atm.

**Comment by RustoMCSpit** [comment]
> This needs a backend change, we dont have the capability as a client to sort by the time they were saved at. Not sure even if the backend even stores that timestamp atm.

could you port this issue over then

**Comment by MV-GH** [comment]
I can't transfer this issue to LemmyNet/Lemmy, Can you recreate it at Lemmy and link it there to here

**Comment by dessalines** [comment]
Stale issue.

**Comment by RustoMCSpit** [comment]
> Stale issue.

whats wrong with it

**Comment by dessalines** [comment]
It needs someone to work on adding this to lemmy back-end. If you want to work on it, you can open up an issue there, and we can assign it to you.

**Comment by dessalines** [comment]
Not too bad IMO, but you'll have to self-educate.
