### ISSUE TITLE
filter saved posts by posts youve made

### ISSUE THREAD

**Issue by RustoMCSpit** [dessalines/jerboa#1263]
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

all posts i made should be able to have their own category in the saved posts tab

**Comment by dessalines** [comment]
This isn't a feature in lemmy, and also you already have your own made posts tab.
