### ISSUE TITLE
Crash scrolling through top all time comments

### ISSUE THREAD

**Issue by amigan** [dessalines/jerboa#1268]
### Jerboa Version

0.0.49

### Android Version + Phone

Android 13, Pixel 6

### Describe The Bug

Scrolling through my own comments sorted by top/all time, the app crashes after scrolling to the same distance each time. Judging from the http client logs, it looks like a pagination issue, with two separate page responses both returning a comment with the same ID. The UI doesn't deduplicate this and it leads to a crash.

### To Reproduce

1. Go to my comments.
2. Sort top/all.
3. Scroll down.
4. Watch crash.

### In the case of a crash or when relevant include the logs

<http responses redacted, please mail me if you need them>
10-22 10:53:49.600  5885  5932 I okhttp.OkHttpClient: <-- END HTTP (48190-byte body)
10-22 10:53:49.617  5885  5885 D AndroidRuntime: Shutting down VM
10-22 10:53:49.618  5885  5885 E AndroidRuntime: FATAL EXCEPTION: main
10-22 10:53:49.618  5885  5885 E AndroidRuntime: Process: com.jerboa, PID: 5885
10-22 10:53:49.618  5885  5885 E AndroidRuntime: java.lang.IllegalArgumentException: Key "4902" was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(Unknown Source:182)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.foundation.lazy.layout.LazyLayoutMeasureScopeImpl.measure-0kLqBqw(Unknown Source:33)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1$measuredItemProvider$1.getAndMeasure(Unknown Source:18)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke(Unknown Source:617)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.navigation.compose.NavHostKt$NavHost$14$1.invoke(SourceFile:17)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(Unknown Source:91)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(Unknown Source:45)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.material3.ComposableSingletons$AppBarKt$lambda-2$1.invoke-3p2s80s(Unknown Source:60)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.material3.ComposableSingletons$AppBarKt$lambda-2$1.invoke(SourceFile:73)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.layout.LayoutModifierImpl.measure-3p2s80s(Unknown Source:12)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(Unknown Source:10)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.material3.ComposableSingletons$AppBarKt$lambda-2$1.invoke-3p2s80s(Unknown Source:19)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.material3.ComposableSingletons$AppBarKt$lambda-2$1.invoke(SourceFile:76)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.layout.LayoutModifierImpl.measure-3p2s80s(Unknown Source:12)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(Unknown Source:10)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(Unknown Source:5)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(Unknown Source:10)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at okhttp3.internal.http2.Http2Connection$1.invoke(SourceFile:17)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at okhttp3.internal.http2.Http2Connection$1.invoke(SourceFile:13)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at kotlin.UNINITIALIZED_VALUE.observe(Unknown Source:63)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(Unknown Source:66)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(Unknown Source:75)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:12)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(Unknown Source:109)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(Unknown Source:110)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.foundation.layout.BoxKt$boxMeasurePolicy$1.measure-3p2s80s(Unknown Source:220)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(Unknown Source:45)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.foundation.layout.FillNode.measure-3p2s80s(Unknown Source:101)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(Unknown Source:10)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at okhttp3.internal.http2.Http2Connection$1.invoke(SourceFile:17)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at okhttp3.internal.http2.Http2Connection$1.invoke(SourceFile:13)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at kotlin.UNINITIALIZED_VALUE.observe(Unknown Source:63)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(Unknown Source:66)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(Unknown Source:75)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:12)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(Unknown Source:109)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(Unknown Source:110)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.foundation.lazy.layout.LazyLayoutMeasureScopeImpl.measure-0kLqBqw(Unknown Source:55)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.ActualKt.getAndMeasure-SGf7dI0(Unknown Source:9)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.foundation.pager.PagerMeasurePolicyKt$rememberPagerMeasurePolicy$1$1.invoke(Unknown Source:763)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.navigation.compose.NavHostKt$NavHost$14$1.invoke(SourceFile:17)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(Unknown Source:91)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(Unknown Source:45)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.material3.ComposableSingletons$AppBarKt$lambda-2$1.invoke-3p2s80s(Unknown Source:60)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.material3.ComposableSingletons$AppBarKt$lambda-2$1.invoke(SourceFile:73)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.layout.LayoutModifierImpl.measure-3p2s80s(Unknown Source:12)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(Unknown Source:10)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.material3.ComposableSingletons$AppBarKt$lambda-2$1.invoke-3p2s80s(Unknown Source:19)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.material3.ComposableSingletons$AppBarKt$lambda-2$1.invoke(SourceFile:76)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.layout.LayoutModifierImpl.measure-3p2s80s(Unknown Source:12)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(Unknown Source:10)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(Unknown Source:5)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(Unknown Source:10)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.foundation.layout.FillNode.measure-3p2s80s(Unknown Source:101)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(Unknown Source:10)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at okhttp3.internal.http2.Http2Connection$1.invoke(SourceFile:17)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at okhttp3.internal.http2.Http2Connection$1.invoke(SourceFile:13)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at kotlin.UNINITIALIZED_VALUE.observe(Unknown Source:63)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(Unknown Source:66)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(Unknown Source:75)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:12)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(Unknown Source:109)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(Unknown Source:54)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded(Unknown Source:130)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(Unknown Source:128)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout(Unknown Source:61)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.node.Owner.measureAndLayout$default(Unknown Source:3)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(Unknown Source:18)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.view.View.draw(View.java:23269)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:22133)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:22089)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:22089)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:22089)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:22089)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:22089)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:22089)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:689)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:695)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:793)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.view.ViewRootImpl.draw(ViewRootImpl.java:4789)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4500)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3687)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2371)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9297)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:899)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:832)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:942)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7918)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
10-22 10:53:49.618  5885  5885 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
10-22 10:53:49.665  1686  6025 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
10-22 10:53:49.665  1686  3194 W ActivityTaskManager:   Force finishing activity com.jerboa/.MainActivity
10-22 10:53:49.674  5885  5885 I Process : Sending signal. PID: 5885 SIG: 9

**Comment by MV-GH** [comment]
Weird that it does return the same comment twice, might indicate a issue with the backend none the less I will add a deduplication guard

**Comment by amigan** [comment]
theamigan@lemmy.dynatron.me
