### ISSUE TITLE
App icon not showing up after install on Android

### ISSUE THREAD

**Issue by 3-w-c** [dessalines/jerboa#128]
Thank you for this app, and for all that you do :pray: 

On Android 11 (LineageOS), I see a lovely app icon for Jerboa (0.0.10) in F-Droid (1.14):
![image](https://user-images.githubusercontent.com/66082850/159810356-e6a79062-5e52-496f-b3b0-effe078c34be.png)

In my launcher (Nova 6.2.19), it seems to be using the default Android app icon.
![image](https://user-images.githubusercontent.com/66082850/159811292-acf4f2b6-3de3-40c6-8804-56032e16d150.png)

Sorry not to be able to suggest a fix, I don't know much about Android :sweat_smile: Let me know if there's any other details that'd be helpful.

**Comment by dessalines** [comment]
Not really sure what I can do about this one. I'm correctly setting the icon here: https://github.com/dessalines/jerboa/blob/main/app/src/main/AndroidManifest.xml#L14

A few possibilities: you installed an older version before I did that, and nova isn't correctly replacing it? Or maybe the icon cache on your device isn't updating properly? Not sure.

The only thing I can think of is to uninstall then reinstall.

**Comment by BluePixel4k** [comment]
I have the same problem on Android 12 (GrapheneOS) and Android 11 (LineageOS). I also reinstalled it once, but it did not solve the problem.

I use the default launcher from the OS.

![Jerboa](https://user-images.githubusercontent.com/77979781/160234968-3cca2206-c0d4-4a1f-89f7-00ce41790c71.png)

**Comment by dessalines** [comment]
What version?

**Comment by dessalines** [comment]
Maybe some devices don't like the fact that its an SVG? I have this also installed on two different devices, android 11 and 12, both show the icon.

**Comment by dessalines** [comment]
I'd very much appreciate some help from android devs, because besides setting that app icon, I have no idea what to do.

**Comment by devinberg** [comment]
I'm on stock Android 9 and I see the same thing.

**Comment by BluePixel4k** [comment]
> What version?

0.0.12 and now 0.0.13. The bug still exists, unfortunately.

> Maybe some devices don't like the fact that its an SVG? I have this also installed on two different devices, android 11 and 12, both show the icon.

Weird...
