### ISSUE TITLE
Make bottom navbar shorter when not showing comment text

### ISSUE THREAD

**Issue by dessalines** [dessalines/jerboa#1280]
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

The bottom navbar has some pointless margins when text is turned off. Example:

![Screenshot_20231121_093929_Jerboa](https://github.com/dessalines/jerboa/assets/930215/296eabea-b6c6-407a-b6a3-8838e5ede381)

**Comment by MV-GH** [comment]
Not sure what this means, there is already an option to completely hide the bottombar and there is also option to disable the text.

**Comment by MV-GH** [comment]
I already looked at trying that once, its not so simple since google follows the M3 standard, which has fixed height. You would have to override with a fixed smaller height.

**Comment by dessalines** [comment]
I'm def okay with that. Seems like such a common case that google will probably follow it eventually anyway.
