### ISSUE TITLE
Post cannot be sent when the content field is not clicked, after fixing a broken field

### ISSUE THREAD

**Issue by firefoxlover** [dessalines/jerboa#1282]
### Jerboa Version

0.0.50

### Android Version + Phone

Android 13 GrapheneOS, Pixel 4a

### Describe The Bug

When having a post condition that doesnt allow uploading and fixing that condition, the state is not reloaded until clicking on the "content" field.

This does not happen when just moving the focus (clicking) on the URL box, it only activated the post when clicking in the content field

### To Reproduce

1. Create a post with some error, for example no title
2. create a content
3. oh no, "send" button greyed out, so add a title
4. try to send it, still greyed out
5. now click in the "content" field and do not change anything
6. try to send it, it works

**Comment by MV-GH** [comment]
https://github.com/dessalines/jerboa/assets/67873169/d2c9b6ce-0ccb-425f-b005-49a81b457aa9

I can't reproduce this (According to steps provided)

**Comment by firefoxlover** [comment]
yeah me neither? Weird
