### ISSUE TITLE
Remove account / profile if the account is connected to a dead instance.

### ISSUE THREAD

**Issue by dessalines** [dessalines/jerboa#1289]
### Jerboa Version

0.0.51

### Android Version + Phone

Android13

### Describe The Bug

Before switching to an account, we should see if its a dead instance, so that it won't fail verification checks and crash jerboa.

Context #1288

### To Reproduce

1. Startup app
2. App will crash because its connected to a dead instance.

**Comment by MV-GH** [comment]
I was more thinking by adding a check in the verifications step. When it encounters this issue it will display the appropriate action. (remove account). This way its more explicit. Or could be that the instance is only temporary down.
