### ISSUE TITLE
Crash upon login

### ISSUE THREAD

**Issue by Psyklax** [dessalines/jerboa#1296]
### Jerboa Version

0.0.50

### Android Version + Phone

Android 12 Ulefone Power Armor 13

### Describe The Bug

When I log in on one instance, the app works norma
lly, but crashes on another instance. All settings unchanged between logins. 

### To Reproduce

Go to add an account
Select lemmy.ml from dropdown
Enter username and password
Press "Login"
"Jerboa has stopped"

### In the case of a crash or when relevant include the logs

`` Stacktrace ``

java.lang.IllegalStateException: You must either set a text or a view
	at com.android.internal.util.Preconditions.checkState(Preconditions.java:215)
	at android.widget.Toast.show(Toast.java:191)
	at com.jerboa.model.LoginViewModel$login$1.invokeSuspend(Unknown Source:637)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:109)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1cd9f1e, Dispatchers.Main.immediate]

`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 30
Thread time: 0 hr 0 min, 2 sec

`` END of thread info ``

`` Device info ``

Report ID: 6d31bdec-a167-4285-a84f-a3fb073bc72d
Device ID: eb2595acd6d156fa
Application version: 50
Default launcher: com.android.launcher3
Timezone name: Eastern Standard Time
Timezone ID: America/New_York
Version release: 12
Version incremental : 1675935266
Version SDK: 31
Board: Gotron-GQ3096TF3
Bootloader: unknown
Brand: Ulefone
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: Power_Armor_13
Display: S7TS68B7.GQU.Ulefone.HB.HJ.AZVKPVFPEYDYTY8PTAE.20230223.V3.01
Fingerprint: Ulefone/Power_Armor_13/Power_Armor_13:12/SP1A.210812.016/1675935266:user/release-keys
Hardware: mt6785
Host: bs
ID: SP1A.210812.016
Manufacturer: Ulefone
Product: Power_Armor_13
Build time: 1675935266000
Build time formatted: 09-02-2023 04:34:26
Type: user
Radio: MOLY.LR13.R1.MP.V164.P3,MOLY.LR13.R1.MP.V164.P3
Tags: release-keys
User: pri
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: Yes
Is in interactive state: Yes
Is ignoring battery optimizations: No
Thermal status: STATUS_NONE
Location power save mode: MODE_FOREGROUND_ONLY
Is device idle: No
Battery percentage: 13
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: MT6785V/CD
Number of CPU cores: 8
Up time with sleep: 97 hr 26 min, 21 sec
Up time without sleep: 34 hr 22 min, 5 sec

`` END of Device info ``

`` Exit reasons ``

`` Exit reason #1 ``
Description: null
Importance: CACHED
Reason: SIGNALED
Timestamp: 15-12-2023 13:40:48
`` END of exit reason #1 ``

 `` Exit reason #2 ``
Description: remove task
Importance: CACHED
Reason: USER_REQUESTED
Timestamp: 15-12-2023 06:35:22
`` END of exit reason #2 ``

 `` Exit reason #3 ``
Description: crash
Importance: FOREGROUND
Reason: CRASH
Timestamp: 14-12-2023 19:57:36
`` END of exit reason #3 ``

`` END of exit reasons ``

`` Application info ``

App name: Jerboa
Version code: 50
Version name: 0.0.50
Package name: com.jerboa
Short package name: jerboa
Flavor: N/A
Signatures: c80qNSw9NUKgqci9/TrHLtzCTSw=
Is debuggable: No
First installed: 13-12-2023 17:49:28
Last updated: 13-12-2023 17:49:28
Requested permissions: android.permission.ACCESS_NETWORK_STATE, android.permission.INTERNET, android.permission.READ_MEDIA_AUDIO, android.permission.READ_MEDIA_IMAGES, android.permission.READ_MEDIA_VIDEO, com.jerboa.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION
Default prefs: N/A
Default prefs: N/A

`` END of Application info ``

`` Currently running foreground/background processes ``

N/A

`` END of running foreground/background processes info ``

**Comment by dessalines** [comment]
Upgrade to the current version, `v0.0.54`

**Comment by Psyklax** [comment]
I have, and it works. Sorry to bother you.
