### ISSUE TITLE
Failed to verify JWT token when opening Jerboa/accessing the profile/notifications tab on feddit.de

### ISSUE THREAD

**Issue by Aipathon** [dessalines/jerboa#1299]
### Jerboa Version

0.0.50

### Android Version + Phone

Android 10 LG K61

### Describe The Bug

When opening Jerboa or trying to access your notifications/profile I always get the error showing "failed to verify JWT Token". This error occurs on feddit.de

### To Reproduce

1. Open Jerboa on feddit.de
2. See the Error

1. Open Jerboa on feddit.de
2. Click on the Profile/notifications tab
3. See the Error

**Comment by DasSkelett** [comment]
I assume duplicate of #1285, try upgrading to 0.0.51 or above for Lemmy 0.19 Support

**Comment by MV-GH** [comment]
Yes indeed, It's taking quite some time for the updated version to land on gplay

**Comment by dessalines** [comment]
Google play finally approved it a few hours ago 😮‍💨
