### ISSUE TITLE
Subsribed list times out

### ISSUE THREAD

**Issue by mhzawadi** [dessalines/jerboa#1301]
### Jerboa Version

0.0.52

### Android Version + Phone

Android 12, Realme x50 pro

### Describe The Bug

when viewing Subscribed communities, after 10 posts a red `Posts failed loading, retry` is shown this happens on my instanace: lemmy.horwood.cloud

### To Reproduce

1. set your site settings to `type: Subscribed`
2. set your site settings to `Sort type: New`
3. open jerboa and scroll down
4. see red error

### In the case of a crash or when relevant include the logs

![Screenshot_2023-12-18-07-19-48-04_a10f969cf1c4adf2c503042b459b8476](https://github.com/dessalines/jerboa/assets/11944327/956f20c9-14a3-442c-8751-df687e24d23b)

**Comment by mhzawadi** [comment]
Found this in my lemmy container `2023-12-18T07:45:17.824110Z  WARN lemmy_server::root_span_builder: CouldntGetPosts: legacy pagination cannot be combined with v2 pagination`

**Comment by MV-GH** [comment]
Weird that we can combine that for other sort options @dessalines ?

This is probably done easier in at API Client level

**Comment by mhzawadi** [comment]
FYI: this only happens for subscribed, all and local are fine. If that helps

**Comment by pcouy** [comment]
Please see this comment : https://github.com/dessalines/jerboa/commit/9463f78cbbe0270e2bc44f25771ef9e855e7db76#r135232518
