### ISSUE TITLE
Getting incorrect_login toast when uploading an image 

### ISSUE THREAD

**Issue by lightrush** [dessalines/jerboa#1303]
### Jerboa Version

0.0.54

### Android Version + Phone

Pixel 8 Pro 

### Describe The Bug

Just updated to Jerboa 0.0.54 via the Play Store. The instance is lemmy.ca which runs 0.19. I tried adding an image to a comment and I got a toast with a message "incorrect_login":

![Screenshot_20231218-105359~4](https://github.com/dessalines/jerboa/assets/2876507/bc451397-4da8-48fc-93b4-5767b77519d9)

The problem seems to persist across accounts. I've only tested on lemmy.ca. Uploading an image via the web app seems fine.

### To Reproduce

1. Tap on the new post button (FAB)
2. In Body, tap the image button
3. Pick an image

Expected: the image is uploaded
Actually: incorrect_login toast shows up

**Comment by MV-GH** [comment]
@dessalines did `cookie: auth` get removed? It no longer seems to work I get 401 with the incorrect_login back now.

**Comment by MV-GH** [comment]
I see, I currently use the cookie due to being easier implement (for pictrs, its on the backlog to change this)
