### ISSUE TITLE
Crashes on login 

### ISSUE THREAD

**Issue by Glimpythegoblin** [dessalines/jerboa#1306]
### Jerboa Version

0.0.50

### Android Version + Phone

Android 11, Moto G Power 2021

### Describe The Bug

App crashes when logging into account.  Would not verify account after lemm.ee update.     Cleared app cache with no result.  

### To Reproduce

Add account.  
Sign in
App crashes after inputting credentials and hitting log in.

**Comment by dessalines** [comment]
This is fixed in newer versions.
