### ISSUE TITLE
Timeout when trying to comment 

### ISSUE THREAD

**Issue by Aipathon** [dessalines/jerboa#1307]
### Jerboa Version

0.0.55 

### Android Version + Phone

Android 10 LG K61

### Describe The Bug

Sometimes when I try to comment on posts I get a timeout(see the screenshot for the full error). I don't know if this happens on all instances, but it happens at least on feddit.de.

![Screenshot_20231220-064343](https://github.com/dessalines/jerboa/assets/148320888/63b6aa73-cdba-4b15-8d69-71a8f141eb97)

### To Reproduce

1: go to the comment section of a comment section
2: write a comment
3: Try to send the comment
4: See the Error 

### In the case of a crash or when relevant include the logs

There are no crash logs to paste.

**Comment by dessalines** [comment]
That's a feddit.de issue
