### ISSUE TITLE
Community view only lets you scroll down 10 posts

### ISSUE THREAD

**Issue by clemdemort** [dessalines/jerboa#1313]
### Jerboa Version

0.0.55

### Android Version + Phone

Android 11

### Describe The Bug

When looking at a single community the feed only scrolls to the 10th post and nothing loads after that like if there was no other post in the community (around 10 other posts are available if you change the sort) when new posts should load under the last post

### To Reproduce

1 open jerboa
2 open any community page
3 scroll down

### In the case of a crash or when relevant include the logs

Merry Christmas 🎄

_No response_

**Comment by MV-GH** [comment]
Can't reproduce this

Which community, sort, instance, listing (local, all), ...

https://github.com/dessalines/jerboa/assets/67873169/14e5f0a2-e6d8-4096-a7a0-49c587851a84

**Comment by clemdemort** [comment]
https://github.com/dessalines/jerboa/assets/62178977/e5ab8fc7-cbe6-4d94-b0fc-3cfc7b1e507e

I'm connected to lemmy.world 
In the video I show that you can scroll 10+ posts on the main feed with all the communities together, while on the page of a single community which is 196@lemmy.blahaj.zone in the video, I can't scroll down forever, it blocks at ten posts
I also show that if you change the sort the same thing happens.

Hope that helps :)
