### ISSUE TITLE
Change app name to Lemmy

### ISSUE THREAD

**Issue by paulo-roger** [dessalines/jerboa#1322]
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

Several users ask me which app they should use, others tell me that Lemmy doesn't even have an official app. So they don't trust.

I think renaming **Jerboa** to **Lemmy** would be helpful for new users and more intuitive.

This is just a suggestion, I could be wrong and I'm only saying this because I wish Lemmy much success.

Thanks

**Comment by dessalines** [comment]
Lemmy is the name of the back-end software, this app is distinct from that. Jerboa started as a side project of mine, and even if we eventually absorb it into the LemmyNet org, there wouldn't be much point in making it "official". 

What matters is that people can search for the term "Lemmy" in app stores, and it will show all the clients.

**Comment by paulo-roger** [comment]
I see thank you for explaining.
