### ISSUE TITLE
Long press to hide comment

### ISSUE THREAD

**Issue by BalabakMan** [dessalines/jerboa#133]
Long press the comment box to hide the comment.Hidden comment will collapse comments thread under it.If the hidden comment is under a comment thread,the upper comment remain unaffected.

**Comment by dessalines** [comment]
You do this by holding on the header, not the whole comment box. I want to leave that action for other potential things.

**Comment by vboykox** [comment]
how to select text in the post?

**Comment by dessalines** [comment]
Click the view source button.
