### ISSUE TITLE
Replace ImmutableList with list entry in stability fix config file

### ISSUE THREAD

**Issue by MV-GH** [dessalines/jerboa#1332]
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

There is new feature which allows us to specify what we consider stable to the compose compiler. We could make use of this to declare that `List` is stable, thus the need for ImmutableList becomes nil, and we can get rid of this third party library.

This does have a sneaky consequence, it won't recompose anymore if we mutate a mutableList somewhere that we pass as List to a composable. Instead this needs to be done now like ImmutableList (create new list), only we won't have compile time safety for this now.

I consider this a worthwhile tradeoff. What do you think @dessalines ?

https://developer.android.com/jetpack/compose/performance/stability/fix#configuration-file

**Comment by dessalines** [comment]
That seems fine to me. We shouldn't be passing around mutableLists anyway... all functions where we do need to alter list data should take in and return lists, even if internally they use `.toMutableList()`
