### ISSUE TITLE
All community pages are broken in `0.0.56`

### ISSUE THREAD

**Issue by dessalines** [dessalines/jerboa#1348]
### Jerboa Version

0.0.56

### Android Version + Phone

all

### Describe The Bug

Every community page displays "Couldn't find community". 

### To Reproduce

1. Click on any community page
2. It displays the error above

### In the case of a crash or when relevant include the logs

NA

**Comment by MV-GH** [comment]
I also take a look into this rn
btw can you clean Lemmy Project Chat on Matrix

**Comment by dessalines** [comment]
I got it.
