### ISSUE TITLE
Question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [dessalines/jerboa#1353]
My APK scanner got a few additional checks implemented in January, and on today's release of Jerboa reported:

```
! repo/com.jerboa_57.apk declares sensitive permission(s): android.permission.READ_MEDIA_AUDIO
 android.permission.READ_MEDIA_IMAGES android.permission.READ_MEDIA_VIDEO
 android.permission.READ_EXTERNAL_STORAGE
```

My *guess* is this is so local media can be included with posts – but as the app description does not mention it, I thought I'd better make sure before stating so in the permission descriptions:

![image](https://github.com/dessalines/jerboa/assets/6781438/da353edb-c65d-4705-a8a9-0d13874322c2)

Oh, as for that `DEPENDENCY_INFO_BLOCK`, that's rather easy to get rid of:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

**Comment by dessalines** [comment]
Yeah its to allow you to upload local pictures and such. I'll add that dependenciesInfo block in a sec.

**Comment by IzzySoft** [comment]
Cool, thanks! So I've added the permissions to the allow list now:

![image](https://github.com/dessalines/jerboa/assets/6781438/744293d9-bab4-478d-9f5b-75ab8226dc0c)

**Comment by MV-GH** [comment]
`WRITE_EXTERNAL_STORAGE` is so that the user can store media on the device. (SDK 28 and below)

`ACCESS_NETWORK_STATE` is so that we can check if you have internet connection, as differentiate between no network enabled and no network receiving
