### ISSUE TITLE
On big fontsize, text gets cutoff

### ISSUE THREAD

**Issue by MV-GH** [dessalines/jerboa#1359]
### Jerboa Version

0.0.57

### Android Version + Phone

N/A

### Describe The Bug

When using a big fontsize, words get cut off.

Now (37px)
![f5c79872-e9dc-4a10-83bf-770b393f8da4](https://github.com/dessalines/jerboa/assets/67873169/fd2ec5f2-8151-43f4-8130-7a8edcf57f8b)

![08135188-25e7-4c2d-9b81-1cf967ac67c8](https://github.com/dessalines/jerboa/assets/67873169/41076772-ee2c-4d37-a568-4616fac139dc)

Previsously on 0.0.55 (29px)

![image](https://github.com/dessalines/jerboa/assets/67873169/acf028e6-f579-43d9-a8e9-5b07f11bddf2)

![image](https://github.com/dessalines/jerboa/assets/67873169/d4c57930-e4ec-4fdc-813c-57d8792edf55)

### To Reproduce

set fontsize to 38

This is probably related to `convertSpToPx` that got refactored in #1277  

this might be related to
![image](https://github.com/dessalines/jerboa/assets/67873169/1f75fa9f-f331-4a6b-8201-3e8f86fa70ef)

Also related https://github.com/dessalines/jerboa/issues/1338

**Comment by dessalines** [comment]
Here's the relevant SO issue: https://stackoverflow.com/questions/29664993/how-to-convert-dp-px-sp-among-each-other-especially-dp-and-sp#29665208

I'm not exactly sure what to look for in the first one.

The settings is def still an issue tho, until the next compose-settings release.

**Comment by MV-GH** [comment]
The first one cuts the title in the actionbar.

But to me the real problem only is that 29px is no longer the dame size.

According to the reported user  29 became equal to 38??

I can't really reproduce that.

The actionbar can't get bigger so the only solution is that it cuts of the words.There no way around that. Unless the desired behavior is that it stops increasing the size when it no longer fits. Which is quite bit more complicated to achieve.

The second pic was expected. Imo the thing that needs to be addressed is the px conversion changed. It should be roughly the same as before

**Comment by MV-GH** [comment]
This was found on the device `Kindle Fire HD 8, (10th gen tablet).` with Android 9. When I have some time I'll see if i can reproduce this somehow

**Comment by bappitybup** [comment]
I have Android 14, a Pixel 8 Pro
![Screenshot_20240216-103622](https://github.com/dessalines/jerboa/assets/12457072/8c11e9a1-621a-40a6-965a-c93e3032f0b7)

**Comment by dessalines** [comment]
That has to do with a bug in compose-settings. I made a fix for it but we're still waiting on its release.

**Comment by MV-GH** [comment]
I thought this was related to `convertSpToPx ` but we only use it for the markdown. So that couldn't it be. If there was a change it was due to change in the Compose framework itself. No actionable point that we can take. So I'll close this
