### ISSUE TITLE
Use full federated names, but use styling to mute / make the instance smaller

### ISSUE THREAD

**Issue by dessalines** [dessalines/jerboa#1364]
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

Use fully federated names, but play with styling and muting for the @instance part.

**Comment by MV-GH** [comment]
We can probably make this an option, but we already show the full name only not for your own instance, we can a option to also show it for your own instance. But I think there is a FR already for that

**Comment by dessalines** [comment]
It could be an option, but this might not be too bad as a default. I'll have pics for that PR in a bit.
