### ISSUE TITLE
Failing to add a new post does not show any errors

### ISSUE THREAD

**Issue by epragalakis** [dessalines/jerboa#1373]
### Jerboa Version

0.0.57

### Android Version + Phone

android 12

### Describe The Bug

After the update I am not able to create a new post.
On submit, there is a loading bar at the top but there are no visible errors on the screen.

### To Reproduce

1. Go to any community
2. try to post something (i tried multiple titles & body)
3. submit

### In the case of a crash or when relevant include the logs

no crash happened

**Comment by MV-GH** [comment]
Hmm i cant reproduce this

Which instance + community are you trying to post?

**Comment by epragalakis** [comment]
I now see an error after the most recent release, but it is not helpful on resolving the issue.
The error says: POST (and the URL): invalid 401 followed by '...' which hides the details of the error,


(Im guessing this is an authorization error but I'm not sure why.. so far I tried to log in and out again but nothing changes)

@MV-GH any lemmy.world on any instance.

(I'm using the app from the f-droid store if that makes any difference)

**Comment by epragalakis** [comment]
- I can see my inbox and all the other sections of the app without any errors (including changing my settings)
- I get the same error on comments
- username is: evasync@lemmy.world

**Comment by epragalakis** [comment]
I am able to login in a web browser and post normally, but I just noticed that when I refrresh the tab, it logs me out (there is nothing straight forward in the console or the network tab). 

I will contact the lemmy.world folks as it seems like its an issue with their server.

**Comment by MV-GH** [comment]
I just tried again with my lemmy.world account and everything works fine.

I'll see if i can fix it so that it won't cut off the error

Can you give me the name of the account. I'll check if u aren't banned. I don't think we display anything for that.

**Comment by MV-GH** [comment]
It works on Lemmy.world ui?  I saw that you posted recently. It must be on our side then. I would like to get on bottom of this. 

Would it be possible to install Android Studio and then installing the debug version of app to check the logs? Or can you wait until I post a version here that will show the full error log.

**Comment by epragalakis** [comment]
probably the second (my laptop is very old and have failed to run android studio in the past)
