### ISSUE TITLE
Remove bottom divider on comments

### ISSUE THREAD

**Issue by dessalines** [dessalines/jerboa#1388]
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

Almost all apps do this now, and it looks much cleaner.

**Comment by MV-GH** [comment]
Does it really look good? Can you give examples of apps that do this?

**Comment by dessalines** [comment]
I thought it looked weird at first, but surprisingly I think it does look cleaner.

Boost:

![Screenshot_2024-03-03-11-44-14-986-edit_com rubenmayayo lemmy](https://github.com/dessalines/jerboa/assets/930215/1bd53550-bfa1-40dd-95dc-b96a25535ce0)

Sync:

![Screenshot_2024-03-03-11-44-38-651-edit_io syncapps lemmy_sync](https://github.com/dessalines/jerboa/assets/930215/22a96346-0cd5-444a-b5f9-bd34881687fa)

Eternity (notably, doesn't even have top-level dividers)

![Screenshot_2024-03-03-11-46-02-294-edit_eu toldi infinityforlemmy](https://github.com/dessalines/jerboa/assets/930215/3050939f-9e5c-4e52-a7de-b24b79985f59)

**Comment by MV-GH** [comment]
wow, I never noticed boost did that
