### ISSUE TITLE
Make range of base font sizes smaller, and maybe allow them to be floats.

### ISSUE THREAD

**Issue by dessalines** [dessalines/jerboa#1392]
### Jerboa Version

0.0.59

### Android Version + Phone

Android 13

### Describe The Bug

Now that #1386 is merged, it doesn't make much sense to have really large font sizes. The usable scale seems to be about 8-24 . Really large font sizes are unusable

### To Reproduce

see above

### In the case of a crash or when relevant include the logs

NA

**Comment by MV-GH** [comment]
> Make range of base font sizes smaller

Are we talking about the constants?

**Comment by MV-GH** [comment]
Imo, i wouldn't scrimp it to that small range, if there are users that want it that big, they can have it even if it breaks a few UI elements. 

You will also have to write a migration script that sets the settings of users who have it higher to the new maximum.

**Comment by dessalines** [comment]
I'll just close this then, pry not necessary.
