### ISSUE TITLE
Move "Saved" from bottom navigation bar to profile

### ISSUE THREAD

**Issue by Fxsch** [dessalines/jerboa#1394]
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

I think `Saved` should be moved from the bottom navigation bar to a button on your profile.

6 options in the bottom navigation bar is kind of too much and also doesn't quite fit as you can see here:
![Screenshot_20240222-154353_Jerboa (1)](https://github.com/dessalines/jerboa/assets/77849217/5d894910-c219-47af-ab4e-56ddac30f03d)

The `Saved` option is also the one that I think is the least urgent to get to quickly.

On the web interface it's also at your profile, so people will probably search there first.

**Comment by Asudox** [comment]
I'd say make it an option in the settings. I use it pretty frequently tbh.

**Comment by Fxsch** [comment]
That would be good, I think. Maybe even add a setting where you can tick exactly which options you want to have in the navigation bar.

**Comment by dessalines** [comment]
If you have `show_navigation_bar` as false in the settings, it moves all these to your sidebar. That already seems like a better solution than adding tons of settings for every single item in the navbar.

**Comment by Fxsch** [comment]
I don't want to get rid of the navigation bar, I just don't want so many options in it that it doesn't even fit on the screen

**Comment by Fxsch** [comment]
It's also only an issue when you're a mod of a community and the `Reports` option gets added

**Comment by dessalines** [comment]
I'll re-open if someone wants to work on it, but I don't see myself adding this.
