### ISSUE TITLE
Add reports to sidebar

### ISSUE THREAD

**Issue by MV-GH** [dessalines/jerboa#1395]
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

@dessalines I think we forgot to add the reports nav button to the sidebar

**Comment by dessalines** [comment]
We're only currently showing those if the bottom navbar is disabled: 

https://github.com/dessalines/jerboa/blob/main/app/src/main/java/com/jerboa/ui/components/drawer/Drawer.kt#L240

**Comment by MV-GH** [comment]
Yes but if the bottombar is disabled does it list reports?

**Comment by MV-GH** [comment]
It does nvm
