### ISSUE TITLE
Non admin mods are unable to ban people

### ISSUE THREAD

**Issue by MV-GH** [dessalines/jerboa#1398]
### Jerboa Version

0.0.59

### Android Version + Phone

N/A

### Describe The Bug

![ezgif-3-2c47401774](https://github.com/dessalines/jerboa/assets/67873169/3fbfa59f-1acf-4ab6-a8d1-d364e7bfddb1)

A user reported that he could not ban people, as a non admin mod. Even though he can in Lemmy UI

The error in the pic does seem to indicate that this comes from the backend though.

### To Reproduce

ban a user a non admin mod

**Comment by dessalines** [comment]
Thx for finding that. 

As far as this issue, I should be able to check it out this upcoming week.
