### ISSUE TITLE
Tab font size too small

### ISSUE THREAD

**Issue by rottenwheel** [dessalines/jerboa#1403]
### Jerboa Version

0.0.60

### Android Version + Phone

Android 14, Google Pixel 7

### Describe The Bug

Font size of about, posts and comments tabs in the profile section is considerably smaller than in previous versions. Almost can't see it. 

Applies to tabs across the board, in messages too.

Notified you of this on Lemmy, opening the issue as per your request. Thanks for all the great work. 

### To Reproduce

Just run v0.0.60 and pay attention to tabs font size.

**Comment by MV-GH** [comment]
How it looked before:

![image](https://github.com/dessalines/jerboa/assets/67873169/a92f7074-9a25-4348-bb9f-92296c969175)

How it looks now

![image](https://github.com/dessalines/jerboa/assets/67873169/9c23e39f-87e1-4fa5-81d5-a63164dfc566)

By default tabs use this preset = TypographyKeyTokens.TitleSmall

Now: 
The default_font_size is 16px, for title small it reduces this by 7px, so 9px
Previously it did 16px * 0.8 = 12.8px

Currently it makes titleSmall the same size as bodySmall? 

I don't think this is wanted behaviour.

Actually all labels/headline/body/title have the same fontsize for their sizing (small/medium/large)

**Comment by MV-GH** [comment]
|                | Compose default in SP | Jerboa default in Px |
|----------------|-----------------------|----------------------|
| headlineLarge  | 32                    | 16                   |
| headlineMedium | 28                    | 13                   |
| headlineSmall  | 24                    | 9                    |
| titleLarge     | 22                    | 16                   |
| titleMedium    | 16                    | 13                   |
| titleSmall     | 14                    | 9                    |
| bodyLarge      | 16                    | 16                   |
| bodyMedium     | 14                    | 13                   |
| bodySmall      | 12                    | 9                    |
| labelLarge     | 14                    | 16                   |
| labelMedium    | 12                    | 13                   |
| labelSmall     | 11                    | 9                    |
| displayLarge   | 57                    | x                    |
| displayMedium  | 45                    | x                    |
| displaySmall   | 36                    | x                    |

**Comment by dessalines** [comment]
Its tough for us, because I can't find a good "official" way to do this using a custom base font size. This is the method I'm currently using in `Type.kt`

https://egeniq.com/blog/dynamic-font-sizes-with-jetpack-compose/

**Comment by dessalines** [comment]
Another point for us, is that `Headlines` in jetpack compose (for us, only used by the post title) look giant. I have a few other lemmy apps installed, and most of them use only a slightly larger post title.

**Comment by MV-GH** [comment]
`Headliens` is rarely usd anyway. So that one doesn't bother me. But we should do label/body/Title somewhat right ratios

**Comment by MV-GH** [comment]
Is there a reason we originally used pixels instead of DP ?

The default is the size you want the body Large text to be?

**Comment by dessalines** [comment]
iirc we originally used pixels because our last markdown library had some weird custom sizing issues. Anyways `sp` are the preferred font size units now.
