### ISSUE TITLE
Non admin mods can't see moderation menu from the main feed

### ISSUE THREAD

**Issue by MV-GH** [dessalines/jerboa#1411]
### Jerboa Version

0.0.60

### Android Version + Phone

n/a

### Describe The Bug

I looked into it, for moderators we give null in the feed because there is no list available

and then we do this

```
    val amAdmin =
        remember(admins) {
            amAdmin(
                admins = admins,
                myId = account.id,
            )
        }

    val amMod =
        remember {
            amMod(
                moderators = moderators,
                myId = account.id,
            )
        }
```

So both false, thus they cant see the menu

But since we cache those values in the account can't we just use those ?

### To Reproduce

..

**Comment by dessalines** [comment]
Yeah that should work fine also.

**Comment by MV-GH** [comment]
It was more complex than that because we store modding ability as true/false instead of the communities this user actually moderates. So I had to do a bit creatively
