### ISSUE TITLE
Swipe-to-vote gestures are backwards ("swipe right" to upvote)

### ISSUE THREAD

**Issue by maltfield** [dessalines/jerboa#1416]
### Jerboa Version

0.059

### Android Version + Phone

Android

### Describe The Bug

The UX for the swipe gesture is backwards, currently:
1. Swipe to the right is downvote and
2. Swipe to the left is upvote

The standard UX is:
1. Swipe to the right for things you like
2. Swipe to the left for things you don't like

For reference, see this article on How To Geek that describes "swipe right" vs "swipe left"
 * https://www.howtogeek.com/702931/what-do-swipe-left-and-swipe-right-mean/

Moreover, I expect that you'll find most reddit apps have "swipe right for upvote" and "swipe left for downvote". I can only speak to RedReader, which is widely recognized as the most user-accessible reddit app (so much so that it was given an exemption from the API changes so [RedReader could continue to use the reddit API for free](https://old.reddit.com/r/RedReader/comments/145du4j/update_4_redreader_granted_noncommercial/) -- because their UX is so good). And, yes, **RedReader has "swipe right for upvote" and "swipe left for downvote"**

The above-described UX is so commonly ingrained in our culture that it's become common slang. Consider the entry in Urban Dictionary for "swipe right"

 * https://www.urbandictionary.com/define.php?term=Swipe+right

> **Swipe Right**
> (verb) A phrase used to describe your acceptance of something.
> ...
> [example] "These burritos are so good! I'm glad we swiped right on Chipotle."

### Solution

The solution to this is to swap the directions of the votes on Jerboa, such that:

1. Swipe to the right is upvote and
2. Swipe to the left is downvote

### To Reproduce

1. Download Jerboa v0.0.59 from F-Droid
2. Tap on the hamburger menu
3. Tap on `Settings`
4. Tap on `Look and feel`
5. Tap on the `Preset for swipe gesture` drop-down menu
6. Tap on `Only votes`
7. Click the back button
8. Click the back button
9. Attempt to "swipe right" on something to upvote it
10. Post gets a downvote
11. Get confused

**Comment by MV-GH** [comment]
Thanks for the comprehensive bug report. Currently `Only votes` preset has left as downvote and right as upvote.



https://github.com/dessalines/jerboa/assets/67873169/05318d85-cb4e-4412-b5d8-dacdfe11e8d0

Very strange that is mirrored for you. Do you have RTL enabled? or language set with RTL?

**Comment by maltfield** [comment]
Your video shows swiping to the right is downvote.

**Comment by MV-GH** [comment]
Ah I see what you mean we can always add another option
