### ISSUE TITLE
View community moderators from community info screen

### ISSUE THREAD

**Issue by kinther** [dessalines/jerboa#1417]
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

Currently I don't seem to be able to view the moderators of a given community when clicking the three dots -> community info.

I would like to request the ability to see who is a moderator currently, and a link to their profile.

This is similar to the web interface, so this already exists (just not on mobile jerboa)
![Screenshot from 2024-03-01 12-34-00](https://github.com/dessalines/jerboa/assets/6426957/699a9596-144c-43c4-bca7-f7fe53bbb3a2)

**Comment by MV-GH** [comment]
duplicate #1343
