### ISSUE TITLE
Comments with a mention to yourself get duplicated into the Comments section when they shouldn't.

### ISSUE THREAD

**Issue by Asudox** [dessalines/jerboa#1438]
### Jerboa Version

0.0.61

### Android Version + Phone

Android 14, Google Pixel 8 Pro

### Describe The Bug

Using the web version of Lemmy, comments with mentions don't get put into the Comments section in Inbox, but only in the Mentions section. In Jerboa, however, the comment entry in the Mentions section gets duplicated into the Comments section.

### To Reproduce

1. Receive a comment with a mention to yourself
2. See the same comment entry in the Comments section and the Mentions section

**Comment by MV-GH** [comment]
@dessalines Does lemmy-ui have special behaviour for this?

**Comment by dessalines** [comment]
No, it also duplicates them, since a row is inserted in the `person_mention` table, and the API comes back with both. Its really a back-end bug, so I'll move it there.
