### ISSUE TITLE
Replies tab scrolling issue

### ISSUE THREAD

**Issue by Stugist** [dessalines/jerboa#1439]
### Jerboa Version

0.0.61

### Android Version + Phone

Android 13; Samsung S20FE 5g(SM-G781B/DS)

### Describe The Bug

With multiple new replies, scrolling doesn't go further than the top of the screen. I'm assuming that this issue will effect replies long enough to be longer than one full screen.

### To Reproduce

1. Goto Replies
2. Have more than one reply or a reply with a very large body
3. Try to scroll
4. ???

**Comment by MV-GH** [comment]
In inbox?

**Comment by Stugist** [comment]
Yes, in Inbox

**Comment by Stugist** [comment]
I should mention that I'm only getting this issue with the Unread filter on. Though when scrolling up specifically when filtering all I get a lot of stuttering.

**Comment by MV-GH** [comment]
Scrolling up and down or already with just scrolling down?

**Comment by MV-GH** [comment]
Of that we are aware see https://github.com/dessalines/jerboa/issues/1259

also I can scroll in replies?

https://github.com/dessalines/jerboa/assets/67873169/4fef2840-75a1-4474-a5a8-04c40ec837e5

But it hides a section behind the bottom navigation system bar. This is a bug that will fix
