### ISSUE TITLE
Allow changing the font size

### ISSUE THREAD

**Issue by KSPAtlas** [dessalines/jerboa#144]
The font size is too large IMO and I want to turn it down.

**Comment by dessalines** [comment]
It uses your system font size. I'm pretty overloaded at the moment, but when I eventually add settings, I can probably add app-specific settings like this.

**Comment by suoko** [comment]
@dessalines 
Actually when you write posts the font is too small. Smaller then the font used in the main feed page.
Can you make it the same size?

**Comment by suoko** [comment]
@dessalines 
Check the screenshots


![Screenshot_2022-09-19-21-57-17-878_com jerboa](https://user-images.githubusercontent.com/3659980/191105725-8c8d7cb7-fc3e-4140-a239-2d3a5442ee9a.jpg)
![Screenshot_2022-09-19-21-58-05-883_com jerboa](https://user-images.githubusercontent.com/3659980/191105782-33d48731-99cb-4497-b996-b8499b4831f6.jpg)

**Comment by dessalines** [comment]
Hrm that is pretty weird cause it doesn't look as pronounced on mine... I'll take a look.

**Comment by suoko** [comment]
> Hrm that is pretty weird cause it doesn't look as pronounced on mine... I'll take a look.

I use a xiaomi, maybe it's miui's fault?
