### ISSUE TITLE
Screenshots prevented by security settings

### ISSUE THREAD

**Issue by Xavienth** [dessalines/jerboa#1440]
### Jerboa Version

0.0.61

### Android Version + Phone

Samsung Galaxy A50

### Describe The Bug

When attempting to take a screenshot anywhere in the app (tested on main screen, comments, viewing media, and settings menu), it is prevented, with a system message banner saying it's due to security settings.

### To Reproduce

1. Open the app
2. Attempt to take a screenshot anywhere

**Comment by MV-GH** [comment]
Do you have this setting enabled? 
![image](https://github.com/dessalines/jerboa/assets/67873169/017ae518-dc0f-4a30-8d72-3e7573a99f76)

If so this is intended behaviour

I am guessing you didn't have this enabled before? Maybe we accidental enabled it somehow?

Let me see if I can find a cause

**Comment by Xavienth** [comment]
Yup, setting got enabled by the update.
