### ISSUE TITLE
Add comment sort type

### ISSUE THREAD

**Issue by BalabakMan** [dessalines/jerboa#147]
It is easier to see old and top comment this way.

**Comment by dessalines** [comment]
Sounds good, I think at least top, hot, new, and old should be supported.

**Comment by a1studmuffin** [comment]
I'm working on a PR for this one, sneak preview:

![image](https://github.com/dessalines/jerboa/assets/6295625/20b93fb3-5a31-4d0b-8c46-b4e35f43946c)

**Comment by ToNIX-** [comment]
That's nice, comments sorting would be a good addition to Jerboa!
