### ISSUE TITLE
Any plan to integrate moderation soon?

### ISSUE THREAD

**Issue by ashemsay** [dessalines/jerboa#153]
Hey, I really like the app, I find it more pleasant to use than lemmur but the only thing preventing me from migrating is the lack of a report button.
I find myself having to jump back to lemmur when I need to report something, it's kind of frustrating so I am sticking to lemmur for the moment.
It would be nice to have this, I hope I didn't just miss it somewhere, that would be embarassing... :)

**Comment by dessalines** [comment]
Yep, the report button already exists, click the three dot menu on any post or comment. Make sure you are on the newest version also.

**Comment by ashemsay** [comment]
Ok, indeed, I thought the F-droid version was up to date but it wasn't, grabbed the last version from the release page instead, everything's fine, sorry about that.
