### ISSUE TITLE
Add a "Show context" button to comment notifications

### ISSUE THREAD

**Issue by felipeforte** [dessalines/jerboa#155]
![image](https://user-images.githubusercontent.com/64996043/163219235-a32f1b22-d7fa-460a-9b6b-1e69bad473fd.png)

Currently, there is not option to "show context" in the menu. The three dots have the options "copy link" and "view source"

**Comment by dessalines** [comment]
Agree, this is very necessary. Lemmy-ui uses a front end hack to do this currently, because the best way to do it is to add a comment endpoint. Its probably one of the last bigger features lemmy is missing.
