### ISSUE TITLE
Share to function?

### ISSUE THREAD

**Issue by poVoq** [dessalines/jerboa#163]
Really strange that neither this nor Lemmur support integration with Android to share links to Lemmy from a browser etc., i.e. that I can use the share button of Firefox (or any other app) to open Jerboa to make a new post on Lemmy with the link (or the selected text) already pasted into the new post form.

At least with a Lemmy webapp that is really easy to add and probably one of the most useful features for posting stuff.

**Comment by dessalines** [comment]
Lemmy-ui doesn't have this, and it would be difficult to add for any federated service where the domain name could be anything.

Right now you do the same thing you have to do for lemmy-ui, which is to copy-paste any link urls into the create post URL field.

I'm not sure how this would be possible in any way for unpredictable lemmy domains.

**Comment by poVoq** [comment]
Uhm, maybe I am missing something but Lemmy-UI does have this. I used it in my uLemmy Ubuntu Touch app (currently unmaintaned as I broke my Nexus5).

It is a URL addition: `/create_post?body=` and `/create_post?url=`

**Comment by dessalines** [comment]
I have no idea how its able to do this, I didn't code anything for it. That URL link would work, but android is not going to know what app to open when the URL could be literally anything.

**Comment by poVoq** [comment]
Hmm, I guess that only works with webapps then?

Android knows of course which app to use as when Jerboa is registered as a "share to" end-point for URLs, then the user can select it from the list of apps that opens when you click on the share button.

**Comment by dessalines** [comment]
@LunaticHacker completed this.
