### ISSUE TITLE
Show favicon at instance

### ISSUE THREAD

**Issue by Tealk** [dessalines/jerboa#164]
Hi,

the app can manage multiple instances but unfortunately you can't tell them apart as only the username is displayed. Would it be possible to add the favicon or the instance name?

**Comment by dessalines** [comment]
No, for one jerboa has multiple account support, so which sites favicon would be appropriate?

Secondly all icons must be bundled with the android program, which isn't possible when signing up to an instance where you don't know the favicon beforehand.

**Comment by dessalines** [comment]
Ohh if you aren't talking about the app icon, then it might be possible to put the site icon somewhere. Where did you have in mind?

**Comment by Tealk** [comment]
I think we are talking at cross purposes
I mean here:
![Screenshot_20220419-233343~2.png](https://user-images.githubusercontent.com/12276250/164105775-651d2aee-9ca1-43e0-a0b6-7ea25ad996a2.png)

**Comment by dessalines** [comment]
Where you pointed if anything, should show your user avater, not the site icon.

**Comment by Tealk** [comment]
I don't know how others work, but I use the same avatar everywhere as much as possible, so how do I know which server I'm switching to?

**Comment by Tealk** [comment]
> I can add the instance name there too, something like `{instance.tld}/{username}`. 

That would be extremely helpful
