### ISSUE TITLE
"View Sidebar" button on federated communities crashes the app

### ISSUE THREAD

**Issue by whouishere** [dessalines/jerboa#170]

**Comment by dessalines** [comment]
I can't replicate, just tried a federated community. Which community is giving you issues?

**Comment by whouishere** [comment]
I tested with !brasil@lemmy.pt and !internetexplorers@sopuli.xyz.
It might be my device or something. Will try to compile the app from source and replicate tomorrow

**Comment by whouishere** [comment]
The weird thing is that I tested with [!tecnologia@lemmy.pt](https://lemmy.pt/c/tecnologia) and it works out just fine, while the other mentioned communities still crash.
And neither of the communities have any special formatted text on the sidebar, which was my first suspicion.

**Comment by dessalines** [comment]
I've also verified that crash, I'll have to investigate. Guessing its a missing field.

**Comment by dessalines** [comment]
Can't seem to verify it with those communities above now. I'm guessing it was an old version issue. I can re-open if its still an issue.

**Comment by dessalines** [comment]
Nevermind, found an issue and fixed it.
