### ISSUE TITLE
Accessibility: many things read as "todo" with talkback

### ISSUE THREAD

**Issue by davidbtc2009** [dessalines/jerboa#175]
V0.0.15
Android 11

The menu items read as 
- "todo subscribed"
- "todo local"
- "todo all"
- "todo saved"
- "todo profile"
- todo inbox"

The tabs along the bottom read as "todo"
The upvote, downvote, star, and 3 dot menu read as "todo"

Edit: the buttons on the top right such as sort order and the three dot menu also do this

**Comment by dessalines** [comment]
Thanks, might be a while before I can get to this.

**Comment by davidbtc2009** [comment]
@dessalines i just wanted to let you know about them.

**Comment by shortwavesurfer2009** [comment]
This is still an issue as of v0.0.31

**Comment by 0hCome0n** [comment]
Given that r/blind is organizing the Reddit blackout, it may be a very good idea to fix this ASAP so that we can promote Jeroba as blind-friendly.

**Comment by dessalines** [comment]
Before that, jerboa should add internationalization #1 too. I'm very busy at the moment, but if someone would be willing to work on both, that would be very much appreciated.

**Comment by pipe01** [comment]
I'm working on this, shouldn't conflict with #1.
