### ISSUE TITLE
[FR] Add a way to change the base instance when anonymous

### ISSUE THREAD

**Issue by momobobe** [dessalines/jerboa#176]
It seems there is no way to replace the default base instance lemmy.ml for anonymous / non-logged profile unless log into another instance. Please make it changeable as an separate option instead of bundled with account login. In other words, I just wanna simply view posts in other instances without login.

**Comment by dessalines** [comment]
That would require a whole other page just like the login one. Rather than do this, I'd rather just not allow anonymous browsing whatsoever.

**Comment by dessalines** [comment]
Going to stop anonymous browsing, since google play store doesn't allow it anyway.
