### ISSUE TITLE
Let the app manage image previews

### ISSUE THREAD

**Issue by suoko** [dessalines/jerboa#225]
At the moment, when opening an image in a post, the browser is used to preview it.
Is it possibile to use the app itself? Maybe with the webview

**Comment by dessalines** [comment]
Maybe way down the road, because it would require bundling a library, doing picture saves, file permissions, etc.

**Comment by suoko** [comment]
What about an embedded webview? Easy peasy

**Comment by twizmwazin** [comment]
@jasonnab What you're describing is a seperate issue

**Comment by pipe01** [comment]
This can be closed
