### ISSUE TITLE
Create lemmy-kotlin-client

### ISSUE THREAD

**Issue by dessalines** [dessalines/jerboa#233]
Extract all the API definitions into a kotlin client.

**Comment by MV-GH** [comment]
With the upcoming backwards compatible API, for this issue would you want me to make it a seperate project that Jerboa would depend on?

**Comment by dessalines** [comment]
Sure. I tried and failed at creating a kotlin-specific library and put it on sonatype. Theirs and gradle's tutorials for creating and uploading libraries aren't the best.

**Comment by MV-GH** [comment]
#1284
