### ISSUE TITLE
Don't allow viewing anything without a login.

### ISSUE THREAD

**Issue by dessalines** [dessalines/jerboa#240]

**Comment by twizmwazin** [comment]
I don't think I would agree with this. Instead I think Jerboa should allow the user to choose an instance to view when not logged in, and generally support the no-account use case.

**Comment by dessalines** [comment]
One reason for this, is that google play could remove us at any moment. They dinged me for not having no-account reporting (which doesn't exist in lemmy), or things they don't like seeing on the front page of lemmy.ml.

Things have settled for now, but I used to pull my hair out on every update. I see why pretty much every federated app doesn't have a "default instance" view, they make you log in first.

**Comment by twizmwazin** [comment]
I see, that's unfortunate. This is a stretch, but maybe at some point in the future we can have a sanitized "google play friendly" build option.

**Comment by dessalines** [comment]
True. 

I def agree its a nice experience to just load up the app and see content, but I don't think we should spend too much dev effort on non-logged-in support. Infinity for reddit also has lots of warning toasts all over the place when you try to do anything without an account.

**Comment by dessalines** [comment]
Stale issue.
