### ISSUE TITLE
Keyboard overlaps text box in Android 

### ISSUE THREAD

**Issue by jcklpe** [dessalines/jerboa#243]
Thank you for building this client! Looks great so far. Just one minor issue:

![Screenshot_20221103-161142](https://user-images.githubusercontent.com/9451726/199835458-180dc479-aef6-4bc0-8a4d-705027f1a36b.png)

**Comment by jcklpe** [comment]
I'm using the Microsoft SwiftKey keyboard.

**Comment by dessalines** [comment]
I don't understand, you can still scroll down to the bottom right? I'm not getting that overlap.

**Comment by jcklpe** [comment]
I can scroll but most apps autoscroll when typing into an input like this.

**Comment by dessalines** [comment]
I spose I could add a "scroll to bottom" type thing on the reply screen, because this issue will only arise when replying to long comments.

**Comment by jcklpe** [comment]
That wouldn't be bad but other apps just do it automatically as you type.
