### ISSUE TITLE
Troubles with comments

### ISSUE THREAD

**Issue by InvalidNickname** [dessalines/jerboa#293]
A couple of days ago comments under posts stopped loading, example on the screenshot. You can see that the post has non zero comments, but none is shown.

![Screenshot_20230203-013700_Jerboa for Lemmy](https://user-images.githubusercontent.com/34033166/216465536-04b0cbe4-2471-4b3e-a901-0b1f00c470bf.jpg)

Tried to clean cache and reinstall, nothing changed. I have app backup turned off, so definitely not a cache thing. Also tried with different Wi-Fi and mobile networks.

Maybe it has something to do with the new version of lemmy's api?

**Comment by dessalines** [comment]
Dupe of #290
