### ISSUE TITLE
Language not allowed

### ISSUE THREAD

**Issue by suoko** [dessalines/jerboa#322]
When posting to lemmy.ml I always got a 'language not allowed' error.
Since last update

**Comment by suoko** [comment]
![Uploading IMG_20230210_234844.jpg…]()

**Comment by dessalines** [comment]
Did you change your user languages by chance? Currently jerboa isn't sending that language field, so it *might* be selecting one of your user languages, and someone might have set a post language that isn't allowed by your user languages.

**Comment by suoko** [comment]
> Did you change your user languages by chance? Currently jerboa isn't sending that language field, so it _might_ be selecting one of your user languages, and someone might have set a post language that isn't allowed by your user languages.

I didn't change anything.
Consider that I only have one user account which is in a non-English language, and I use that account to comment on lemmy.ml
Something changed on jerboa or on lemmy.ml
How can I solve it? Other users have the same issue

**Comment by suoko** [comment]
@dessalines 
Check this: https://feddit.it/post/147427
I could create that post but now I can't comment it

**Comment by suoko** [comment]
@dessalines actually I can't reply via web either, same error, so it's not jerboa issue.
Forget it, must be some lemmy misconfiguration

**Comment by suoko** [comment]
@dessalines actually I can't reply via web either, same error, so it's not jerboa issue.
Forget it, must be some lemmy misconfiguration

![Screenshot_2023-02-11-08-12-04-547_org mozilla firefox](https://user-images.githubusercontent.com/3659980/218245872-e3332d3f-f9cb-4931-b07f-1a96a9fdc0fe.jpg)

**Comment by dessalines** [comment]
Gotcha, ya the lemmy back-end is having some issues with Languages not being properly allowed under some circumstances. It won't let me transfer this issue so you might have to re-open it in the lemmy repo.
