### ISSUE TITLE
Publish latest release to F-Droid

### ISSUE THREAD

**Issue by Beagle** [dessalines/jerboa#340]
The current version of Jerboa available on F-Droid is 22. The bug fixes in the latest releases are critical for Jerboa to be more useful. Please release an updated version to F-Droid.

**Comment by dessalines** [comment]
It should be in the next f-droid build (usually every few days), and its also on izzyondroid.

https://gitlab.com/fdroid/fdroiddata/-/commit/2258d03ebeb552193058beeec40d059d43e62728

**Comment by Coool** [comment]
Latest current version on Google Play Store - [0.0.81-gplay](https://play.google.com/store/apps/details?id=com.jerboa), but still no 0.0.81 on [F-Droid](https://f-droid.org/packages/com.jerboa)

**Comment by dessalines** [comment]
gplay build numbers are one ahead. I'll probably try to fix this in the next release.
