### ISSUE TITLE
Redirect to login page when required

### ISSUE THREAD

**Issue by fxdave** [dessalines/jerboa#346]
The user icon requires you to be logged in.

**Comment by dessalines** [comment]
What user icon? You need to go to the top left, and click add account.

**Comment by fxdave** [comment]
Indeed. I was confused by the UI. Thanks!

**Comment by dessalines** [comment]
Sorry about that, my bad! I'll re-open, since any button clicks that result in the toast `please log in`, should direct you to the login page instead.

**Comment by dbbvitor** [comment]
The user icon (person icon on the bottom right) prompts me to "Login first".
I cant log in.

**Comment by fxdave** [comment]
@dbbvitor The UI is confusing, you can find the solution at the top of the issue.
