### ISSUE TITLE
Cross-post, post and comment from different instance incorrectly links to home domain.

### ISSUE THREAD

**Issue by ShinyLuxray** [dessalines/jerboa#361]
Checked earlier issues, similar to #186, #228.

Version: Discovered on 0.0.27, persists on 0.0.30

Description: Clicking/opening a link within the Jerboa app leads to the page on the logged in user's instance instead of the instance contained in the link.

Steps to reproduce:
1. Navigate to any post containing a link to a Lemmy comment, post or cross-post whose domain does NOT match the instance of the logged in user.
2. Click said link and open in Jerboa app.
3. (A) Receive "Couldn't Find Post/Comment" error or (B) App navigates to different post/comment than desired.

Example A:
- User logs in on lemmy.ca within Jerboa and navigates to this post: https://lemmy.ca/post/529783
- User clicks on https://lemmy.ml/post/1073275 written in the post body, selects to open in app
- App navigates to https://lemmy.ca/post/1073275, receives "Couldn't find post"

Example B:
- User logs in on lemmy.ca within Jerboa and navigates to this post: https://lemmy.ca/post/529882, "Why privacy is important" in lemmy.ca's Bestofthefediverse community.
- User clicks on the post's main link to a comment: https://lemmy.ml/comment/66425 "Why is privacy important?" on lemmy.ca's Privacy community, opens in Jerboa.
- User is instead led to an unrelated comment:  https://lemmy.ca/comment/66425 "Megathread on /r/SubredditDrama about /r/antiwork" on lemmy.ml's antiwork community.

Notes: 
Opening in web browser works OK. I believe the issue is that lemmy.ml (and any other site) ends up replaced with lemmy.ca or the user's home server (e.g. beehaw.org, if someone can double check if that is the case).

**Comment by dessalines** [comment]
I'm not sure how I'd tackle this one, and I'd need some help with it.

Jerboa is not a web browser that can go to any url, the navlinkparams only work with a specific set of instances. Probably all fediverse apps are dealing with this issue, that urls only load in web browsers.

I think the way I'm going to handle it, is to remove all web / URL loading as it exists, and integrate the search function to load activitypub urls as lemmy-ui currently does.

**Comment by twizmwazin** [comment]
Closing in favor of #186
