### ISSUE TITLE
Commonly receiving various connectivity errors

### ISSUE THREAD

**Issue by 0hCome0n** [dessalines/jerboa#364]
Phone: Pixel 7
OS: UpsideDownCake (UPB2.230407.014)

Receiving many variations on connectivity errors E.G.

"Connection closed"

"Value <html> of type java.lang cannot be conver..."

"Stream was reset: REFUSED_STREAM"

Did not find "refused" in an issue search, so apologies if this is a duplicate.

**Comment by 0hCome0n** [comment]
Fat fingers closed the issue

**Comment by dessalines** [comment]
I'm not sure what I could do about that, as these are indicative of server connection issues.

**Comment by 0hCome0n** [comment]
As I learn more, I agree. (As if disagreeing were somehow an option once you understand what the messages mean.)

Maybe just adding "server error" to the message would make it more clear it's a server error to people who don't know better. I'm definitely the kind of person who doesn't know better, so it could cut down on well-meaning but misinformed issue complaints.

Feel free to close this issue, I think if I closed it it would prevent you from commenting, right?
