### ISSUE TITLE
Flicking between tabs (at least what I think) is causing the app to think the entire screen is the same as a post, and therefore flashbangs/creates a rather white light upon tab switching only.

### ISSUE THREAD

**Issue by ColdyCold** [dessalines/jerboa#371]
https://youtube.com/shorts/mNxzDxvASrI?feature=share

(I don't know why but it's not letting me posta video here, but it's essentially doing this.)

**Comment by dessalines** [comment]
Not sure what could be causing that. I don't do any special / custom transitions between screens.

**Comment by twizmwazin** [comment]
Fixed in #428
