### ISSUE TITLE
Black theme for OLED displays, and some more theme color options?

### ISSUE THREAD

**Issue by a1studmuffin** [dessalines/jerboa#376]
I saw in a previous commit that there was once a Black theme alongside Light and Dark. This would be great to reinstate for OLED displays (and just for aesthetic preference). I imagine it would effectively look the same as Dark theme but with true black (#000000) as the background.

On a similar note it would be nice to have a greyscale theme color option in addition to Green and Pink.

If this isn't high on the priority list, I'm happy to have a go at putting together a PR, just let me know. Thanks!

**Comment by dessalines** [comment]
Feel free to add as many themes as you like! jetpack compose handles material v4 themes really well, so its nbd to add these.
