### ISSUE TITLE
Remove BANNED_INSTANCES, or do a better implementation of it.

### ISSUE THREAD

**Issue by CaptainBasculin** [dessalines/jerboa#379]
While I was browsing the source code for a completely different issue I've been having, I noticed this in the Login.kt file. 

`val BANNED_INSTANCES = listOf("wolfballs.com")`

`val isValid =
        instance.isNotEmpty() && username.isNotEmpty() && password.isNotEmpty() &&
            !BANNED_INSTANCES.contains(instance)`

Putting the fact that this instance has been shut down months ago aside, completely disabling logins to an instance and not even notifying the user about its cause is a wrong approach to take. It should be up to the user in the end to decide whether they should browse the instance they want. An opt-in toggle to view potentially unsafe instances, removing this completely and allowing anyone to connect to the instance they want, or at the very least putting a message like "This instance is not supported" would be all better approaches.

**Comment by dessalines** [comment]
This was just a kludge... basically these anti-vaxx / anti-trans trolls were bragging that someone had built an app for their hate site. It could be implemented better, but I do reserve the right to . In the end, this is an open source project, so they could always fork it, remove that, and maintain it.
