### ISSUE TITLE
Manage dependencies using Gradle Version Catalogs

### ISSUE THREAD

**Issue by oscarnylander** [dessalines/jerboa#381]
As a strategy for managing dependencies, Gradle Version Catalogs is the most scalable approach for managing dependencies. In particular, it makes defining common versions a breeze.

Read more: https://docs.gradle.org/current/userguide/platforms.html#sub:conventional-dependencies-toml

**Comment by dessalines** [comment]
I'd be open to that, as long as android studio can handle upgrades of dependencies well with it. 

Currently android studio shows warnings on unupdated dependencies in your build.gradle

**Comment by MV-GH** [comment]
What are the advantages of using version catalogs over what we currently do?

**Comment by oscarnylander** [comment]
>I'd be open to that, as long as android studio can handle upgrades of dependencies well with it.

The best experience I've had is using the `renovate`-bot to automatically get updates, and it is compatible with version catalogs.

>What are the advantages of using version catalogs over what we currently do?

1. Codegen for common versions, that is
2. Sharable across modules

The benefits of this are especially evident when having more than one module in the project, which to be fair is not the case today.

**Comment by dessalines** [comment]
Stale issue, can re-open if someone wants to work on it.
