### ISSUE TITLE
Posts are not immediately marked as viewed after viewing them in Home-Screen

### ISSUE THREAD

**Issue by oscarnylander** [dessalines/jerboa#403]
Expected behaviour is that posts get marked as viewed immediately after having been viewed.

**Comment by dessalines** [comment]
This should come after I have time to work on, and merge, the `autogen_types` branch, which has the `MarkPostAsRead` data class this requires.

**Comment by oscarnylander** [comment]
Sounds great. I won't pick this up, in that case.

**Comment by dessalines** [comment]
Definitely not a good first issue. But there are plenty of other ones you could take.

**Comment by Schoolkid1** [comment]
Thanks for your quick reply. Do you perhaps have any recommendations? I like a good challenge to work on, ultimately I want to learn and upgrade my knowledge.

**Comment by dessalines** [comment]
#425 is a good smaller one to take. 

When I get the time, I'll go through and organize these issues a bit better.

**Comment by MV-GH** [comment]
Hmm confirmed, weird did not touch anything regarding that

**Comment by MV-GH** [comment]
[app-release.zip](https://github.com/dessalines/jerboa/files/12423204/app-release.zip) has the fix
