### ISSUE TITLE
Value Timeout of type java.lang.String

### ISSUE THREAD

**Issue by Stugist** [dessalines/jerboa#410]
Cannot be converted.

I'm on the Google store version. Happens seemingly at random, at least once an hour.

**Comment by AdamDoesThingsSometimes** [comment]
I'm getting this too, mostly when looking at specific "subs" like AskLemmy. Sometimes it's accompanied by <html> cannot be converted. :)

**Comment by 0hCome0n** [comment]
It's a server issue, not an app issue. The instance servers are overloaded right now and while they work to scale up you'll see different errors related to connectivity failures. That's one of them, as far as I understand.

**Comment by AdamDoesThingsSometimes** [comment]
> It's a server issue, not an app issue. The instance servers are overloaded right now and while they work to scale up you'll see different errors related to connectivity failures. That's one of them, as far as I understand.

Thank you so much for letting us know :) I guess it's a pain of being successful - hopefully it'll all pan out nicely. :)

**Comment by 0hCome0n** [comment]
Oh no, do not take me as a voice of authority. This is just what I've figured out from my experience of the errors I've been receiving and a little idle googling.

That string error shows up as one of the many variations that happen when the server goes kaputz. My googling tells me it's related to the connection timing out and a variable type mismatch that occurs as a result. The code is expecting a string and for some reason when the connection times out it gets something different and isn't happy about it.

There's more elegant ways to handle the error, sure, but at this point I wouldn't consider it a priority for the app. Properly handling the timeout isn't going to bring the server back online.

Thanks for your hard work! I'd help if I could but I'm too disabled to code, literally.

**Comment by dessalines** [comment]
Yep, this is a server issue, not related to the app.
