### ISSUE TITLE
Add a favourite option to communities

### ISSUE THREAD

**Issue by Anna-log7** [dessalines/jerboa#416]
A feature I really like in Reddit is fun is the ability to favourite a community, which places it at the top of the subscription list in the sidebar

- Add a favourite button or a star icon next to the Subscribe button in a community
- Add favourited communities either to the top of the subscribed list, or in a separate favourited section just before the subscriptions list

**Comment by dessalines** [comment]
In lemmy just like reddit, a favorite is equivalent to a subscribe. Use the community page or the sidebar to quickly find communities.

**Comment by twizmwazin** [comment]
@dessalines This is not the same as a subscribe, it is a client feature that allows "favorite"  communities to show at the top of the community list in the app. The implementation would likely be entirely local to the client.  It is useful when a user subscribes to many communities but has a few that they want quick access to without having to scroll through the subscribed list.

**Comment by smuuf** [comment]
BaconReader for Reddit had this and it was a great feature _(which Reddit did not have to support/know about - it was just a client-side thing)_. You had the ability to "favorite" a subreddit, which saved that subreddit into the list of your subreddits for easy access - ***without subscribing to it***.

Which essentially meant you had quick access to your favorite subreddits without their posts being shown in your main "subscribed feed", which is great for lurking and "nsfw safety."

IMHO this would be a great feature for Jerboa to have.

**Comment by ResurFace382500000** [comment]
https://github.com/LemmyNet/jerboa/issues/416
https://github.com/LemmyNet/jerboa/issues/1751
https://github.com/LemmyNet/jerboa/issues/1927
