### ISSUE TITLE
Implement Cards 2.0 from Boost?

### ISSUE THREAD

**Issue by TrollBlox** [dessalines/jerboa#423]
I use Boost and I use Cards 2.0 and would love to see it be ported to Jerboa!

**Comment by dessalines** [comment]
For sure, it'd be nice to have. The relevant components are `PostListingCard` and `PostListingList`, in `PostListing.kt`

If you'd like to submit a PR to add a view, go right ahead.

**Comment by TrollBlox** [comment]
I'd love to if I had the time! Also, I think I got the name wrong of the post style. I meant this one:![Screenshot_20230606-134957.png](https://github.com/dessalines/jerboa/assets/52006707/d40e73e9-f9ba-4e2a-a74a-f8f3f639685f)

**Comment by dessalines** [comment]
This is done
