### ISSUE TITLE
Issue with long passwords

### ISSUE THREAD

**Issue by sir-wombat** [dessalines/jerboa#425]
Instance tested with: feddit.de

Expected behavior: Long passwords should work. If a password does not work, due to whichever limitation, the error message should state the specific limitation and/or the requirements for an acceptable password.

Issue: I kept getting "login failed" messages, until I shortened my password. 64 chars of letters, digits and special chars didnt work; then I changed to 64chars of letters and digits only, which also didn't work. Then I changed to 24 chars of letters and digits and it worked.

Additional info: I am using KeepassDX, so I'm positive that I didn't "misstype".

**Comment by dessalines** [comment]
The lemmy back end, as well as lemmy-ui has a password limit length of 60, and lemmy-ui smartly truncates that password field when you paste or autofill, to make sure that you can log in. 

We essentially need to add that limit / truncation to jerboa as well.

**Comment by Tealk** [comment]
No this is not the right way, remove the maximum length of the password.

Besides, the user does not even know his correct password if it is automatically shortened!

**Comment by dessalines** [comment]
That back-end doesn't truncate, it correctly throws an error for overly-long passwords. The front end / lemmy-ui input, has a `maxLength`, which does the truncation. Whether to replicate that behavior here, is a question.

**Comment by twizmwazin** [comment]
Fixed in #462
