### ISSUE TITLE
Maintain Settings on Update

### ISSUE THREAD

**Issue by dukethorion** [dessalines/jerboa#427]
Updated the latest version, all theme and sort settings were reset to default.  Settings should persist between updates.

**Comment by dessalines** [comment]
That shouldn't be the case... we didn't do any destructive migrations whatsoever. Are you sure you clicked save after changing your settings? Which settings got reset?

**Comment by dukethorion** [comment]
I imagine that if I didn't click Save, it would not persist upon closing/reopening the app?  

The theme was reset, and the Default feed (Subsc/Local/All) and the default sort (Hot/New/Etc).

**Comment by dessalines** [comment]
I also just upgraded on one of my devices, and didn't get this error. The feed and default sort is a separate issue not related to DB migrations, which are working.
