### ISSUE TITLE
Handle connection issues gracefully

### ISSUE THREAD

**Issue by AntmanLFEz** [dessalines/jerboa#429]
Currently if there is a gateway timeout on app startup then the application loads the user as anonymous even though they have already signed in.

If the connection issues are resolved and the application is restarted, the user will be logged in as normal.

Currently with no indication a user will try and unnecessarily log in again (unsuccessfully)

The app should still load the username and indicate "Connection Issues". There should then be either a retry button or automatic retry.

**Comment by MV-GH** [comment]
Solved with #1099
