### ISSUE TITLE
Allow swiping back on comments to return to post view

### ISSUE THREAD

**Issue by jordan1776** [dessalines/jerboa#431]
Many 3rd party reddit apps (Sync, Relay, etc)  have the feature where you can swipe back on comments back to the main page. It would be a nice QoL improvement if Jerboa did the same.

**Comment by dessalines** [comment]
This already exists, both on the top bar, and the navigation history stack.

**Comment by twizmwazin** [comment]
There is no swipe gesture currently implemented as far as I can tell for the comments view. Ideally the user should be able to swipe across anywhere in the comments view to be taken to the preview view, with a pointer-tracking slide right animation.

**Comment by dessalines** [comment]
Ohhh I see what you're saying, not the android back button, but the entire view.

**Comment by jordan1776** [comment]
> There is no swipe gesture currently implemented as far as I can tell for the comments view. Ideally the user should be able to swipe across anywhere in the comments view to be taken to the preview view, with a pointer-tracking slide right animation.

Thanks for clarifying twizmwazin, this is exactly what I mean
