### ISSUE TITLE
Do not require login when clicking on 3 dot menu

### ISSUE THREAD

**Issue by tuxiqae** [dessalines/jerboa#435]
When clicking on 3 dot menu of a post/comment(maybe others as well) users are introduced with the `loginFirstToast` toast which prevents them from copying links or other features which thos menu provides.
I tried looking for the exact location where this is handled in the code but I could not find it.
I would like to disable this check when clicking read-only global option (options which should not be hiddeb from anyone)
I would gladly do it myself if I could find it, let me know if you want me to take xare of it.

Running Jerboa v0.0.31

**Comment by twizmwazin** [comment]
Here's where that check occurs: https://github.com/dessalines/jerboa/blob/main/app/src/main/java/com/jerboa/ui/components/common/AppBars.kt#LL296C9-L296C9


We probably want to add a "requiresAccount" field or something.

**Comment by dessalines** [comment]
Rather than the "please login" toasts that I had been doing, I think a better solution is to *also* navigate to the login page.

**Comment by tuxiqae** [comment]
> In addition to the "please login" toasts that I had been doing, I think we should also navigate to the login page.

I do not agree, I would hate being redirected to the login page every time I accidentally clicked on the wrong button.

**Comment by tuxiqae** [comment]
https://github.com/dessalines/jerboa/pull/450
@dessalines @twizmwazin

**Comment by tuxiqae** [comment]
Guess we can close that?
Just bear in mind that it was not tested as I do not have an Android development setup ready to use.

**Comment by dessalines** [comment]
Wish you would've told me that. I'm very busy so I haven't had time to manually test every one of these.

**Comment by tuxiqae** [comment]
@dessalines  Don't you prefer to leave it open so you won't forget to manually test it?

**Comment by camporter** [comment]
Tested on v0.0.33 and this issue isn't present.

**Comment by tuxiqae** [comment]
I did too and it's actually kinda worse, now the new menu allows a couple of actions which require being signed-in (reporting, blocking), we need to take care of that

**Comment by twizmwazin** [comment]
Original issue is fixed, we can make a new issue for the resulting issue.
