### ISSUE TITLE
Login form is not treated as a login form by autofill services

### ISSUE THREAD

**Issue by oscarnylander** [dessalines/jerboa#439]
Expected behaviour is that the login form is treated as such by autofill services like password managers.

**Comment by dessalines** [comment]
Def agree, this would be nice to have. 

Does anyone have any links that show how to get jetpack-compose inputs working with form fillers?

**Comment by twizmwazin** [comment]
This blog seems more useful than the first official docs that come up in search: https://bryanherbst.com/2021/04/13/compose-autofill/

**Comment by Terrance** [comment]
Looks like this was fixed and released in 0.0.33, but I've just downloaded 0.0.34 from F-Droid and the login form still isn't presenting auto-fill as an option?

[<img src="https://github.com/dessalines/jerboa/assets/4025899/aa2e3840-40c7-4e23-abb0-c091db471ae5" width="200">](https://github.com/dessalines/jerboa/assets/4025899/aa2e3840-40c7-4e23-abb0-c091db471ae5)

Running on a OnePlus Nord CE, Android 13.
