### ISSUE TITLE
Scrolling seems to sutter/lag on latest version (0.0.32)

### ISSUE THREAD

**Issue by Footsiefat** [dessalines/jerboa#445]
This suttering/lag/jerkyness shows itself on both posts and comments, this is running on a Samsung a32

I checked logcat but unfortunately I am seeing no errors about jerboa, I do see an related scroll warning come up which I will link below.

![image](https://github.com/dessalines/jerboa/assets/12180913/ec3dbb9d-bfa8-4e9a-a260-6ee039ba15ad)

I am also willing to put a $50 usd (monero) bug bounty on this for whoever can fix this issue.

**Comment by Footsiefat** [comment]
Upping the bug bounty to $100 usd

**Comment by Footsiefat** [comment]
Potential fix found? https://stackoverflow.com/a/71943968 @dessalines

**Comment by Footsiefat** [comment]
Is the UI meant to be recomposed when scrolling?
![image](https://github.com/dessalines/jerboa/assets/12180913/25cd2da4-4122-4e55-9cb1-2b971b7d892f)

**Comment by dessalines** [comment]
I believe so yes, lazycolumn loads new content dynamically.

**Comment by Footsiefat** [comment]
It should also be noted that this is being triggered when scrolling back over existing comments that have been previously loaded

**Comment by dessalines** [comment]
@oscarnylander is it possible that downgrading that android gradle plugin `AGP` made performance worse?

Granted, scroll-stuttering was still an issue before this.

**Comment by oscarnylander** [comment]
I'd consider it to be pretty unlikely. I guess profiling a build with the alpha-variant versus a build without would reveal whether it's the case, though.

**Comment by a1studmuffin** [comment]
Dumb question as I'm not super familiar with Jetpack Compose/Android app dev, but should there be a Debug and Release build profile of some kind, the latter turning on all optimisations and removing debug symbols/aids etc?

**Comment by oscarnylander** [comment]
You are correct, debug builds will affect performance a lot as far as Compose is concerned.

I'd assume that the final build that makes it out to release channels already is built using a release configuration, though.

**Comment by kabe-inc** [comment]
Going from the stable 0.0.33 to the latest 0.0.34 build introduced a ton of lag and jerky scrolling too.

**Comment by kabe-inc** [comment]
Going from the stable 0.0.33 to the latest 0.0.34 build introduced a ton of lag and jerky scrolling too.

**Comment by a1studmuffin** [comment]
I think someone needs to do some profiling in Android Studio while scrolling in Jerboa, and spend some time going through the results to see if there's any way we can reduce the amount of composition/layout going on. 

There's some good docs on the subject here:

https://developer.android.com/jetpack/compose/performance
https://developer.android.com/jetpack/compose/phases

Unfortunately I don't think there's going to be a quick fix - it'll likely be death by a thousand cuts causing the lag, so will probably require lots of little optimisations to existing code to make it more efficient. Hopefully there's a little bit of low hanging fruit though.

**Comment by sockenklaus** [comment]
I don't know if this is worth anything but since this is such a diffuse issue I'll try to collect reports of users with their Device and Android version. Maybe it shows a pattern

| Device | Android version | Jerboa version | Comment |
|------------|---------------------------|--------------------------|------------------|
| Cell | Cell | Cell |
| Cell | Cell | Cell |

**Comment by Cdsi37** [comment]
Scrolling is laggy (but usable) on 0.0.34 on Android 8.1 on Xiaomi Redmi 4 Prime

**Comment by optimusam** [comment]
Not sure how to help but wanted to add that it lags a lot on s22+ snapdragon variant.

**Comment by bblacher** [comment]
Any updates on this? This is my main problem with Jerboa, it just makes it uncomfortable to use the app.

**Comment by bblacher** [comment]
Also happens on a Pixel 8 Pro on CalyxOS. This makes the app unusable for me.

**Comment by dessalines** [comment]
What version?

**Comment by bblacher** [comment]
Happens on 0.0.55, happened to me ever since I first tried this app in July. I checked if the bug was gone every now and then but nothing fixed it. This makes jerboa unusable for me.

**Comment by dessalines** [comment]
I'm using jerboa on multiple android devices, with different android versions. This seems like it would affect every single jetpack-compose app that uses LazyLists for specific android versions / OSs.

Could you post a video?

**Comment by bblacher** [comment]
Here you go. This only happens to me with jerboa and it happens on both my phones.

https://github.com/dessalines/jerboa/assets/42916911/fe4933d7-f6dc-403b-b2ad-d9aef4f18b3f

**Comment by dessalines** [comment]
Stale issue. Can re-open if we find specific cases, but we're mostly limited by jetpack compose's lazylist.
