### ISSUE TITLE
Photo links do not open in Jerboa app properly

### ISSUE THREAD

**Issue by jasonnab** [dessalines/jerboa#448]
Jerboa Version: Version 0.0.32 (F-Droid/IzzyOnDroid)
Android Version: Android 11 (LineageOS 18.1 ocean)
Android Device: Motorola G7 Power
Lemmy instance: Any

----

When clicking on an image inside the app, it prompts me to either open with Jerboa, or with my web browser.

![jerboa1 png](https://github.com/dessalines/jerboa/assets/99688442/3afc849d-d650-4c4c-9dbf-1c7bff60b4e3)![jerboa2 png](https://github.com/dessalines/jerboa/assets/99688442/c0abf108-dd6a-4ccf-8ec7-e1f051e1d4a5)

If I select Jerboa, it reopens the app from a normal app start, losing my browsing place, acting as if I had just opened the app.
If I select my web browser, it opens the direct image URL.

Relevant logcat output when selecting Jerboa as the **Open With** option:

```
ResolverListAdapter
 Add DisplayResolveInfo component: COmponentInfo{com.jerboa/com.jerboa.MainActivity}, intent component: ComponentInfo{com.jerboa/com.jerboa.MainActivity}

ActivityTaskManager
 START u0 {act=android.intent.action.VIEW dat=https://feddit.de/... flg=0x3000000 cmp=com.jerboa/.MainActivity}
```

The shortened ```dat``` portion is the image URL itself.

Thank you!

**Comment by dessalines** [comment]
In app pictures are now added.
