### ISSUE TITLE
Rewrite links in /c/community@server or /u/user@server in appropriate ways

### ISSUE THREAD

**Issue by Barbariandude** [dessalines/jerboa#454]
In lemmy-ui, a link formatted in the ways described in the title are automatically rewritten to the appropriate URL by prepending the URL of the instance the account is from. This functionality is missing from Jerboa. Not the most urgent thing in the world as users can use the website instead, but definitely something that should be looked at at some point.

**Comment by dessalines** [comment]
Is this referring to the copy permalink button? Or content that's in the markdown fields?

If its the permalink, we should probably use the original links, and if its the latter, jerboa doesn't even have a smart auto-filler for users and communities yet like lemmy-ui does.

And when it does, we'll need to match lemmy-ui, and add both links (a local and a fedi-link) : https://github.com/LemmyNet/lemmy-ui/issues/1048

**Comment by Barbariandude** [comment]
If I format a link like [this]\(/c/lemmy@lemmy.ml) in the web UI, then a user sees the link as https://my.server/c/lemmy@lemmy.ml. This is very useful funcionality once people get used to it. It would be nice if the functionality matched in Jerboa.

**Comment by beatgammit** [comment]
This has been merged and I believe resolved.
