### ISSUE TITLE
Getting asked to log in, after logging in.

### ISSUE THREAD

**Issue by vagkalosynakis** [dessalines/jerboa#455]
** Jerboa Version **
0.0.32

**Describe the bug**
After successfully logging in through my instance(Lemmy.ml) I can see that I am logged in, because both my avatar and my username is showing at the top but I cannot do any action because it asks me to *Login first*.

Clicking on my account I have 2 options:

1. Add Account
2. Switch to `lemmy.ml/[my username]`

Selecting `Switch to [my username]` completely logs me out.

I have no way to interact with the application and/or communities on my phone.

**Comment by dessalines** [comment]
I can't replicate this, but I *have found* that sometimes connection issues, or theme mode changes (which I think trigger a lot of app reloads, can sometimes cause it.

**Comment by amminadabz** [comment]
I am also having this issue, 0.0.32 on Android 12 on OnePlus 9 Pro, using sh.itjust.works.

**Comment by ogre-about-town** [comment]
I also have this issue.  

Using Jerboa 0.0.34
Moto G 5g (2022 version)
Android 13, Build 13.01.000

This happens on multiple instances.  I can mitigate the problem by clearing app cache.

**Comment by SnakiSnaki** [comment]
I also have this issue.
Also, if I open the top-left menu > expand my profile > click "Switch to [username]@lemmy.world" it actually logs me out. Now the top-left menu shows "Anonymous" with the option to "Add Account" or "Sign Out".

Using Jerboa 0.0.39.
OnePlus 8T
Android 13 build KB2003_13.1.0.580(EX01)

**Comment by MV-GH** [comment]
Should be resolved by #1099
