### ISSUE TITLE
Implement a debug options menu

### ISSUE THREAD

**Issue by twizmwazin** [dessalines/jerboa#456]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **
Jerboa should have a debug settings panel that contains developer-specific options. The initial motivating factor is to allow buttons to start and stop tracing for performance profiling and debugging.

**Comment by dessalines** [comment]
Would need to know what these specific things would be.
