### ISSUE TITLE
Allow responding to your own comment

### ISSUE THREAD

**Issue by twizmwazin** [dessalines/jerboa#458]
** Jerboa Version **
Type the version from the settings here.
0.0.32

**Describe the bug**
Commenting is disabled on your own post. Unless this is enforced on the server I don't think it should be disabled on the client.

**To Reproduce**
View any post you have made and attempt to respond with a comment.

**Comment by Footsiefat** [comment]
Luckily it shouldn't be too hard, it just requires commenting out lines 571 to 577 in [CommentNode.kt](https://github.com/dessalines/jerboa/blob/b1b83bcdde6626cefced270d6b05f0a348033be8/app/src/main/java/com/jerboa/ui/components/comment/CommentNode.kt)
