### ISSUE TITLE
Add slrpnk.net to DEFAULT_LEMMY_INSTANCES

### ISSUE THREAD

**Issue by hohenheim1618** [dessalines/jerboa#463]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

The available list of instances is somewhat limited. For reference, this list is located at [com.jerboa (lines 73-82)](https://github.com/dessalines/jerboa/blob/main/app/src/main/java/com/jerboa/Utils.kt):

```
val DEFAULT_LEMMY_INSTANCES = listOf(
    "lemmy.ml",
    "lemmygrad.ml",
    "mujico.org",
    "feddit.de",
    "szmer.info",
    "beehaw.org",
    "feddit.it",
    "sopuli.xyz",
)
```

My specific request is to add [slrpnk.net](slrpnk.net) to this list, although I also recommend creating a thread for a more ideal solution, which might be to have an open field for users to add their own instance (excluding banned ones like wolfballs.org, of course).

Cheers!

**Comment by dessalines** [comment]
I'd be good with that. Feel free to do a PR for it.

**Comment by giantsfan006** [comment]
> have an open field for users to add their own instance

with so many new instances popping up this would be awesome
