### ISSUE TITLE
Default sort type errored when set from account settings

### ISSUE THREAD

**Issue by spaceburrito** [dessalines/jerboa#471]
** Jerboa Version **
0.0.32
Android 12
Samsung A12

**Describe the bug**
Several default sort type options are errored.
-TopDay displays Old
-TopWeek displays TopDay
-TopMonth displays TopWeek
-TopYear displays TopMonth
-TopAll displays TopYear
-MostComments displays TopAll
-NewComments displays MostComments

Occurs with Subs, Local, and All listing types. Active, Hot, and New display correctly.

**To Reproduce**

1. Login to jerboa with user account
2. Navigate to Settings > account settings
3. Change default sort type to one of above listed options
4. Scroll down click save settings
5. Close and re-launch jerboa
6. Observe errored post listing

**Comment by dessalines** [comment]
Good catch, thanks for this.
