### ISSUE TITLE
Accessibility: Light Mode Account Text Colour Difficult to See

### ISSUE THREAD

**Issue by JDubyew** [dessalines/jerboa#476]
**Jerboa Version**
0.0.32

**Bug Description**
I'm on a Pixel 7 Pro. I couldn't figure out how to log in at first as whilst in the default Light Mode, the 'Anonymous' account name text colour is so close to the background it makes it difficult to see. I had to join the Matrix chat to figure out how to log in as I couldn't see there was a button to click.

![Screenshot_20230609-122701.png](https://github.com/dessalines/jerboa/assets/17597135/7b2fc005-1abf-4a3e-9e3a-8fce04985328)

**Reproduction Steps**

1. Open the app on a Pixel 7 Pro in Light Mode
2. Open the side bar

**Comment by mitchellss** [comment]
I agree this threw me off too. I'll work on a change to have the text color respond like the other elements in the sidebar.
