### ISSUE TITLE
Display full username and instance combination

### ISSUE THREAD

**Issue by 0hCome0n** [dessalines/jerboa#482]
- [✓] Did you check to see if this issue already exists?
- [✓] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

Please display both the username and the instance wherever usernames are currently displayed as a way to avoid impersonation or confusion with two accounts seeming to have the same username.

This will have the added benefit of reinforcing the federation concept as well as advertising instances to other users in the comments of popular posts.

As an example, please change:

username

To:

username@instance.org
Or
@username@instance.org

The second version would help differentiate the federation system from email, but it's all your call in the end.

Thanks.

**Comment by a1studmuffin** [comment]
Perhaps a good middleground for UX purposes would be `username` for any users on your current instance, and `username@instance.org` for users on another instance.
