### ISSUE TITLE
A new instance of MainActivity is launched when opening the app from the launcher while it's already paused in the background

### ISSUE THREAD

**Issue by oscarnylander** [dessalines/jerboa#485]
**Jerboa Version**
0.0.32

**Describe the bug**
A new instance of MainActivity is launched when opening the app from the launcher while it's already paused in the background. The expected behaviour is for the launcher icon to open the already running instance of MainActivity, instead of spawning a new one.

**To Reproduce**

1. Open the app
2. Bring the app to the background
3. Open the app from the launcher
4. Note that the app does not resume from the point where it was backgrounded
5. Press back
6. Note that this brings you back to the point where the app was previously backgrounded

**Comment by MV-GH** [comment]
i can't reproduce this

**Comment by twizmwazin** [comment]
I could not reproduce this either on my Pixel 5 running Android 13. @oscarnylander what device and software version are you experiencing this on?

**Comment by oscarnylander** [comment]
Now that I tried it a few times again, it stopped happening. Odd. I'm on a Pixel 7 Pro running Android 13.
