### ISSUE TITLE
Inbox unread count does not update when you switch accounts

### ISSUE THREAD

**Issue by aaronfg** [dessalines/jerboa#491]
**Jerboa Version**
0.0.32

**Describe the bug**
The inbox unread count badge does not update when you switch between saved accounts in the app. 

**To Reproduce**
1. Add a profile from some instance that has unread replies
2. Verify that the inbox icon shows the badge with the count of unread items.
3. Add a 2nd account to the app from a different instance. Be sure this account either has a different number of unread messages or has none at all

**Expected Behavior:**

The badge on the inbox tab should change to reflect the inbox unread number for each respective account

**Actual Behavior:**

The badge on the inbox tab shows the number for whatever account has unread messages. Changing to an account with zero unread messages will not clear out that badge when using that account.

**Comment by ZJouba** [comment]
I believe this was fixed with #1051
