### ISSUE TITLE
Can't login through kbin.social

### ISSUE THREAD

**Issue by DraconicNEO** [dessalines/jerboa#494]
**Jerboa Version**
0.0.32

**Describe the bug**
Whenever I try to log into kbin.social I get the error message that the login was incorrect even though I typed the login correctly.

**To Reproduce**

1. Go to 'Accounts' in the left sidebar
2. Click on 'Add Account'
3. Type 'kbin.social' as the instance and your login credentials.

**Comment by brandonlujan** [comment]
Kbin.social is not a lemmy instance, that might be why

**Comment by DraconicNEO** [comment]
> Kbin.social is not a lemmy instance, that might be why

Oh, I was told that it was or that it was compatible with Lemmy. I guess that person lied to me, well thanks for letting me know.

**Comment by NaturalHate** [comment]
kbin is compatible with Lemmy & Lemmy is compatible with kbin, but Jerboa isn't compatible with kbin.

**Comment by DraconicNEO** [comment]
> kbin is compatible with Lemmy & Lemmy is compatible with kbin, but Jerboa isn't compatible with kbin accounts.

Too bad, was hoping to login to my Kbin account on Jerboa, I couldn't find another Android client which supports kbin.
