### ISSUE TITLE
Add homescreen widget

### ISSUE THREAD

**Issue by dtantono** [dessalines/jerboa#507]
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [X] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **
It would be wonderful if this app support widget. So, we can keep tracking our communities easily.

**Comment by dessalines** [comment]
I'll re-open if someone else wants to work on this. Its low priority for me.
