### ISSUE TITLE
Can't search if navigation bar is disabled

### ISSUE THREAD

**Issue by jordan1776** [dessalines/jerboa#510]
** Jerboa Version **
0.0.32
**Describe the bug**
I am not sure if I just can't find it, but it appears if I hide the navigation bar (home, search, inbox, saved, profile), I can't get to the search. The home, inbox, saved, and profile have links duplicated in the left side menu, but I don't see the search anywhere else. 
I feel like it should be in the side menu or top bar or even the 3 dot menu.

**To Reproduce**

1. Disable navigation bar in Settings > Look and feel
2.  :\

**Comment by twizmwazin** [comment]
I noticed this too! I want to add it as an option in the side drawer.
