### ISSUE TITLE
Tapping on comments that end in a link open the link.

### ISSUE THREAD

**Issue by TrollBlox** [dessalines/jerboa#516]
** Jerboa Version **
0.0.33-alpha

**Describe the bug**
Tapping on comments that end in a link opens the link, even when not tapping the link directly.

**To Reproduce**

1. Find a comment that ends with a link.
2. Tap on the comment (but not the link).
3. Link opens.

The comment by @UntouchedWagons@lemmy.ca on [this](https://lemmy.world/post/42894) post is where I found the bug.

**Comment by sensiblepuffin** [comment]
That comment seems to be gone, but I also can't reproduce this issue. For me, no matter where I tapped, it collapsed/expanded the comment, unless of course I tapped on the username or the link itself. Where are you tapping on the comment?

**Comment by TrollBlox** [comment]
I had a screen recording that I stupidly deleted. I was clicking directly horizontally of the link (but not on it).

**Comment by sensiblepuffin** [comment]
Ah, I see it now.

[links.webm](https://github.com/dessalines/jerboa/assets/175900/5a9cd334-30b9-490d-8130-b3d45635d75c)

**Comment by TrollBlox** [comment]
Yes. That is the issue I was experiencing.

**Comment by ZJouba** [comment]
I don't think this is something that Jerboa can fix. It's a third party plugin that parses markdown links
https://noties.io/Markwon/docs/v4/linkify/

**Comment by MV-GH** [comment]
This more of a consequence that we use the default MovementMethod for Markwon. It is pretty flawed. If you click on a line after a clickablespan (links, images) it will still call that clickable span. We need to. implement a better one ourself. I already looked at that but I have not found the time yet to implement it yet. As I want to add longclick and shortclick. see #1096
