### ISSUE TITLE
Swipe upvote / downvote / click and hold

### ISSUE THREAD

**Issue by dessalines** [dessalines/jerboa#52]

**Comment by maltfield** [comment]
I came here to open a feature request: users to be able to:

1. swipe left on a post/card in the jerboa feed to downvote the post
2. swipe right on a post/card in the jerboa feed to upvote the post

This functionality is what I'd expect with reddit clients, namely [RedReader](https://github.com/QuantumBadger/RedReader)

Unfortunately, when I swipe left on the app today, nothing happens. If I swipe right, it opens the navigation menu.

There's no description for this issue, so I assume we're talking about the same thing?

As for the "click-and-hold", I don't know what that would do. But in RedReader it would open a submenu with the following options that can be tapped:

1. upvote
2. downvote
3. save
4. hide
5. report
6. reply
7. view in external browser
8. go to subreddit
9. block subreddit
10. pin subreddit to main menu
11. unsubscribe from subreddit
12. share
13. share comments
14. copy link
15. user profile
16. properties

I guess jerboa should implement a subset of these

**Comment by dessalines** [comment]
Another possibility that would work:

- Tap once = upvote
- Tap again, downvote
- Tap again, remove vote. 

I'd consider any of these solutions good enough.

**Comment by loadsas** [comment]
I really like the idea (maybe because I'm a redreader user ;) ). There are some issues here about accidently clicking something wrong instead of opening the "thread". This would be a good solution and a better UX (my opinion ;) )

Other issues

https://github.com/dessalines/jerboa/issues/488
https://github.com/dessalines/jerboa/issues/418
https://github.com/dessalines/jerboa/issues/394

Maybe there are more but I'm on holidays and only have a smartphone with me. (too straining)

**Comment by heeplr** [comment]
> ... But in [RedReader](https://github.com/QuantumBadger/RedReader) ...

I'd like to add to this, imho, very important point:
RedReader's UX is extremely popular among users who need accessibility features to a point that Reddit exempted it from the upcoming API ban.

It's UI is **very** slick and can be configured to be ultra clean. It's worth imitating in every aspect.

**Comment by Snow4DV** [comment]
WIP. Liked that feature back in the day in sync. 
Can be easily implemented with swipetodismiss, will refactor it and create the PR

![screen-20240120-125243~2_2](https://github.com/dessalines/jerboa/assets/32912696/399f8213-c705-42d6-93c6-fcb65018ce8e)

**Comment by maltfield** [comment]
@Snow4DV thanks for working on this :)

> I'm open to suggestions about colors, icons, moving some of the features to swipe to the right :)

I really, really don't like the "swipe to right to both upvote and downvote"

If you go this route, please make it configurable in settings. Personally, I think it's most intuitive to have:

"left swipe" = downvote
"left long swipe" = also downvote

"right swipe" = upvote
"right long swipe" = also upvote

> swipe to the right is preserved for "go back to feed"

this should also be able to be changed. And, imho, it should default to "upvote".

**Comment by dessalines** [comment]
Done now.
