### ISSUE TITLE
Search and subscribe to new communities

### ISSUE THREAD

**Issue by ravermeister** [dessalines/jerboa#522]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

It would be very helpful if it is possible to search for new (yet unknown to the own instance) communities and subscribe to them, 
IIRC it is currently only possible via the web frontend.

**Comment by EoN-kCw1u5Sh1Ws** [comment]
Yeah, this will be a big deal. I'm trying to use Jerboa as my main way of accessing Lemmy, and switching to browser to search for Communities is quite frustrating.

**Comment by twizmwazin** [comment]
Currently we can search for existing communities known to the instance, can anyone knowledgeable chime in on what is necessary to include communities not yet known to an instance?

**Comment by dessalines** [comment]
This already exists.

**Comment by andreapx** [comment]
> This already exists.

I think that explain how to search for communities for those who wrote up here and for the ones (like me) that came here looking for a solution, would be a good idea.
Thanks!

**Comment by dessalines** [comment]
1. Click the button that says search
2. Start typing
3. Click a community
4. Click subscribe

**Comment by andreapx** [comment]
> 1. Click the button that says search
> 
>     2. Start typing
> 
>     3. Click a community
> 
>     4. Click subscribe

Ops! Thanks!
