### ISSUE TITLE
Changing font size in settings cuts off bottom option "Use Custom Tabs"

### ISSUE THREAD

**Issue by Stugist** [dessalines/jerboa#523]
** Jerboa Version **
0.0.33

**Describe the bug**
As in title.

**To Reproduce**
Steps to reproduce the behavior: Change font size.
![Screenshot_20230611_091845_Jerboa for Lemmy](https://github.com/dessalines/jerboa/assets/102943350/4160b592-2b47-4887-9823-51d98012e7bf)
![Screenshot_20230611_091856_Jerboa for Lemmy](https://github.com/dessalines/jerboa/assets/102943350/68008c3b-f084-4042-ab1a-b7831c3ef8ef)

**Comment by calincara** [comment]
Also seems it's messing up the font slider in the Look and Feel page, as well as the main page. I'm wondering if font size 48 is too much? Maybe it could be reduced to something lower, say 32? Still a bug which needs to be fixed though, even font size 32 is messing up the UI.

![Screenshot_20230611-145120](https://github.com/dessalines/jerboa/assets/28709035/bc82c321-6c3d-451f-9d66-5793ae1bd8fe)

![Screenshot_20230611-144927](https://github.com/dessalines/jerboa/assets/28709035/ce8af9a7-1970-4f67-81ae-8f766abb6449)

**Comment by Stugist** [comment]
I feel like 48 is needed for persons with visual impairments. Like just because 8 is technically readable for me, though it does cause eye strain, my mum wouldn't be able to discern that it was actually text, and size 48 is legitimately the size she would probably use if she was cool and used Jerboa/Lemmy

**Comment by elishamint** [comment]
The Settings pane now generally fails to scroll. Same with "About".
