### ISSUE TITLE
Host translations in Weblate

### ISSUE THREAD

**Issue by ngosang** [dessalines/jerboa#526]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

**Describe the feature request below**

I see you already have internationalization / multi-language support. I will like to help with translation but I don't want to keep track of the changes in GitHub.
Could you add some kind of automation that syncs the `.xml` files with the translations with [Weblate](https://hosted.weblate.org/)? It's easy to translate in their Web UI and I will receive notifications when new translations are required.

https://hosted.weblate.org/

**Comment by ngosang** [comment]
Lemmy is already doing that => https://weblate.join-lemmy.org/projects/lemmy/

**Comment by dessalines** [comment]
Closing as not really needed, ppl have been doing PRs to strings.xml.
