### ISSUE TITLE
Add option to blur or unblur NSFW posts

### ISSUE THREAD

**Issue by JaxiiRuff** [dessalines/jerboa#529]
- [x] Did you check to see if this issue already exists? 
https://github.com/dessalines/jerboa/issues/291
https://github.com/dessalines/jerboa/pull/514
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

If NSFW is enabled simply give the user a choice between blurring or unblurring posts on their feed.

**Comment by Meganium97** [comment]
Seconding this.

**Comment by FerrahWolfeh** [comment]
Yeah, this is really relevant now that lemmy is starting to have more NSFW themed communities that end up appearing in `All`. 

And I also guess that with this, users would feel more comfortable while browsing communities or `All` in public, right?

**Comment by RandomLegend** [comment]
> So the blur works, but there's no way that I can see to turn it off and just have NSFW posts viewable in the cards browsing setting. Is this in the works, or am i missing something?

Yeah i cannot disable it aswell....everything is blurred despite me having ticket "Show NSFW"

**Comment by tgxn** [comment]
> Yeah i cannot disable it aswell....everything is blurred despite me having ticket "Show NSFW"


Really need this, option to unblur all posts
