### ISSUE TITLE
Swipe to discard in-app image viewer (panning off screen issue?)

### ISSUE THREAD

**Issue by jordan1776** [dessalines/jerboa#532]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **
I feel that the image viewer's behavior should match the behavior of other apps, with the biggest issue being the lack of swipe to discard which in somes cases allows the image to go off screen in the current viewer (0.0.33). In comparison:
Fully viewed out:
- Sync/Relay: Gesturing up/ down or tapping anywhere (on or off image) discards image
- Boost: Gesturing up/ down discards image
 tapping anywhere (on or off image) hides/shows navigation 
- Jerboa: Gesturing up/down does nothing
tapping anywhere (on or off image) hides/shows navigation 

Partially zoomed in:
- Sync/Relay: Panning left/right bound by image
 Gesturing up/ down discards image
- Boost: Panning left/right bound by image
Gesturing up/down does nothing
- Jerboa: Panning left/right bound by image
Panning up/down image can go partially off screen.

Deep zoomed:
- Sync/Relay: Panning left/right/up/down bound by image
 if image hits top or bottom of screen, further gesturing swipes to discard
- Boost: Panning left/right/up/down bound by image
Gesturing does nothing
- Jerboa:  Panning left/right bound by image
Panning up/down allows the image to go off screen!

**Comment by MV-GH** [comment]
Swipe up to discard is implemented
