### ISSUE TITLE
Allow sharing posts/comments/users/communities with Android Sharesheet

### ISSUE THREAD

**Issue by maltasoron** [dessalines/jerboa#536]
Thank you very much for your hard work!

Currently, it is possible to tap the three dots next to a post or comment and copy the permalink. However, if I want to send that permalink to someone, I have to switch to another app and send it. I would like to be able to use the [Android Sharesheet](https://developer.android.com/training/sharing/send) to send it with fewer clicks.

Also, I would like to be able to share communities and users the same way.

**Comment by dessalines** [comment]
Stale issue. If someone wants to work on this I can re-open.
