### ISSUE TITLE
Quick comment navigation

### ISSUE THREAD

**Issue by XLRUUU** [dessalines/jerboa#542]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

It would be nice to have two buttons to quickly navigate between next and previous top level comment like it is possible on Boost.

**Comment by DanielVolz** [comment]
Navigation through top comments with volume buttons would be great.

**Comment by V13Axel** [comment]
Came here to suggest the same thing; I keep hitting the volume keys expecting it to jump between top level comments like Sync did.

**Comment by Daniel15** [comment]
Relay for Reddit also used the volume buttons for this purpose. It's a great feature.

**Comment by ToNIX-** [comment]
Please, implement this. Virtual buttons to navigate through the top comments is crucial to have. Thank you!

**Comment by AaronMaria** [comment]
Joey has this with an additional button inbetween to select what the buttons should move to. So for example you can choose "new" instead of "top-level comments" to jump between new comments. I would love this kind of functionality in Jerboa.

**Comment by ToNIX-** [comment]
Thank you for implementing this quickly! Another great addition would be to move to the top (the post itself) when you long press the "up" button.

**Comment by tomewarren** [comment]
Can we also have the volume button set to scroll to the next card? On relay we could configure the button actions

**Comment by dessalines** [comment]
Open these as separate individual issues.
