### ISSUE TITLE
Option to switch the tap to collapse to a hold to collapse comment 

### ISSUE THREAD

**Issue by XLRUUU** [dessalines/jerboa#544]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

It would be great to have a option to switch the tap to collapse comment to a hold to collapse comment

**Comment by LitDub** [comment]
For me, it **is** hold-to-collapse, but **I want** tap-to-collapse. Where are you tapping to collapse without holding?

**Comment by XLRUUU** [comment]
Are you on the latest version? (0.0.33)

For me holding a comment shows or hides the comment action bar (where there's the upvote, downvote, save, comment buttons)
And tapping hides or shows the comment text.

**Comment by LitDub** [comment]
> Are you on the latest version? (0.0.33)
> 
> For me holding a comment shows or hides the comment action bar (where there's the upvote, downvote, save, comment buttons) And tapping hides or shows the comment text.

Sorry, I downloaded from F-droid and got too excited to help before making sure I was on the latest version. I've upgraded now and, although prefer how it's tap-to-collapse in 0.0.33, I do think there be an option to choose between the two.

**Comment by twizmwazin** [comment]
Closing in favor of #52
