### ISSUE TITLE
Keep some context displayed on collapsed comments for reference (in full-collapse mode)

### ISSUE THREAD

**Issue by elishamint** [dessalines/jerboa#545]
**Description**
v. 0.0.33
Collapsed comments, in full-collapse mode, currently show only user name and number of comments in the collapsed sub-tree.
It would help navigation a lot if we would have at least some (truncated) text from the collapsed comment shown, possibly 1-2 lines in small font. It should not take up much more display space than it currently does

**Comment by dessalines** [comment]
I don't like that idea, collapse should mean collapse.
