### ISSUE TITLE
Visual hinting of user relationship with instance in instance string

### ISSUE THREAD

**Issue by servoparmi** [dessalines/jerboa#546]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

We currently show the community@instance.org name in All and Subscribed feeds in green, which is a great visual feature.

We should allow users to enable a function where the instance portion of this is visually hinted as to the user's relationship with the instance. Example using colours:

Grey for no subs or comments on the instance
Orange for subscribed to one or more communities on the instance
Green for home instance
Red for user banned from instance

**Comment by servoparmi** [comment]
I've raised this on the lemmy repo too just in case this makes more sense at a platform level, but it would be bloody useful even if it was implemented solely at jerboa level.  https://github.com/LemmyNet/lemmy-ui/issues/1188

**Comment by dessalines** [comment]
I don't like these colors, no one's going to know what they mean without a guide.
