### ISSUE TITLE
pseudo-logged out on app update

### ISSUE THREAD

**Issue by Luunae** [dessalines/jerboa#547]
** Jerboa Version **
0.0.32 -> 0.0.33 (Play Store)

**Describe the bug**
After updating:
- none of the posts from my subscribed communities display on app load
- After opening the left-side drawer with the top left hamburger menu, it says my username is "Anonymous" at the top, where it would normally say "Luna".
- Tapping on the username space brings a drop-down menu with two options:
- - Add Account
- - Sign out
- Below the username space in the left-side drawer are three options:
- - Local
- - All
- - Settings
- Opening Settings notably has another option inside it: 
- - Luna Settings (Every setting is blank, first option in the list, or unchecked)
- Going back to the top-level of the left-side drawer and changing from Local to All or vice-versa shows no posts, and the error toast `Value <html> of type java.lang.String cannot be c...` displays on attempt to load posts.
- Try to log in and the app crashes to my phone's home screen. This looks like #538.

![Screenshot_20230611_143721_Jerboa for Lemmy](https://github.com/dessalines/jerboa/assets/49705655/ef4d452d-fc02-469c-87b7-c7fe816206b9)
![Screenshot_20230611_143725_Jerboa for Lemmy](https://github.com/dessalines/jerboa/assets/49705655/c7e6e4ea-201c-4202-ac26-8397a703e81f)
![Screenshot_20230611_143729_Jerboa for Lemmy](https://github.com/dessalines/jerboa/assets/49705655/76382d0b-765b-469a-b779-f68763a665b0)
![Screenshot_20230611_143733_Jerboa for Lemmy](https://github.com/dessalines/jerboa/assets/49705655/50dba035-685c-449b-aa6f-4a6d9a04f989)
![Screenshot_20230611_143737_Jerboa for Lemmy](https://github.com/dessalines/jerboa/assets/49705655/bb381b6a-7643-43d9-904a-7c475040e1d4)
![Screenshot_20230611_143804_Jerboa for Lemmy](https://github.com/dessalines/jerboa/assets/49705655/6ce73f77-1041-4595-9cea-5c69c1095cd4)
![Screenshot_20230611_144115_Nova7](https://github.com/dessalines/jerboa/assets/49705655/5b838052-1445-4176-9a03-07226009e9db)

**To Reproduce**

1. Go to Play Store
2. Click on Update
3. Reopen app
5. Force-close and reopen app and error persists.
6. Attempt to login and app crashes.

**Comment by Luunae** [comment]
(Whoops, mobile + accidentally tapped the wrong area of the button)

**Comment by Sebbito** [comment]
It is as seen on the last screenshot;

it looks like a timeout issue from the server and the client not expecting html from the api but a valid data structure.

Maybe a more informative popup would be a good start but sadly i don't know any kotlin nor have the resources to learn android app dev rn :(
