### ISSUE TITLE
Large images in comments can cause juddery scrolling while in view

### ISSUE THREAD

**Issue by Lknechtli** [dessalines/jerboa#548]
** Jerboa Version **
0.0.32

**Describe the bug**

When scrolling past a large image preview in a comment, it sometimes recalculates the image position incorrectly during the scroll and cause it to flash between two positions

**To Reproduce**

1. View this comment: https://lemmy.ml/comment/520826
2. Scroll down to the image. 
3. While the image is on-screen, it will inconsistently calculate the image offset below the comment depending on how fast the scroll animation is. 

https://github.com/dessalines/jerboa/assets/4392704/10552d55-b5cd-4be6-b28d-70b35a3a5f6f

**Comment by outtieTV** [comment]
The app in general is having juddery scrolling for me as well. Android version 11.

**Comment by twizmwazin** [comment]
This issue was fixed in 0.0.33. Let me know if you find that's not the case.

**Comment by Lknechtli** [comment]
Ah, will do. F-Droid hasn't published that version yet so I didn't know there was a new version.

**Comment by Lknechtli** [comment]
Confirmed working correctly on newest version. Thanks!
