### ISSUE TITLE
Read posts don't turn grey until after refresh, and not at all when just viewing image/link.

### ISSUE THREAD

**Issue by bynatejones** [dessalines/jerboa#551]
** Jerboa Version **
Type the version from the settings here.
0.0.33

**Describe the bug**

After I "read" a post and to back to my feed, I expect the post title to be greyed out to show that I've just read that post. However, the title color doesn't change until after I scroll all the way back to the top of the feed and pull down to refresh.

Also, when only opening the image or website link for a post and not opening the post/comments itself, the post never appears as already read. I feel like that would be the expected outcome, since sometimes I don't feel like reading the comments but still want to know I've already viewed that post's content.

**To Reproduce**

1. Read post.
2. Go back to feed.
3. Notice post still appears as if unread.
4. Refresh feed
5. Notice post now appears greyed out correctly.

**Comment by ZJouba** [comment]
This was fixed by #1025

**Comment by MV-GH** [comment]
The repro is indeed fixed, not sure if we should mark a post as read if you view its image directly from the feed? @twizmwazin what do you think

**Comment by twizmwazin** [comment]
I think viewing an image or link directly should mark the post as read
