### ISSUE TITLE
Comment replies icon appears in profile

### ISSUE THREAD

**Issue by jordan1776** [dessalines/jerboa#553]
** Jerboa Version **
0.0.33

**Describe the bug**
Comment replies icon (+N) appears when tapping user comments in profile.

**To Reproduce**

1. Go to 'profile'
2. Tap 'comments'
3. Tap a comment which has replies.

**Comment by priyatanu** [comment]
Hi ,
I would like to work on this issue. Could you please describe more. as I new to the project. maybe with screenshot?

**Comment by dessalines** [comment]
This is fixed.
