### ISSUE TITLE
Downvote button still appears on instances with the button disabled, and crashes the post when pressed

### ISSUE THREAD

**Issue by SekoiaTree** [dessalines/jerboa#555]
** Jerboa Version **
0.0.33

**Describe the bug**
Although my instance has downvotes disabled, the button still appears. Whenever I press it, I get a popup saying "downvotes_disabled" and, if I attempted to downvote a post, it crashes the view and I need to exit and reenter the post.

**To Reproduce**
See above. Need to be on an instance with downvotes disabled though.

**Comment by twizmwazin** [comment]
Fixed in #502, it'll be in the next release.

**Comment by SekoiaTree** [comment]
Shoot, I didn't think of searching closed issues, my bad.
