### ISSUE TITLE
Changing viewing mode resets filters.

### ISSUE THREAD

**Issue by Sarke** [dessalines/jerboa#559]
**Jerboa Version**
0.0.33

**Describe the bug**
Turning the phone (switching to landscape or portrait) will reset the filters to default and restart at the top.  Basically like restarting the app.

**To Reproduce**

1. Open app.
2. Change a filter (e.g. All) and/or sort (e.g. New) and/or scroll down a bit
3. Turn device 90°
4. View is now at the top again with filters and sort reset to default (e.g. Local Active).  You have lost your place and have to start over scrolling.

**Comment by nahwneeth** [comment]
Changing orientation calls the `MainActivity.onCreate` method to redraw the the screen. The `onCreate` method calls `fetchInitalData` that reads the account settings and resets the sort type & listing type to defaults.

https://github.com/dessalines/jerboa/blob/dcaf9915361e25ca1135220c95c55751299a670b/app/src/main/java/com/jerboa/MainActivity.kt#L114

https://github.com/dessalines/jerboa/blob/dcaf9915361e25ca1135220c95c55751299a670b/app/src/main/java/com/jerboa/Utils.kt#L732-L763
