### ISSUE TITLE
White flash with Jerboa logo when starting the application

### ISSUE THREAD

**Issue by garret** [dessalines/jerboa#56]
Using 0.0.4 on Pixel 6 with Android 12. 

Screen flashes to white background with jerboa logo in the middle when opening the app for the first time. This is a bit annoying, especially when opening the app at night. I think that it is a solvable fix as also recently also the app Lemmur and Markor had the same issue but was fixed in the latest updates. 

Some references: 
- https://github.com/LemmurOrg/lemmur/releases/tag/v0.7.0
- https://github.com/LemmurOrg/lemmur/pull/257
- https://github.com/LemmurOrg/lemmur/pull/256
- https://github.com/gsantner/markor/issues/1517

**Comment by dessalines** [comment]
Could you take a video of this so I can see? I don't know if there's anything I can do, the theme is set before that splash screen starts, and it doesn't make any sense that it'd suddenly change.

**Comment by garret** [comment]
@dessalines

https://user-images.githubusercontent.com/27555/150944512-76987b2b-d5cf-42a3-a27b-8dc75ce63139.mp4

**Comment by garret** [comment]
@dessalines with new version .5 I can see that the issue was half-solved. Now when opening the app there is still a white flash in the beginning which then soon switches to a dark background with the jerboa icon in the middle. I attach a new video to be more clear: 

https://user-images.githubusercontent.com/27555/151715349-dbc14ce3-b41b-4c4c-a594-b95dccaf5064.mp4

**Comment by dessalines** [comment]
Really weird issue, but this pry fixes it: https://stackoverflow.com/questions/68925263/removing-the-initial-flicker-of-the-white-background-while-loading-the-compose-a

**Comment by dessalines** [comment]
This should be fixed in the next release, you can see the commit I added that closed this.
