### ISSUE TITLE
Manually sorting subscriptions

### ISSUE THREAD

**Issue by datWeazel** [dessalines/jerboa#561]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **
Currently subscriptions are auto-sorted. For me this results in a weird ordering where communities "ich_iel" and "de_EDV" are at the bottom of the list even tho I subscribed to other communitys that should be after the two(bugreport here: #562). 

This lead me to think: I might want to manually reorder the subscriptions so I can have communities I use more often on the top.

**Comment by dessalines** [comment]
This isn't a feature in the lemmy-back-end.
