### ISSUE TITLE
Subscription sorting broken?

### ISSUE THREAD

**Issue by datWeazel** [dessalines/jerboa#562]
** Jerboa Version **
0.0.33

**Describe the bug**
Assume the following subscriptions: 
- de_EDV
- Germany@someRandomInstance.com
- ich_iel
- Linux
- Memes@lemmy.ml
- Something

One would assube that the order would be alphabetically (the way I listed them above) but in reality the subscriptions `de_EDV` and `ich_iel` are at the bottom. So the list in the app looks like this: 
- Germany@someRandomInstance.com
- Linux
- Memes@lemmy.ml
- Something
- de_EDV
- ich_iel

**Comment by ZJouba** [comment]
Should be fixed by #1131
