### ISSUE TITLE
Add way to get to instance from community

### ISSUE THREAD

**Issue by csm10495** [dessalines/jerboa#566]
- [ x] Did you check to see if this issue already exists?
- [x ] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

Add a way to get to the list of communities on an instance from a community on that instance.

If I'm on an community page (listing new posts, etc) I don't think there is a way to get to the list of communities that instance has.

**Comment by dessalines** [comment]
This is related to federated community searching, which doesn't even exist in the lemmy backend yet.
