### ISSUE TITLE
Failed to connect after a while

### ISSUE THREAD

**Issue by JVT038** [dessalines/jerboa#568]
** Jerboa Version **
0.0.33

**Describe the bug**
When I've installed Jerboa for a couple of hours, maybe a day, it will suddenly lose the ability to connect to Lemmy servers.
The following error appears (both on my Android screen and my logcat):
` okhttp.OkHttpClient: <-- HTTP FAILED: java.net.SocketTimeoutException: failed to connect to lemmy.ml/51.38.185.90 (port 443) from /<my ip address> (port 47702) after 10000ms`
When I reinstall Jerboa, it will work again.
This happens with other Lemmy servers as well (not only with `Lemmy.ml`)

**To Reproduce**

1. Install Jerboa.
2. Log in and wait for a while.
3. Open Jerboa

**Comment by kuroi-usagi** [comment]
The Lemmy Server infrastructure is currently under a lot of load because of the reddit blackout. This seems to be a server issue on the instance you are using.

**Comment by ZJouba** [comment]
@JVT038 are you still experiencing this issue?
