### ISSUE TITLE
Add support for blocking screenshots from being taken

### ISSUE THREAD

**Issue by grrrrr** [dessalines/jerboa#573]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

I am aware that this is not a perfect privacy solution and there are ways around it but it would be useful to have jerboa block the ability to take screenshots and somewhat compliments  [dessalines/jerboa/issues/572](https://github.com/dessalines/jerboa/issues/572)

While the risks / concerns of someone remotely taking a screenshot of jerboa on most peoples devices phone are low there are still users who may be more high risk, it is a possibility that some malware is setup to take screenshots of the recorded data and could result in issues in restrictive countries

Additionally with screenshots blocked, switching apps would result in you seeing jerboa is your list of open apps but not seeing the screen it's contents, an extra benefit

My suggestion would be to add a toggle allowing users to opt-in to this feature,.

Some apps that do that have this option if examples/comparison is needed

* KeepassDX (always blocked)
* Signal (allows toggling screenshot capture on or off)
* ProtonMail (allows toggling screenshot capture on or off)
* Aegis (allows toggling screenshot capture on or off)
* MediLog (allows toggling screenshot capture on or off)
* RedReader (allows toggling screenshot capture on or off)
* Quacker & Fritter (allows toggling screenshot capture on or off)

**Comment by twizmwazin** [comment]
Should be pretty simple, let's make it optional though https://stackoverflow.com/questions/28606689/how-to-prevent-screen-capture-in-android
