### ISSUE TITLE
Tapping on an embedded image in a comment collapses the comment

### ISSUE THREAD

**Issue by abluescarab** [dessalines/jerboa#574]
**Jerboa Version**
0.0.33

**Describe the bug**
When there is a comment with an embedded image, tapping on the image collapses the comment. I would expect it to open a view of the image, even if the image is small.

**To Reproduce**

1. Find a comment with an embedded image ([example](https://beehaw.org/comment/182424))
2. Tap on the image
3. Comment collapses

**Comment by MV-GH** [comment]
Fixed by #1069
