### ISSUE TITLE
I see the replies and mentions empty, althought I had a reply to comments, and notifications don't arrives.

### ISSUE THREAD

**Issue by painkiller1717** [dessalines/jerboa#575]
**Jerboa Version**
0.0.30

**Describe the bug**
The fields inside of Inbox on Replies and Mentions are empty, althought I received some replies to some comments. I also have another problem, and is that notifications don't arrives. I have a Xiaomi, MIUI, and I disabled the optimization battery to not restrict, and enabled the auto start. The notifications are turned on. I'm a new user, but these are the bad thing I experimented, but I love the app: good work! :)

**To Reproduce**

1. Go to Inbox
2. Click on Replies and Mentions
3. Nothing to see here, totally empty, although I have some mentions in comments. 
4. The notifications don't arrive.

I will update in case of any new stuff, and I will be pendent of this. Great app! I think that with time, could evolve in a total amazing work, with the help of the community to report bugs or do suggestions, and ofc with the work of the dev.

Cheers.

**Comment by MV-GH** [comment]
Can you still reproduce this in the latest version?
