### ISSUE TITLE
Image viewer darkened background too small

### ISSUE THREAD

**Issue by jordan1776** [dessalines/jerboa#577]
** Jerboa Version **
0.0.33

**Describe the bug**
The darkened background of the image viewer doesn't stretch all the way to he top and bottom of screen.

**To Reproduce**

1. Tap image which opens the image viewer

**Comment by jordan1776** [comment]
[Image (light mode for visibility)](https://i.imgur.com/LZutOih.png)

**Comment by pipe01** [comment]
What android version are you using?

**Comment by jordan1776** [comment]
Android 11, the phone's an Xperia 1 II

**Comment by MV-GH** [comment]
Should be fixed in #980
