### ISSUE TITLE
Respect show scores account settings

### ISSUE THREAD

**Issue by igarshep** [dessalines/jerboa#578]
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [X] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **
Under account settings, there is a "Show Scores" checkbox setting that does not seem to affect any score visibility toggling

**Comment by painkiller1717** [comment]
Would be great, something like karma or called of another way!
