### ISSUE TITLE
Post sorting ignores stickies

### ISSUE THREAD

**Issue by Coffee-Viking** [dessalines/jerboa#579]
** Jerboa Version **
0.0.33

**Describe the bug**
Not sure it's a bug or actually intended behaviour, but when I sort posts by "newest" I would expect sticky post to be sorted by actual creation time, and not stick to the top. That is IMHO good for the default view when first opening a community, but not as a permanent fixture.

**To Reproduce**
1. Go to any community that has a sticky post on top
2. Click on "sort order" (top right)
3. Select "new"
4. See the sticky still on top despite not being new.

**Comment by ZJouba** [comment]
@MV-GH, @dessalines is this something we'd want to change or should pinned posts always remain on top?
IMO they should stay on top because that's what pinned posts are supposed to do

**Comment by dessalines** [comment]
Yep that's intended behavior, stickied come before all the sorts.
