### ISSUE TITLE
"Incorrect login" when entering correct credentials 

### ISSUE THREAD

**Issue by CrumpThePenguin** [dessalines/jerboa#582]
** Jerboa Version **
0.0.33 Google Play/F-droid

**Describe the bug**
When attempting to login to FMHY.ml it says incorrect login after ensuring it's correct. 

**To Reproduce**
Try to login, instantly get "incorrect login" 

I saw another similar issue but it was noted the instance the user was trying to login to was not a lemmy instance. I'm pretty sure FMHY.ml is though considering I found it via the "find a community" page on the lemmy info page. 

edit: getting same thing with Beehaw too so I'm really not sure what's happening.

**Comment by beatgammit** [comment]
FMHY.ml landing page only mentions a subreddit and a Divolt server, so I'm pretty sure it's not a Lemmy instance.

**Comment by CrumpThePenguin** [comment]
![Screenshot_20230613_022200_Firefox Nightly](https://github.com/dessalines/jerboa/assets/24972809/445cf374-6fb1-48db-894e-20040eefb266)
It shows on recommended on the instance page for me, though I'm unsure of the requirements to appear there. Solved I guess?
