### ISSUE TITLE
Optionally hide avatar, community and preview images in list overview

### ISSUE THREAD

**Issue by heeplr** [dessalines/jerboa#584]
This is technically not a single feature request but so closely related, that I'll put it into a single issue anyway. (Will split it up if needed.)

Screen estate is scarce in the Jerboa post overview listview. 
Optionally disabling community images, user images and previews would provide a much cleaner UI for people who don't need them in the list.

This might also save quite some bandwidth.

**Comment by Bardak** [comment]
Mabey add and extra text only list view that would remove all that and remove in comment images (replacing them with a link to the image)

**Comment by dessalines** [comment]
showAvatars is a user setting, this is done.
