### ISSUE TITLE
#421

### ISSUE THREAD

**Issue by 7heo** [dessalines/jerboa#585]
It is impossible to re-open issues, so I make a new one: #421 isn't solved or me. #422 didn't fix it. (that, or my build of 0.0.33 somehow lacks my fix, but I doubt that).

What I suspect is that the check I put in place in #422 isn't thorough enough, and in case the file explorer doesn't return a valid file, but still returns a "valid path" in the sense of `null` or `EMPTY`, the check succeeds, but the upload fails.

**Comment by twizmwazin** [comment]
Closing in favor of the original issue
