### ISSUE TITLE
Stricken text does not render.

### ISSUE THREAD

**Issue by 7heo** [dessalines/jerboa#587]
**Jerboa Version**
0.0.33

**Describe the bug**
Stricken text does not render. ~~Text~~ is rendered as `~~Text~~`.

**To Reproduce**

1. Make a post or comment or edit any post or comment
2. In the body of the post/comment, write text and include text surrounded by `~~`.
3. Post
4. Read the "rendered" version of the body containing text surrounded by `~~` and not stricken.

**Comment by awdsns** [comment]
This is an aspect of #440 I think? (Spoiler tags and other things don't work either.)

**Comment by 7heo** [comment]
Isn't #440 related to previous markdown render?

**Comment by awdsns** [comment]
Idk, it's still open and markdown rendering issues persist, so I commented there.
