### ISSUE TITLE
Default to viewing All Communities

### ISSUE THREAD

**Issue by EoN-kCw1u5Sh1Ws** [dessalines/jerboa#588]
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **
Every time I open the app, it defaults back to viewing on my local Community. As I'm using quite a small instance, I switch back to All every time.

Defaulting to All will reduce friction on new users seeing as much content as possible and improve their experience.

**Comment by kuroi-usagi** [comment]
You can change this behavior in your user settings. There you will find Default Listing Type. Just switch this to All and save. That should work.

**Comment by EoN-kCw1u5Sh1Ws** [comment]
Completely missed that!

While that is useful, I do think there's value in defaulting to All for new users, so they see as much content across instances.

It seems to me there's some centralization occurring, duplication of Communities etc. Defaulting to all will help alleviate that.

**Comment by twizmwazin** [comment]
Changing the default behavior is something that would need to be fixed on the Lemmy side, not here.
