### ISSUE TITLE
Include on Inbox a button to go directly to a reply of a comment, without had to seek for it on the thread

### ISSUE THREAD

**Issue by painkiller1717** [dessalines/jerboa#597]
**I think could be great add a function to on the Inbox and the replies to your comments, add a button to go directly to that comment and not seek for it in the whole thread. If already exists, which I think not, it doesn't works.**

**Comment by jordan1776** [comment]
On 0.0.34 I see that as the "link" button. Pressing it goes to comment it was replied to, with "view post" and "view context" buttons. I think either the icon should be changed or make pressing the body of the comment go to that comment (instead of collapsing it, for some reason?)

**Comment by painkiller1717** [comment]
> 

Thank you, I only see which that the last version of F-Droid is 0.0.30. Where did you download the 0.34?

**Comment by painkiller1717** [comment]
> On 0.0.34 I see that as the "link" button. Pressing it goes to comment it was replied to, with "view post" and "view context" buttons. I think either the icon should be changed or make pressing the body of the comment go to that comment (instead of collapsing it, for some reason?)

Ok I already saw it here on GitHub, not uploaded to F-Droid or NeoStore yet. And yes in this last version exists that link button. Thank you! There is things to improve and I'm sure it will be of that way, but step by step. Thanks to the developers and contributors!

So this thread is solved.
