### ISSUE TITLE
Hide all read posts

### ISSUE THREAD

**Issue by aflorea-2k** [dessalines/jerboa#598]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

It would be nice to have a button that hides *all* read posts. Sometimes, when I refresh jerboa, I have to wade through tons of posts that I've already seen before getting to stuff I haven't read yet.

Thank you.

**Comment by mulderthefox** [comment]
Or the ability to swipe away posts as I read would be great!

**Comment by WybeBosch** [comment]
Looking forward to this feature aswell
would improve the user experience for me when sorting by top Day
of not having to see the posts i have already seen.

**Comment by AaronMaria** [comment]
Ideally this would be a CheckBox that can be quickly turned on and off, probably best in the menu with "Post View Mode".

**Comment by pabloscloud** [comment]
I would like this too in addition to keeping the current scroll position just like in social media apps. Or am I just used to them too much?

**Comment by Ansis100** [comment]
Jerboa already has a "Show read posts toggle". What you're looking for is a "Mark posts as read on scroll" setting, which would be great.

**Comment by pabloscloud** [comment]
Oh well, found it. Should be in the apps look and feel settings and not the account settings imho

**Comment by MV-GH** [comment]
It is in the account setting because it is a setting that exists per account

Since mark posts as read on scroll already exists, I am closing this issue.
