### ISSUE TITLE
Post Button

### ISSUE THREAD

**Issue by dukethorion** [dessalines/jerboa#602]
- [ ] Did you check to see if this issue already exists?
- [ ] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

I'd like to see the Post Button, which is currently a "+” sign, be changed to the word Post, or some other blatantly obvious button, so the user doesn't think it's an " additional options" thing.  Even here on Github it's a blue arrow that stands out from the rest of the screen.

**Comment by twizmwazin** [comment]
I think the floating action button is a pretty standard button in the android ecosystem that doesn't necessarily need to always show text. I do think we could change the icon to something like a pencil or a pen and paper and that might make it more obvious.

**Comment by dukethorion** [comment]
> I think the floating action button is a pretty standard button in the android ecosystem that doesn't necessarily need to always show text. I do think we could change the icon to something like a pencil or a pen and paper and that might make it more obvious.

I should have explained it better.  The floating action button is fine.  As I am typing this comment here on GH, there is a blue arrow at the top right, which indicates posting this comment.  On Jerboa, in the Post Compose screen, this button is also a smaller + sign.  That is what I'm looking to enhance.

**Comment by dukethorion** [comment]
![Screenshot_20230613-220410-01.jpeg](https://github.com/dessalines/jerboa/assets/81173278/f7242b11-3576-4354-9e77-20afaa33b973)

**Comment by Chris-Kropp** [comment]
I'd propose the [send icon](https://fonts.google.com/icons?selected=Material+Icons+Outlined:send:&icon.query=send&icon.set=Material+Icons), I'm not sure about including text or not, personally, leaving it off seems to match better with the rest of the app.
![Icon_only](https://github.com/dessalines/jerboa/assets/52611624/0792c7ea-c8f7-4259-a2a2-9148bd540ee8)
![Text_and_icon](https://github.com/dessalines/jerboa/assets/52611624/7e30706b-249b-466b-af46-2bdc445cbb16)
