### ISSUE TITLE
Vote Count

### ISSUE THREAD

**Issue by dukethorion** [dessalines/jerboa#607]
- [y ] Did you check to see if this issue already exists?
- [y ] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **
Next to the vote count number (next to the time), can we get small arrows or color code (green/red), to indicate what that number is?

**Comment by dessalines** [comment]
The specific counts are already shown on the action bar. The top right is only the sum score.
