### ISSUE TITLE
Add PR template that informs the reader about formatKotlin

### ISSUE THREAD

**Issue by MV-GH** [dessalines/jerboa#615]
Basically title, add a template for pull requests that informs the reader that the reader shouldn't forget to do `./gradlew formatkotlin`

**Comment by kuroi-usagi** [comment]
Better approach would be to have a pre-commit hook that executes it maybe?

**Comment by MV-GH** [comment]
I am not opposed to that either way it should be mentioned in CONTRIBUTING.md

**Comment by twizmwazin** [comment]
It needs to be documented either way. In my experience even if you have a pre-commit config most users won't use it.

**Comment by a1studmuffin** [comment]
I like the idea of setting up a basic CONTRIBUTING.md, just mentioning this and any other practices/conventions we want to adhere to along the way.

**Comment by kuroi-usagi** [comment]
Yes, a contributing doc would be nice

**Comment by a1studmuffin** [comment]
Other things that would be good to mention:
- when to bump the settings database version
- making changes to strings.xml files (to make localisation changes easier to manage)

**Comment by MV-GH** [comment]
> It needs to be documented either way. In my experience even if you have a pre-commit config most users won't use it.

https://github.com/jeremymailen/kotlinter-gradle#git-hooks

it's possible to force add them on build
