### ISSUE TITLE
Account specific Look and Feel 

### ISSUE THREAD

**Issue by CodeF53** [dessalines/jerboa#619]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

## Describe the feature
Allow "look and feel" settings to vary based on the selected account.

For example:
- On my main, list style post view, dynamic theme color
- On my alt, card style post view, pink theme color 

The way I would handle implementing this is to have a global setting. Then, in the account specific settings, all the drop downs would have an extra "default" option, which points to the global setting. 

## why 
1. Easier to tell what account I have selected when using the app
2. (once #529 is resolved) I would like to have NSFW blurred in my main and not on my alt

**Comment by dessalines** [comment]
I'm leaning toward no, that app settings should be general for your app, while account settings are specific to your lemmy account. This is how its structured in the DB too. 

Thoughts @twizmwazin ?

**Comment by twizmwazin** [comment]
I support the idea, generally. The use case @CodeF53 described makes sense to me, and I don't see a reason to reject it outright. I'd probably choose to implement it a bit differently though. The look & feel settings would become "profiles" that users could create any number of, and then they can assign those profiles to an account, or something along those lines. I don't see this as being high priority though, as there are so many core features that still need attention.

On a somewhat related note, I feel like there should be a stronger delineation between account settings and look and feel settings. Account settings should ideally be client-agnostic. The web client doesn't make this type of distinction, it has few look & feel settings so it just places them with the others. Show avatars, nsfw, and scores are all things that have more to do with how the client presents information than how the server presents your account to other users, and so I think it is reasonable to want to support setting these differently in Jerboa than how they might be set on the web client.
