### ISSUE TITLE
UX Suggestion - Add Community Search to Top-Left Hamburger Panel

### ISSUE THREAD

**Issue by dginovker** [dessalines/jerboa#620]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

Add a button right here that says "Search" and it takes you to the community search page:

![image](https://github.com/dessalines/jerboa/assets/32943174/d25d5508-67fc-4ca8-8559-e082141e35f8)

Note the search page already exists, this would just be another way to redirect to it.

This is a feature on Boost. Would be a great little UX touchup, since it's nice to have multiple ways to get to commonly accessed features.

**Comment by twizmwazin** [comment]
0.0.34 adds a "communities" option below saved, This might get renamed to search depending on how the search UI evolves. Does that implement what you want?

**Comment by dginovker** [comment]
Probably yea
