### ISSUE TITLE
Markdown spoilers and block quotes not rendered

### ISSUE THREAD

**Issue by trubeck** [dessalines/jerboa#627]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

As you can see in the screenshot, Markdown is not rendered in the overview. This poses a problem for me because I want to run a community for a book series and I want to hide spoilers, especially in the overview, so that new readers don’t miss out on the fun.

![tempFileForShare_20230614-085442](https://github.com/dessalines/jerboa/assets/13149855/f57175f1-ba08-460b-a9b2-4bd43722fa35)

**Comment by twizmwazin** [comment]
I believe that markdown is rendered, but spoilers are not currently rendered.

**Comment by trubeck** [comment]
Yes, spoilers and strike-through text are is not working. I created a separate issue for this: #628 

But in the overview, no Markdown is rendered at all.

**Comment by beatgammit** [comment]
Strike through and block quotes seem to work on the latest in main, spoilers are a WIP.

**Comment by ZJouba** [comment]
@twizmwazin Should we support `:::` or `<details>`? Also, do we want to support nested spoilers?

**Comment by MV-GH** [comment]
This should be supported now.
