### ISSUE TITLE
Markdown spoilers and strike-through text not rendering

### ISSUE THREAD

**Issue by trubeck** [dessalines/jerboa#628]
** Jerboa Version **
0.0.34

**Describe the bug**
Markdown spoilers and strike-through text is not rendered in Jerboa.
You can view my post regarding this issue on Lemmy: [https://feddit.de/post/814396](https://feddit.de/post/814396)

**Comment by twizmwazin** [comment]
Strike through should be fixed by #610, spoilers are a duplicate of #627
