### ISSUE TITLE
Unable to login with lemmy.ml account

### ISSUE THREAD

**Issue by nunokalhau** [dessalines/jerboa#636]
** Jerboa Version **
Latest

**Describe the bug**
Tried logging in, login error returned, I'm able to login in the desktop.
Able to login with a different instance account.
Clearing cache/data and starting over didn't solve the issue.

**To Reproduce**

1. Try to login using lemmy.ml account

**Comment by MV-GH** [comment]
Does it still consistently happen? (Not a chance that lemmy.ml was down during that time?)

**Comment by nunokalhau** [comment]
> Does it still consistently happen? (Not a chance that lemmy.ml was down during that time?)

It was working on the PC, just tried it again now and was able to login in the app. Closing this ticket.
