### ISSUE TITLE
Seperate multi-paragraph posts/comments into seperate text elements 

### ISSUE THREAD

**Issue by shortwavesurfer2009** [dessalines/jerboa#637]
** Jerboa Version ** 0.0.34

**Describe the bug**
When using talkback on long posts you just get a large wall of text instead of seperate elements per paragraph. Take https://feddit.it/post/326148 for example. In lemmy this post looks like this when talkback is enabled. 
![Screenshot_20230614-054343_Jerboa_for_Lemmy](https://github.com/dessalines/jerboa/assets/116814522/1f45654f-e1fd-4725-9c41-db68d035ece7)

In the web interface that same post appears like this.
![Screenshot_20230614-054535_Fennec](https://github.com/dessalines/jerboa/assets/116814522/942a04a8-2c65-42c1-ae72-46ee54695e25)
![Screenshot_20230614-054544_Fennec](https://github.com/dessalines/jerboa/assets/116814522/a61236ec-715c-4d5d-83cf-6e7f3963eaaf)
![Screenshot_20230614-054550_Fennec](https://github.com/dessalines/jerboa/assets/116814522/1fecb857-97d3-4d2c-8e76-d4b406aae623)

Notice how the green box only highlights the current paragraph? Each paragraph is its own element

**Comment by dessalines** [comment]
This probably has to do with the markdown renderer, markwon. You'll need to open an issue there.
