### ISSUE TITLE
Action Bar Buttons get pushed off screen when comment count is too high

### ISSUE THREAD

**Issue by kuroi-usagi** [dessalines/jerboa#639]
** Jerboa Version **
0.0.34

**Describe the bug**
Action Bar Buttons beneath a post are being pushed off screen when the comment counter gets to high or has too much text  alltogether.

**To Reproduce**
1. Open Jerboa
2. Open one of the top comments with more then 100 comments
3. Check if the more action button is still visible
4. It is not (see screenshot)

![Screenshot_20230614_130829_Jerboa (DEBUG)](https://github.com/dessalines/jerboa/assets/40325654/38eb24b5-46d2-42af-ad15-265166ebae4f)

I have a quick fix for this but its not a pretty one.

![Screenshot_20230614_130853_Jerboa (DEBUG)](https://github.com/dessalines/jerboa/assets/40325654/0f443584-0bc0-48f6-851d-1aecfce56278)

**Comment by servoparmi** [comment]
What version of Android is that screenshot from?

**Comment by kuroi-usagi** [comment]
> What version of Android is that screenshot from?

Android 13

**Comment by noloman** [comment]
This is about the hamburger menu, isn't it? the three vertical dots (...)

**Comment by kuroi-usagi** [comment]
Yes exactly those, but it concerns basically all the buttons in this section. In extreme cases all of them will be pushed out of the screen.

**Comment by noloman** [comment]
Ok, I think I can try to take care of this

**Comment by ZJouba** [comment]
@twizmwazin, @MV-GH, @dessalines how do we want to tackle this? Even setting the Arrangement to SpaceAround doesn't leave enough space. We should also decide on a minimum width that we want to cater for, I think 240px is the norm?
![image](https://github.com/dessalines/jerboa/assets/42601911/4b48d0eb-eef2-409c-8c15-54a298c3723f)
It get's especially messy if all the buttons are available
Should we move ActionButtons to the More menu when there isn't enough space?

**Comment by MV-GH** [comment]
I am open for changing `XXX comments (XXX new)` to `XXX (+XXX)` But only for card layout as list layout does not suffer this problem. I was discussing this in matrix too

**Comment by dessalines** [comment]
I think a flowrow, and maybe smaller margins is probably the best way to handle it. That would safely cover all screen widths by wrapping to new lines.

**Comment by Freeman999** [comment]
Maybe we could shorten the "comments" or even remove it? When removed, the buttons have a lot more space and if the counter rounds (for example like reddit to "12.4k") then the counter doesnt evet take much space.
