### ISSUE TITLE
Bottom bar Saved button label says Search

### ISSUE THREAD

**Issue by servoparmi** [dessalines/jerboa#640]
** Jerboa Version **
0.0.34

**Describe the bug**
The bottom bar has 5 action buttons. One of them shows the Saved icon but has the label Search. 

**To Reproduce**
1. Open app
2. Navigate to any feed page (all, subbed, etc)
3. Observe the bottom bar. 

![Screenshot_20230614-222154](https://github.com/dessalines/jerboa/assets/136274388/6e7db975-9255-4482-a95c-1c5a50131bde)

**Comment by servoparmi** [comment]
Love the app, you guys are doing an amazing job! Remember to take time for yourselves and your families!

**Comment by itsmegb** [comment]
This is already fixed in #608
