### ISSUE TITLE
Jerboa not working on older Lemmy servers?

### ISSUE THREAD

**Issue by retiolus** [dessalines/jerboa#645]
**Jerboa Version**
0.0.33

**Lemmy Version**
0.16.7

**Describe the bug**
Feeds don't load: `java.lang.IllegalStateException: Expected a string but was BO...`

**Comment by twizmwazin** [comment]
@dessalines Can you comment here, was there a breaking API change that we should document?

**Comment by dessalines** [comment]
Yes, we can't support below v0.17 rn. The next 0.18.0 release, i'll create a `release/v0.17` branch, that we can cherry pick too, if we want to support old versions.

**Comment by twizmwazin** [comment]
Does lemmy have a version endpoint that we can use cross version to check if an instance is new enough?
