### ISSUE TITLE
Show Read Posts (Unchecked) Hides Your Posts;  Add Exception for Self

### ISSUE THREAD

**Issue by randomletters** [dessalines/jerboa#646]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **
I made the embarrassing mistake of posting multiple times thinking that my post was not going through because I couldn't find it in any of my feeds.  I finally realized that if i checked the "Show read posts" box, then I could see my submissions.

I would think that everyone would want to see their own posts even if they were read.  So, maybe add a feature to only hide posts that you did not submit.

**Comment by nightgolfer** [comment]
Out of curiosity - where are you seeing this setting? I've just been on a rant about how I wish I could hide read posts in Jerboa, and now you're saying it's already there? I've looked though every menu I could find - where is it? 😅

**Comment by randomletters** [comment]
Hamburger Menu -> Settings -> [username] settings
Scroll down and look for "Show read posts"

**Comment by WybeBosch** [comment]
Ah so thats where that  option is, i would have thought it would go under "Look and feel", but i suppose its a Lemmy setting and not a Jerboa setting.

**Comment by randomletters** [comment]
It looks like it may be.  Should this issue be moved over to the main project?  Is it a ui or core issue?

**Comment by randomletters** [comment]
It looks like it is an active [issue in ui](https://github.com/LemmyNet/lemmy-ui/issues/1186).

**Comment by MV-GH** [comment]
This is a backend issue see [#](https://github.com/LemmyNet/lemmy/issues/3691)
