### ISSUE TITLE
Add list/search community on sidebar

### ISSUE THREAD

**Issue by Xanvial** [dessalines/jerboa#647]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

Currently on navigation bar there's a button to show a page containing list of subscribed community, with search bar that can search all community (including from other federated instances). But only the subscribed list that exist on sidebar. Which is why when Show Navigation Bar setting is disabled, there's no way to search other community.

I propose to duplicate the community button in navigation bar to sidebar, same as other buttons (like inbox, saved, and profile)

**Comment by twizmwazin** [comment]
Since 0.0.34 there is a communities button in the side drawer.
