### ISSUE TITLE
Multiplatform support

### ISSUE THREAD

**Issue by xinkev** [dessalines/jerboa#649]
Do you have any plans to support multiple platforms or is there anyone working on converting this project into a multiplatform one? Compose, for instance, now even supports iOS, although it is still in its early stages. I believe this is the opportune time and situation to do so. Having a fast client would benefit everyone. What are your thoughts on this?

PS: The issue template suggests taking questions and discussions to the Lemmy community, but I believe this is the right place to discuss this matter.

**Comment by twizmwazin** [comment]
It's not on the radar currently. iOS users have a good quality app in mlem, and I think most users would prefer to use something that feels native and integrated with their OS rather than a hastey port from another. Maybe once Jerboa is somewhat feature complete it could be considered.

**Comment by MV-GH** [comment]
I have made the API multiplaform, see https://github.com/MV-GH/LemmyBackwardsCompatibleAPI

So there is movement in that direction, but the app itself being multiplatform is still far away. Too many java dependencies. And all Android dependencies will need to be abstracted away.

**Comment by dessalines** [comment]
I can re-open if someone wants to work on this, but its not on my radar.
