### ISSUE TITLE
The Saved section in the toolbar is labelled Search

### ISSUE THREAD

**Issue by NicoCharrua** [dessalines/jerboa#653]
** Jerboa Version **
0.0.34

**Describe the bug**
In the toolbar, the fourth item that shows saved posts is labelled Search.

![Screenshot_20230614-201102](https://github.com/dessalines/jerboa/assets/55714525/e9378688-e738-4f95-b4b4-ba301f4344db)

**To Reproduce**
Look at the screen

**Comment by daviessm** [comment]
Duplicate of #640, #604
