### ISSUE TITLE
Share images directly from app

### ISSUE THREAD

**Issue by break6700** [dessalines/jerboa#668]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

Currently, Lemmy supports downloading images however, in certain apps you can simply share the image instead of downloading them. This saves space on the users device and also helps if they want to send something a little for nsfw and not have it appear in my camera roll at some random point.

    ![signal-2023-06-15-08-00-15-002.jpg](https://github.com/dessalines/jerboa/assets/44082853/77ec3f3b-95cb-4ffc-87ec-a8e986c83572)

**Comment by MV-GH** [comment]
Would this pr https://github.com/dessalines/jerboa/pull/651 solve that ?

**Comment by twizmwazin** [comment]
We could definitely add a share widget that shares the image itself rather than a link to the image.

**Comment by vivia** [comment]
As a workaround you can "Copy link" (not Permalink) from the three dots on the bottom right of the post, and share that. If you want to share it as an image, you can paste it into your browser and share it from there.

**Comment by MV-GH** [comment]
Supported now
