### ISSUE TITLE
Add haptics for better feel

### ISSUE THREAD

**Issue by 0mega28** [dessalines/jerboa#669]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **
Haptics feedback while upvoting, downvoting and opening a new post. We can see where we can add haptics in other places.

**Comment by twizmwazin** [comment]
Many third-party reddit apps do implement haptics in response to user actions, typically actions that require a tap or long-press.

**Comment by dessalines** [comment]
Stale issue. If someone wants to work on this I can re-open.
