### ISSUE TITLE
Bottom Bar has 2 search labeled buttons

### ISSUE THREAD

**Issue by marcellogalhardo** [dessalines/jerboa#675]
** Jerboa Version **
0.0.34

**Describe the bug**
The search bar has two buttons with the label search. The second one seems wrong.

**To Reproduce**

1. Open the app.
2. See the bottom bar at home screen.

![Screenshot_20230615-190003.png](https://github.com/dessalines/jerboa/assets/4348197/2ccd87c7-98da-4371-bc6a-3acd512aeadb)

**Comment by twizmwazin** [comment]
Duplicate of #604
