### ISSUE TITLE
Where's the button to change localization

### ISSUE THREAD

**Issue by RVGamer06** [dessalines/jerboa#678]
Can't find a Settings button or an option to change the app localization, which stays in English

**Comment by MV-GH** [comment]
See https://github.com/dessalines/jerboa/issues/603

**Comment by MV-GH** [comment]
Do you want the localization to be the one your phone is set too? then it might already do that but there isn't probably any localization yet for your language. What language do you want to set it too?

**Comment by RVGamer06** [comment]
Italian, which i think has been already introduced

**Comment by MV-GH** [comment]
Yes it has, so you have your phone in itialian locale but Jerboa is still in English?

**Comment by RVGamer06** [comment]
The first time i installed it, yes. I installed it back again and seems to be at least partially translated. I guess the localization isn't complete or it's a temporary bug on my device

**Comment by MV-GH** [comment]
Hmm Italian is only missing about 10 translations, can you post a few screenshots of the missing translations
