### ISSUE TITLE
Jerboa renders differently than the browser

### ISSUE THREAD

**Issue by JacksonBailey** [dessalines/jerboa#684]
**Jerboa Version**

0.0.33

**Describe the bug**

Jerboa renders differently than the broswer. Jerboa hides raw HTML tags while the browser displays them as-is.

**To Reproduce**

1. Go here https://programming.dev/comment/116279

On browser you see `<b>raw HTML?</b>` but in the app you see `raw HTML?`.

**Comment by twizmwazin** [comment]
We're using Markwon's html plugin. We can remove it if it is causing problems. Here's the offending code: https://github.com/dessalines/jerboa/blob/main/app/src/main/java/com/jerboa/ui/components/common/MarkdownHelper.kt#L50

**Comment by JacksonBailey** [comment]
Okay, I (very very briefly) dug in and [lemmy-ui][1] uses [markdown-it][2] which says it also uses CommonMark so I'm not sure exactly what is wrong. My hope is maybe there is a simple flag that's missing or something. [Markwon link][3] for completeness.

[1]: https://github.com/LemmyNet/lemmy-ui/blob/79f40095416ad623f18aa0042f7be9c7ed691582/package.json#L59
[2]: https://www.npmjs.com/package/markdown-it
[3]: https://noties.io/Markwon/

**Comment by twizmwazin** [comment]
Commonmark is just a specification. It's the implementations that actually do something and have behavior. In theory, two pieces of software implementing the same specification should behave the same, but in both cases it's complicated because they may omit parts of the spec, and we both use extensions that add features on top of the base spec. What the Lemmy project as a whole should do is decide exactly what markdown features Lemmy clients should and should not support, so that every client can implement those specs as precisely as possible instead of just supporting whatever they want. Basically, we need to build our own specification based on commonmark.

**Comment by JacksonBailey** [comment]
Well said about Lemmy needing its own spec for a CommonMark derivative. Having some agreed way to generate HTML from the CommonMark text would be nice though. It would help avoid ambiguities like this.

CommonMark is clear with regards to how to render in-line HTML, but it isn't a safe thing to do blindly. It says to include it in the output HTML. Doing that would allow for trivial XSS though. I think both of Lemmy UI's and Jerboa's approaches are fine because they wouldn't result in XSS. Both are obviously better than just blindly shooting inline HTML to be rendered. I guess I assumed the CommonMark spec would say to exclude script tags or something.

[Spec section on raw HTML](https://spec.commonmark.org/0.30/#raw-html).

>Text between `<` and `>` that looks like an HTML tag is parsed as a raw HTML tag and will be rendered in HTML without escaping. Tag and attribute names are not limited to current HTML tags, so custom tags (and even, say, DocBook tags) may be used.

[Example](https://spec.commonmark.org/dingus/?text=%3Cscript%3Ealert(%27xss%27)%3C%2Fscript%3E%0A) with CommonMark's live web preview. See the HTML tab. Understandably, they don't run the contents of the script tags in the preview so there is nothing to experience.

In my opinion this is arguably no longer a problem since both are deviating to avoid XSS and there is no objectively correct way to do it. I'll leave it to be closed or not by you though. It depends if your opinion is that Jerboa should match Lemmy UI 100% or not in the absence of an agreed spec.

**Comment by dessalines** [comment]
Stale issue. If someone finds specific cases, open them.
