### ISSUE TITLE
[BUG] (0.0.34 alpha) Slow Scrolling compared to other apps

### ISSUE THREAD

**Issue by outtieTV** [dessalines/jerboa#689]
** Jerboa Version **
[Jerboa v0.0.34-alpha](https://github.com/dessalines/jerboa/releases/tag/0.0.34)

**Describe the bug**
Slow scrolling through any part of the app.

**To Reproduce**
Android version 11.
Open Jerboa and scroll down. Scroll speed is much slower than my other social media apps.

**Comment by MV-GH** [comment]
Duplicate of #445
