### ISSUE TITLE
Media Preview on Long Press

### ISSUE THREAD

**Issue by AaronMaria** [dessalines/jerboa#700]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

It would be nice if you could preview Pictures and Videos on long press on them.
So if you press and hold on an image it would be shown fit to screen until you let go.

**Comment by beatgammit** [comment]
Is this just for posts in the post list, or also for comments?

Related: #658.

**Comment by AaronMaria** [comment]
I guess ideally both.

**Comment by MV-GH** [comment]
There is a imageviewer  for images even in comments. Videos still need to be supported in a separate viewer

**Comment by dessalines** [comment]
^^
