### ISSUE TITLE
Prominent UI button for toggling read post visibility

### ISSUE THREAD

**Issue by CTalvio** [dessalines/jerboa#705]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

Essentially something like the "clear" button in the Relay reddit app. Or a filter setting.

A fast way to toggle the "show read posts" user setting would allow users to more often and easily switch between these two browsing modes. I find myself constantly flip flopping between disabling it for discoverability, and enabling it to come back to stuff.

**Comment by AaronMaria** [comment]
Possible duplicate of #598

**Comment by dessalines** [comment]
Stale issue, but if someone wants to work on this, I'll re-open.
