### ISSUE TITLE
Incorrect bookmarks button title

### ISSUE THREAD

**Issue by varaki** [dessalines/jerboa#707]
** Jerboa Version **
v0.0.34-alpha

**Describe the bug**
Incorrect button title: bookmarks button has the title "Search"
![Screenshot_20230616-212531_crDroid Home](https://github.com/dessalines/jerboa/assets/23281360/4af9b2e7-bad3-4fc3-b2ef-8446bf7770f0)

**To Reproduce**
Steps to reproduce the behaviour:
Open the app, look at the navigation bar at the bottom 😃

**Comment by MV-GH** [comment]
Duplicate and fixed already, will be there in the next release

**Comment by varaki** [comment]
Closed as duplicate and solved.
