### ISSUE TITLE
Add option to save post from list view 

### ISSUE THREAD

**Issue by sockenklaus** [dessalines/jerboa#712]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

**Describe the feature request below**
Please add an option to save posts from list view.

Edit: Maybe a "swipe to save" would be applicable here so the list view doesn't get cluttered.

This has been requested in https://lemmy.ca/post/702033

**Comment by noloman** [comment]
I think I can take care of this. 

I'll just reuse the save post button as in the other post layouts, and in the future, we can always switch to a swipe to refresh. 
However I think it's better for now to just have a minimal save post button to let users save them.

**Comment by sockenklaus** [comment]
> I think I can take care of this.
> 
> I'll just reuse the save post button as in the other post layouts, and in the future, we can always switch to a swipe to refresh. However I think it's better for now to just have a minimal save post button to let users save them.

Thank you for your offer. 

Although I have no say in this matter please consider the following: User's behaviour is hard to change and makeshift solutions are the most long lasting in a world where you have little time to implement a proper solution. So if you implement the save button as in the other post layout for a quick fix it will most probably stay that way, either because the users will accustom to this this UX or because it's "good enough" and no one will invest the time to change it further down the line.

So my advice (again: without having any say) is: Lets decide what UX is the best in this situation (swipe was just the first thing that came to my mind)and implement it the proper way.

**Comment by noloman** [comment]
> So my advice (again: without having any say) is: Let's decide what UX is the best in this situation (swipe was just the first thing that came to my mind) and implement it the proper way.

Definitely! who's to decide about the UX then? there are several ways of doing this: swipe, hamburger menu at the top right with a save button in a contextual button, etc.

**Comment by sockenklaus** [comment]
> Definitely! who's to decide about the UX then?

That's a good question that should be addressed sometime soon. Probably @dessalines and @twizmwazin because they are the code owners. If the project grows as fast as it did in the last week's and continues to receive so many requests and contributions there should be some strategy to decide which feature requests are worth accepting and some coordination in that regard.

**Comment by dessalines** [comment]
There's no post action bar in the list mode, but you can click into the post and do this. There's also swipe actions now that can save the post.
