### ISSUE TITLE
Switch from landscape to portrait sometimes causes a server error and all text and current position is lost

### ISSUE THREAD

**Issue by shodanx2** [dessalines/jerboa#713]
I imagine that changing the phone orientation is causing a page reload.

If the server is overloaded at that moment and an error is returned, what you were reading is lost.

I imagine that the client flushes the buffer before or while making the request and if the server has become unreachable then it no longer has anything to show.

FIrst solution, no page reload just because orientation has changed

If doing a page reload, do not flush the buffer until a successful server response with data has been received

If there is a server error, do not give up and leave the user stranded. 
1. Try the request again with the same parameters
2. Try 3 times
3. When you give up, give the user a retry button so they can retry on their own, also write the error message on screen instead of an ephemeral error message.

**Comment by sockenklaus** [comment]
Is this issue related with this discussion?

https://lemmy.world/post/197137

**Comment by shodanx2** [comment]
Hard to say, I did not lose my account this time. 

But it did happen to me last week immediately after I setup my account.

I wouldn't be surprised if it is similar reload-on-change-orientation logic

**Comment by nahwneeth** [comment]
Similar to #559. And fixed by #690.

**Comment by shodanx2** [comment]
sweet !
