### ISSUE TITLE
Change Android Back Button Behavior

### ISSUE THREAD

**Issue by 0hCome0n** [dessalines/jerboa#714]
- [✓] Did you check to see if this issue already exists?
- [✓] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

The current behavior for the Android OS back button is such that Jeroba will simply cycle backwards through the pages you've visited, irrespective of what "level" they are at in the app navigation.

For example, if you open the app, and from the home screen use the app's bottom nav bar to go to your inbox, then your profile, then your bookmarks, hitting the Android back button repeatedly will get you:

Bookmarks → profile → inbox → app home → exit app

Instead, the app should cause any use of the lower app navigation bar to reset the stack for the back navigation. It should reset to:

Current screen → app home → exit app

This would help get rid of the weird behavior where you cycle through multiple screens on the same level of the app before unexpectedly exiting because you hit the OS back button too many times. It would also get rid of the weird behavior where hitting the OS back button can send you back into a comments section long after you navigated multiple screens away and have forgotten about it.

While I'm sure "fixing" this navigation issue will be a low priority, I still wanted to put in the request just so we at least have a placeholder.

**Comment by beatgammit** [comment]
This should be an option as per https://lemmy.world/post/437338
