### ISSUE TITLE
Search/Community Page: Menu/Options icon doesn't do anything

### ISSUE THREAD

**Issue by FWCologne** [dessalines/jerboa#717]
** Jerboa Version **
0.0.34

**Describe the bug**
On the "search" page, if you tap on the menu/options icon in the top right corner, nothint happens.

**To Reproduce**
1. Go to 'search' page
2. Click on 'menu'/'options' icon (three dots) in top right corner
3. Nothing happens

**Comment by IchbinLuka** [comment]
What is that button supposed to do? Or can it just be removed?

**Comment by ZJouba** [comment]
This has been disabled for now in #1099 until there is a use for it

**Comment by MV-GH** [comment]
It never had a use, the whole searching thing needs to be revamped. If someone can "draw" how a full functional search should look that can search posts/communites/ possible instances/ users and can sort these by on all the sorttypes there is also that you can specify the search to be in All/local/subscribed. So quite a lot of options. Then I'll take a look at implementing it.
