### ISSUE TITLE
add custom feeds 

### ISSUE THREAD

**Issue by xenxs82** [dessalines/jerboa#721]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

Please add an option to creature custom feeds that would only show communities/magazines that have been added into it e.g. gaming related communities/magazines.

**Comment by twizmwazin** [comment]
I agree this would be a useful feature, However, I think this is something that might want to be implemented on the server side first and then Jerboa would just expose a UI for it, rather than building the entire implementation locally.

**Comment by dessalines** [comment]
Like multi-communities? No idea what this is referring to.
