### ISSUE TITLE
Meta: Add GitHub "Topics"

### ISSUE THREAD

**Issue by maltfield** [dessalines/jerboa#723]
To make this repo easier to find, can you please edit the repo in GitHub and add some "topics" to it?

### Why?

Currently, this repo does not appear when searching for repos on GitHub tagged with `lemmy`

 * https://github.com/topics/lemmy

## Solution

Please edit this repo (click the "gears" button next to the "About" heading) and add the following tags:

1. lemmy
2. activitypub
3. link-aggregator
4. fediverse
5. android
6. reddit
7. mobile-app
8. kotlin
9. (etc)

**Comment by krestenlaust** [comment]
"Reddit" doesn't belong on the list of topics, it already has "link-aggregator", and in general isn't really fitting, as Lemmy isn't a 'Reddit'.

Also, strictly speaking, the link-aggregator would only be the backend, right?

**Comment by twizmwazin** [comment]
This is one @dessalines has to do, as far as I can tell

**Comment by krestenlaust** [comment]
Yes, only the owner can change topics and other meta configuration for the repository

**Comment by dessalines** [comment]
K, these are added now.

**Comment by krestenlaust** [comment]
Damn, 3 weeks worth of inbox. Lemmy development contributions has really blown up
