### ISSUE TITLE
Have link to Legal / Privacy policy.

### ISSUE THREAD

**Issue by ogre-about-town** [dessalines/jerboa#729]
- [ ] Did you check to see if this issue already exists?
- [ ] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

Please consider alerting new users that their upvotes and downvotes are publicly federated.  It is just the way that Lemmy works, and not a Jerboa problem per se, but it would be nice for the user experience if this was communcated on the Jerboa end.  

Perhaps the very first time an account votes, a small tool tip could appear with a message similar to:

-  "This is your first time voting!  Please be aware that your votes are publicly associated with your account, and can be seen by other users" 

Or some better message, just as long as it's clearly communicated.

**Comment by beatgammit** [comment]
Or perhaps a larger "Lemmy FAQ" available somewhere on the sidebar to cover things like this, as well as a list of features the app has.

**Comment by ogre-about-town** [comment]
An easily found and digested FAQ is a must as well, I totally agree.  I do think that tool tips can be super useful for onboarding new users though, especially to communicate privacy concerns.  Unfortunately, a toooooon of users will never click on a FAQ or feature list, even if you put it right in front of them on login.   If you can pop a short, easily understood tool tip the first time users do <insert function>, that can go a long way towards both training new users and keeping them informed.  Not for every little feature or function of course, so that they don't feel spammed, but maybe just for a handful of most-used features.

**Comment by krestenlaust** [comment]
Could the argument be made, that this would cause the Streisand-effect? Right now, I don't know of any clients that allows one to view individual votes. It's not like it can be used for nefarious purposes when it's only available to the few.

**Comment by dessalines** [comment]
Privacy / Legal sections are in the site, but we could add a page for that specifically. I'll rename this issue.
