### ISSUE TITLE
Feature Request: Material You Themed Icon for the App

### ISSUE THREAD

**Issue by KelvinCrag** [dessalines/jerboa#732]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

Material You themed icon is a design language developed by Google, and it's widely used in many popular apps. It uses monochrome layout following the system theme.

**Comment by seamuslowry** [comment]
Already added in #528
