### ISSUE TITLE
Blur Effect doesn't work on old Android version 

### ISSUE THREAD

**Issue by Xanvial** [dessalines/jerboa#733]
** Jerboa Version **
0.0.34

**Describe the bug**
In Android version lower than 12, the blur nsfw picture doesn't work at all. 

**To Reproduce**
0. Use Jerboa on Android version 9
1. Go to instance that has nsfw post
2. Scroll down to any post with nsfw picture 
3. See that it shows plain image instead of blurred image

Note that it doesn't happen on latest version of Android. Most likely caused by using blur from jetpack compose in here https://github.com/dessalines/jerboa/blob/145d04aaab7af3ef8a11528b4e261efdd8951f38/app/src/main/java/com/jerboa/ui/components/common/PictrsImage.kt#L103
This function only works on Android 12 and above based on the documentation https://developer.android.com/reference/kotlin/androidx/compose/ui/Modifier#(androidx.compose.ui.Modifier).blur(androidx.compose.ui.unit.Dp,androidx.compose.ui.unit.Dp,androidx.compose.ui.draw.BlurredEdgeTreatment)

**Comment by sockenklaus** [comment]
Hell thanks for finding this issue, I thought I was going insane.

This Compose library could solve this issue:

https://github.com/skydoves/Cloudy
