### ISSUE TITLE
Render Markdown Tables

### ISSUE THREAD

**Issue by ElenaRgC** [dessalines/jerboa#742]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

Jerboa can't render Markdown tables, here is a comparison with a web broser on the same phone.

![Screenshot_2023-06-18-16-16-41-637_com.jerboa.jpg](https://github.com/dessalines/jerboa/assets/95099947/e8066a94-1b55-4bec-91dc-a910e93b7dd8)

![Screenshot_2023-06-18-16-16-35-896_com.brave.browser.jpg](https://github.com/dessalines/jerboa/assets/95099947/bacc0934-7c0b-4205-bb06-1870de3b12e4)

As you can see, the titles and links are rendered properly but tables aren't.

**Comment by MV-GH** [comment]
https://github.com/dessalines/jerboa/assets/67873169/dd0ec28c-137b-44ae-813d-63e74816fd13

That feature is already in main but the links didn't work in tables. So I'm making a pr that fixes those
