### ISSUE TITLE
Randomly, while opening a link to a thread, it will throw an error on Android

### ISSUE THREAD

**Issue by aaronwi** [dessalines/jerboa#747]
** Jerboa Version **
0.0.34

**Describe the bug**
The comment thread will not load and display briefly
"Value <html> of type java.lang.String cannot be converted to JSONObject"

**To Reproduce**
Go to default feed that loads and click any thread

**Comment by twizmwazin** [comment]
As far as I can tell this happens when the server returns an error that isn't valid json data, and the error handling needs to be improved.

**Comment by MV-GH** [comment]
Error handling message has been improved
