### ISSUE TITLE
While typing in the app, spaces between words get deleted when pressing backspace repeatedly

### ISSUE THREAD

**Issue by Frank-The-Healer** [dessalines/jerboa#748]
**App Version**
I have seen this on Jerboa app version 0.0.33 and 0.0.34 . 

**Description of Issue**
I have seen this several times while typing comments, post titles and even URLs in post submissions. As I am typing, if I press backspace repeatedly, it causes the spaces between words to disappear even if the cursor is not there. Very frustrating as if I notice a typo a few words previous, then I will hit backspace repeatedly to get back to where the typo is, but doing so will remove all the spaces between the last several words. This bug has been reported by several users on the Jerboa community on Lemmy (https://lemmy.ml/post/1318193). I have also experienced this since I started using Jerboa last week. I am using a Fairphone 3 with Android 9 and have seen this bug with Jerboa version 0.0.33 and 0.0.34 . I have also taken a screen recording of my phone to demonstrate the issue. The video is here (https://streamable.com/cxme5q)

**To Reproduce**
1) Enter the Jerboa for Lemmy App
2) Begin to type a comment on a post. 
3) Once several words have been typed out, repeatedly press backspace. 
4) The spaces between words will disappear.

**Comment by MV-GH** [comment]
I have not been able to reproduce this yet. What locale and keyboard are you using?
