### ISSUE TITLE
Officially use a single translation tool for managing translation / localization (Crowdin / Weblate)

### ISSUE THREAD

**Issue by krestenlaust** [dessalines/jerboa#754]
Translating strings and starting a new language is cumbersome, because you need to translate all tokens alone at once, to have it properly submitted.

Crowdin is a great platform, which I have a lot of experience with as a translator. They provide their services for free for open-source projects: https://crowdin.com/page/open-source-project-setup-request.

**Comment by twizmwazin** [comment]
There has also been some discussion in using weblate: https://weblate.org/en/

**Comment by krestenlaust** [comment]
The other lemmy projects are using weblate as well, it would make sense to make it the same. I like that weblate is libre as well

**Comment by xmgz** [comment]
https://weblate.join-lemmy.org  is the main project translation platform, should it be an issue for **the official lemmy app** be hosted there too.


thank you for opening this issue, I'm translator for lemmy and (now defuct) lemmur

**Comment by dessalines** [comment]
For rn at least, just do PRs to the strings.xml like the other ones.
