### ISSUE TITLE
Backwards compatible locale / language selection

### ISSUE THREAD

**Issue by krestenlaust** [dessalines/jerboa#755]
**Proposed problem:**
The PR #609 resolved support for locale selection, but only for android 13. I believe it's an oversight as Android 13 adoption percentage is only at ~12% as of April ([source](https://www.androidcentral.com/apps-software/android-13-distribution-report)), and many phones won't get the update (anecdotal; mine).

**Proposed solution:**
Query language option stored in profile, and select that language.

**Alternate solution:**
Adding an option in the menus to change language for phones not supporting API level 13, would be a great solution. It would also allow a redirect to the settings menu for Android 13 users looking for language change option.

**Context:**
It is of my understanding, that the current implementation just uses the main language configured in Android.

**Comment by twizmwazin** [comment]
IMO we should have a setting to just change the language across the entire app. Android has APIs we can use that will keep it consistent before and after Android 13: https://developer.android.com/guide/topics/resources/app-languages#api-implementation

Adding a feature to prompt the user on login if they want to change the app's language to match their Lemmy language could be added later.

**Comment by seelebrn** [comment]
A small plea to consider users with old phones who can't update to android 13 indeed.

**Comment by tibert01** [comment]
I'm on android 13 (oxigen os 13), and I have no idea how tk change the language.

Using the github 0.35 version, and I have no option for changing the app language from the app setting.

**Comment by twizmwazin** [comment]
https://support.google.com/android/answer/12395118?hl=en

**Comment by tibert01** [comment]
Yep, the official way, but as expected there is no such setting for Oxygen os 13...

**Comment by carlomorelli** [comment]
Upvoting this. I just updated to 0.0.35 and the app jumped from English to the os setting (which definitely not everybody appreciates) with no option to revert to English. A global or user setting allowing to choose the language is the way to go.
