### ISSUE TITLE
Adding clipboard access to long press context menu

### ISSUE THREAD

**Issue by Snapz54** [dessalines/jerboa#759]
- [YES] Did you check to see if this issue already exists? 
- [YES] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [NO] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **
Majority of comparable apps will show a "clipboard" option in the long press context menu in text input boxes (specifically Samsung in my case). Currently, the only option I see is "paste" when box is empty.

**Comment by twizmwazin** [comment]
Can you provide a screenshot or example of what other apps do?

**Comment by Snapz54** [comment]
@twizmwazin here's an example screen from Google Messages app - long press in text input box brings up "clipboard" in context menu. Click brings up an overlay on bottom half of screen with last 15-20 clipboard items (example is from a stock Samsung device running Android 9 and One UI 1.0)

**Comment by twizmwazin** [comment]
Interesting. I have google messages on a pixel 5 with Android 13 and I do not get this option. Perhaps this is a Samsung specific feature?

**Comment by Snapz54** [comment]
@twizmwazin Maybe... My uneducated guess was that there might have been a somewhat universal call for the feature at this point? I can say, for example, that not all of the Reddit clients I'd used had that feature initially, but eventually all but one added it quietly - Maybe it is Samsung specific, but they just get prioritized in some development because of their market share? Not sure.

**Comment by dessalines** [comment]
This exists now.

**Comment by Snapz54** [comment]
Awesome, appreciate your effort!
