### ISSUE TITLE
Red error text visible on some scroll conditions

### ISSUE THREAD

**Issue by MV-GH** [dessalines/jerboa#761]
**Jerboa Version**
latest from main

**Describe the bug**
An red error text appears 

**To Reproduce**
Its not consistently but if a refresh fails it shows a red text error text but only if you scroll up
I think its displaying the errors. this is probably a cut off from "Value of type java.lang.String cannot be converted to JSONObject" error.

https://github.com/dessalines/jerboa/assets/67873169/481fe77a-17a1-4d80-b83f-6b5a7e3ca75f

This doesn't seem to be happening only here

comments
![studio64_nIDUthZzey](https://github.com/dessalines/jerboa/assets/67873169/9687762c-415a-4e36-9d85-48e983c3f17a)
profile
![studio64_iHqLQ0smCH](https://github.com/dessalines/jerboa/assets/67873169/4d1daa52-25f3-4c6b-86ab-980666298480)

**Comment by MV-GH** [comment]
```kt
@Composable
fun ApiErrorText(
    msg: Throwable,
) {
    msg.message?.also { Text(text = it, color = MaterialTheme.colorScheme.error) }
}
``` Due to this, this is a change in behaviour imo it should display a toast again

**Comment by dessalines** [comment]
Fixed.
