### ISSUE TITLE
A proper unread replies tab to allow "inbox zero"

### ISSUE THREAD

**Issue by Snapz54** [dessalines/jerboa#770]
- [YES] Did you check to see if this issue already exists?
- [YES] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [NO] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **
A tab with unread messages/replies only in the Messages inbox from the menu bar. Would be the default inbox view with only any unread messages listed. Messages would auto clear after reading so that you can achieve an empty inbox when caught up.

**Comment by MV-GH** [comment]
Isn't that how it currently works right now?
