### ISSUE TITLE
Scroll to top

### ISSUE THREAD

**Issue by ZJouba** [dessalines/jerboa#771]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **
Scroll to top button
https://medium.com/@gsaillen95/how-to-create-a-jump-to-top-feature-with-jetpack-compose-2ed487b30087
![ScrollToTop](https://github.com/dessalines/jerboa/assets/42601911/587958cf-08fa-4bb1-a678-6c7b7e46643a)

**Comment by MV-GH** [comment]
related #1094

**Comment by dessalines** [comment]
Dupe of above.
