### ISSUE TITLE
Missing server

### ISSUE THREAD

**Issue by gunysa1** [dessalines/jerboa#772]
**Jerboa Version**
0.0.34

**Describe the bug**
Can't see or connect to: lemmy.dbzer0.com

**To Reproduce**

**In the case of a crash**

Please include the logs.
See [this post](https://android.stackexchange.com/questions/14430/how-can-i-view-and-examine-the-android-log) to get the logs.
`adb logcat com.jerboa` Should give you the relevant logs.

**Comment by Popkornium18** [comment]
Not all lemmy instances are part of the dropdown menu. Does it also not work if you manually specify `lemmy.dbzer0.com` as the instance?

**Comment by gunysa1** [comment]
It didn't yesterday, it does today.
Thx
