### ISSUE TITLE
Add sorting order on 'Saved' page to sort by date they were saved

### ISSUE THREAD

**Issue by bappitybup** [dessalines/jerboa#780]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **
This is only a suggestion for an extra sorting option when viewing the saved page (if it is possible on Lemmy) to sort posts by the date they were saved. This would prevent confusion if someone adds a saved post and doesn't see it at the top of the feed, thinking it wasn't added.

**Comment by MV-GH** [comment]
I think it already does that by default

```kt
 personProfileViewModel.getPersonDetails(
            GetPersonDetails(
                person_id = personId,
                username = personName,
                sort = SortType.New,
                saved_only = savedMode,
                auth = account?.jwt,
            ),
        )
```
