### ISSUE TITLE
Bottom panel has duplicated "search". 

### ISSUE THREAD

**Issue by jy-r** [dessalines/jerboa#787]
** Jerboa Version **
0.0.34

** Describe the bug **
For me, bottom panel has "Home", "Search" (which controls communities), "Inbox", "Search" (which seems to be related to saved posts) and "Profile". I think both of the "Search" buttons should be renamed to "Communities" and "Saved" retrospectively.

**Comment by sockenklaus** [comment]
This is a duplicate of #604, #653, #675, #741, #757 and has been fixed in #608.
