### ISSUE TITLE
Setting default values for filter and sorting inside the app.

### ISSUE THREAD

**Issue by jy-r** [dessalines/jerboa#788]
** Describe the feature request below **

Ability to set different default values for sorting and filter for the Home. Currently, when the app is opened the sorting is set to "Active" and filter to "Local".

**Comment by Snow4DV** [comment]
There's already such settings. It can be set either on the lemmy instance's site or here in profile settings in the app


![Screenshot_2023-06-21-10-54-03-40_a10f969cf1c4adf2c503042b459b8476](https://github.com/dessalines/jerboa/assets/32912696/087230b3-bc35-4308-bfb2-9140fbd108b0)
