### ISSUE TITLE
Back button disabled in login page when adding first account.

### ISSUE THREAD

**Issue by IchbinLuka** [dessalines/jerboa#789]
**Jerboa Version**
Commit b8e0dfb on the main branch. 

**Describe the bug**
When first logging in the "back" button in the top left corner is disabled. 

From the code it seems like this is intentional:

```kotlin
IconButton(
    enabled = !accounts.isNullOrEmpty(), // Removing this line would solve the problem
    onClick = {
        navController.popBackStack()
    },
)
```

Please correct me if I am mistaken, but I don't really see why it should be disabled since you can still use the android back button.

**To Reproduce**

1. Ensure that no accounts are added to the app
2. Click on the Hamburger Menu in the top left corner
3. Add an account
4. The button in the top left corner with an "arrow_back" icon will be disabled

**Comment by MV-GH** [comment]
Fixed in #1040
