### ISSUE TITLE
Create account first poppup is unclickable

### ISSUE THREAD

**Issue by Schoolkid1** [dessalines/jerboa#793]
- [ x] Did you check to see if this issue already exists?
- [ x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

When you press certain actions (e.g. create post) there is a pop-up with create account first. I like to make this pop-up a clickable image. In combination with adding a feature to create an account in-app I think this would be a great school project to work on for me.

Device: Oppo A78
Software: Android 13

Screenshot of the example below:
![First login](https://github.com/dessalines/jerboa/assets/119050023/adf77342-49b2-4636-ae3b-23cd45fdfc4d)

**Comment by MV-GH** [comment]
The pop up is a toast, and are not clickable, if you want to make them clickable you will probable have to switchover to a snackbar or a use a custom toast. But we currently don't have a consensus on this behavior (what to do with non logged in accounts). As #765 is introducing to instantly navigate to login on certain buttons.
