### ISSUE TITLE
Add "Copy text" option to all posts and comments

### ISSUE THREAD

**Issue by painkiller1717** [dessalines/jerboa#796]
- [x] Did you check to see if this issue already exists?
Yes
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
Yes
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa
No, is a request to better accessibility.

** Describe the feature request below **

I would like it that all text fields, could being capable of copy the text inside of them
I would like to be able to copy the texts of all fields, to be able to translate them outside the app with _**DeepL**_ or _**Translate You**_, for example. Something like the _View Source_ button in the comments to be able to select, because without this the text could not be copied.

I attach an image of an example that does not allow you to copy the text by clicking on it, nor does it have the _View Source_ button.

I would attach a picture of an example, but I'm in GitHub app and I can't.

**Comment by painkiller1717** [comment]
![IMG_20230621_145940.jpg](https://github.com/dessalines/jerboa/assets/77559296/1718ee7a-a38d-49b3-9079-294a74b465ed)

Here an example.

**Comment by tarunsamanta2k20** [comment]
Do you want to enabling selecting tesr functionality or adding a copy button?

**Comment by CharlieGitDB** [comment]
Would adding it to the context menus work?

>  <img width="322" alt="Screen Shot 2023-06-21 at 8 55 04 PM" src="https://github.com/dessalines/jerboa/assets/17328118/cf80f8d2-dd52-4982-85ec-b9b4efa25a1f">

**Comment by FilippoVigani** [comment]
I think we can close this, as view source as been added in [0.38.0](https://github.com/dessalines/jerboa/releases/tag/0.0.38) (#901). Can you confirm this? @MV-GH

**Comment by MV-GH** [comment]
Indeed
