### ISSUE TITLE
Hangs on login

### ISSUE THREAD

**Issue by N-Upchurch** [dessalines/jerboa#80]
When attempting to login, the loader animation appears on the button and nothing happens. I have tried both username and email. 

**Details:**
Server: lemmy.ml
Device: OnePlus 3T
Android Version: 9

I am also using a password manager (KeePass DX) to autofill credentials.

**Comment by dessalines** [comment]
I also use keypass DX, but copy and paste method. Try doing that, or making a dummy account on lemmy.ml with a simple password to verify that its the app.
