### ISSUE TITLE
Markdown tables not rendering in app

### ISSUE THREAD

**Issue by benja810** [dessalines/jerboa#804]
**Jerboa Version**
0.0.34

**Describe the bug**
Markdown tables are not rendered on Jerboa but do render correctly in app. 

**To Reproduce**

Visit:
https://fanaticus.social/post/47372

In Jerboa:
![Screenshot_20230621-182219](https://github.com/dessalines/jerboa/assets/105392370/289856ce-8419-4f0f-a787-0e16d3b571d0)

On Firefox Mobile:
![Screenshot_20230621-182134](https://github.com/dessalines/jerboa/assets/105392370/4ae695e6-e2ee-4b70-b366-1fc8d8308db4)

**Comment by benja810** [comment]
Looks like this is already fixed on main. Sorry I was looking at open issues only!

https://github.com/dessalines/jerboa/pull/744

**Comment by KaKi87** [comment]
Hello, I'm experiencing this issue despite running v0.0.39, what am I missing ? Thanks

**Comment by MV-GH** [comment]
![IMG_20230920_200042.jpg](https://github.com/dessalines/jerboa/assets/67873169/f1bc5280-2235-4260-aab8-270ab128bddf)


Idk, it works, must have used a version that did not have those changes yet
