### ISSUE TITLE
Refactor CommunityViewModel, HomeViewModel, InboxViewModel, PersonProfileViewModel

### ISSUE THREAD

**Issue by MV-GH** [dessalines/jerboa#807]
The VMs: CommunityViewModel, HomeViewModel, InboxViewModel, PersonProfileViewModel all have significant duplicated code such as the pages, posts ... We should refactor that into a ancestor called something like PostsViewModel containing that code.

**Comment by dessalines** [comment]
This one is done, at least for Home and Community

**Comment by MV-GH** [comment]
Most of these changes are still sitting in my draft PR for search expansion. I'll extract them into separate PRs. Atm we still have significant duplicate code that needs to be addressed
