### ISSUE TITLE
Option to not use Chrome Custom Tabs for opening links

### ISSUE THREAD

**Issue by jgeorgeson** [dessalines/jerboa#808]
- [ x] Did you check to see if this issue already exists?
- [ x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

Using a Chrome Custom tab means every link the Jerboa opens "internally" is now part of my Chrome history. If I want to save the posts/comments/links, I can use the built-in bookmark/save feature of Lemmy. If I want to have it in my Chrome history, I can select _Open in Chrome_ from the triple-dot menu. 

Making this a toggle between using an embedded WebView, or perhaps the Chrome Custom Tab can be an incognito tab.

**Comment by twizmwazin** [comment]
There is already an option to use an incognito tab if you custom tabs provider allows it. It is under the "look and feel" section, which I know isn't particularly intuitive. It is also poorly supported, chrome is the only browser that advertises any kind of support and you have to enable a flag to get it, and even then I'm not sure that it works all of the time. Maybe try it though until we have a better implementation.

**Comment by jgeorgeson** [comment]
I don't seem to have that option. Is it new in v0.0.34? I'm still on v0.0.33, and only have an option for "Use custom tabs" which is enabled. Disabling it opens all links in Chrome proper rather than an embedded Custom tab. My phone is running Android 13 build TQ2A.230505.002.A1 with Chrome v114.0.5735.130.

**Comment by twizmwazin** [comment]
It is on main but seems like it hasn't been released yet.

**Comment by dessalines** [comment]
Done.
