### ISSUE TITLE
Can't mark a notification as read

### ISSUE THREAD

**Issue by suoko** [dessalines/jerboa#814]
I remember I could set a single notified message as read, while now I can only mark as read all messages together

**Comment by beatgammit** [comment]
I'm guessing you're running into the issue where the action bar buttons aren't showing below messages. See [this post](https://sh.itjust.works/comment/218637).

If they are showing, you need to find the icon that looks like a speech bubble with a little dot at the bottom right.

**Comment by suoko** [comment]
Long pressing next to the username enables the botton bar.

**Comment by suoko** [comment]
Closed
