### ISSUE TITLE
(German Translation) Ugly line break in bottom Navbar 

### ISSUE THREAD

**Issue by sockenklaus** [dessalines/jerboa#818]
**Jerboa Version**
main branch

**Describe the bug**
The words "Posteingang" and "Lesezeichen" have ugly line breaks. 

This happens on my OnePlus 5t.

* Size: 6.01 inch
* Resolution: 2160 X 1080.

See:
![Screenshot_20230622-175700__01](https://github.com/dessalines/jerboa/assets/870042/ae43bdd1-a35c-4bef-a23c-9c137846f873)

I'll try to look into this later this evening. Maybe it's enough to adjust the padding of those buttons.

Is there any lower resolution limit Jerboas GUI has to work flawlessly?

**Comment by andreaippo** [comment]
A similarly ugly screenshot:

https://lemm.ee/post/238562

**Comment by Aloso** [comment]
Same issue here. Please use an ellipsis ("Posteing...", "Lesezei...") when the text doesn't fit in one line.

**Comment by sockenklaus** [comment]
Truncating and wrapping text in NavigationBars is discouraged by Material.io guidelines:

https://m3.material.io/components/navigation-bar/guidelines

I'd really like to try how it looks with reduced padding between icons but I feel we have to completely rewrite the component because I've found no way to inject smaller padding with modifiers.

Another idea could be to not use labels at as the icons are pretty descriptive in itself.

**Comment by Aloso** [comment]
> Truncating and wrapping text in NavigationBars is discouraged by Material.io guidelines

so, what's the alternative? I don't see any _actionable_ advice, besides coming up with a shorter label, but that is difficult.

- Instead of _Posteingang_ (inbox), we could use _Postfach_ (mailbox / post office box), which is shorter but less descriptive.

- Instead of _Lesezeichen_ (bookmarks), we could use _Gemerkt_ (remembered / bookmarked), or _Favoriten_ (favourites), but then the app uses different terminology than the web app, which might confuse people.

And this solves the problem for German, but not for other languages.

**Comment by Aloso** [comment]
Also, I noticed that the label font size in Google Drive is smaller than in Google Photos. So even though it's discouraged to make a label smaller to fit the text, it is apparently OK to make _all_ labels smaller by the same amount.

**Comment by andreaippo** [comment]
I'm 

> Also, I noticed that the label font size in Google Drive is smaller than in Google Photos. So even though it's discouraged to make a label smaller to fit the text, it is apparently OK to make _all_ labels smaller by the same amount.

I'm no Android dev so I'm not familiar with their design guidelines, but from a user perspective it would seem very off and low quality to have just one label smaller.
Rephrasing things (sometimes losing part of their meaning) just to make them fit also seems a subpar solution to the problem to me. I'd definitely regard the smaller labels for all solution as the more elegant and consistent one here.

**Comment by sockenklaus** [comment]
> I'm no Android dev so I'm not familiar with their design guidelines, but from a user perspective it would seem very off and low quality to have just one label smaller. Rephrasing things (sometimes losing part of their meaning) just to make them fit also seems a subpar solution to the problem to me. I'd definitely regard the smaller labels for all solution as the more elegant and consistent one here.

I think we're all on the same page regarding resizing only the labels that are too long. That's pretty much off the table.

I think making all labels smaller is something that can be tested but I'm wondering whether this is something we can implement per language because I see no reason to make English labels smaller and therefore lessen their readibility because we Germans and Italians have issues with labels that are too long.

**Comment by suoko** [comment]
Add the possibility to show icons only and we're done

**Comment by Sir-Photch** [comment]
Yeah, this is pretty rough. At first, it's probably easiest to just add an option to just show the icons.
