### ISSUE TITLE
Taglines rendering over content on the Home page

### ISSUE THREAD

**Issue by Generator** [dessalines/jerboa#821]
**Jerboa Version**
v0.0.35-alpha

Android: 13 (AOSP)

**Describe the bug**
Render issues with instance header overlapping text.
Instance: lemmy.pt

**To Reproduce**

1. Login
2. Scroll!

**Screenshot**

![screen](https://i.imgur.com/2s1VZNK.jpg)

**Comment by MV-GH** [comment]
Is that consistent everywhere ?

**Comment by MV-GH** [comment]
Is that because the title is way to long, and it should clip the title instead?

**Comment by Generator** [comment]
@MV-GH it shows on subscribed/local/all

**Comment by MV-GH** [comment]
can you link the post? what i mean is that does it do that for all posts

**Comment by Generator** [comment]
Isn't a post, it's the "Home" on lemmy.pt

**Comment by Generator** [comment]
@MV-GH on https://enterprise.lemmy.ml/ set a long text where it says "tagline 2"
open Jerboa with enterprise.lemmy.ml account

Here's a video  

https://github.com/dessalines/jerboa/assets/44146/c62d3994-5716-40a6-a654-a577c3d34936

**Comment by MV-GH** [comment]
caused by this code

```kt
    when (val siteRes = siteViewModel.siteRes) {
        ApiState.Loading ->
            LoadingBar(padding)

        ApiState.Empty -> ApiEmptyText()
        is ApiState.Failure -> ApiErrorText(siteRes.msg)
        is ApiState.Success -> {
            // TODO can be removed with 0.18.0 release
            if (siteRes.data.taglines !== null) {
                Taglines(siteRes.data.taglines)
            }
        }
    }
``` 
In homeActivity

@dessalines     What is needed for? I think we shouldt display the tagline in the feed at all, should only display in the community.

**Comment by dessalines** [comment]
Taglines are a server-wide thing, so should only be on the Home page. I'll change the title on this to reflect the bug.

**Comment by Generator** [comment]
Forgot to say, im on Android 13.
You should add that to the issue template

**Comment by beatgammit** [comment]
Should this be like a "post" that stays above the top post, or a sticky that's expendable as needed?

I'm thinking some kind of notification bar with a clipped version of the text that links to instance info.
