### ISSUE TITLE
Maintain previous home configuration

### ISSUE THREAD

**Issue by svprdga** [dessalines/jerboa#822]
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [X] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

Normally, whenever I browse this application, I do so in the communities to which I have subscribed, ordered by the newest.

However it seems that these settings are not being saved in the user preferences, so when the app dies and is started again the default settings are restored.

I think it would be good to store both the type of threads you want to see, as well as their ordering so that when you reopen the application from a cold start it respects the configuration that the user had previously configured.

**Comment by twizmwazin** [comment]
Just tested this on 0.0.35, it seems like while the settings are saved correctly, they are not respected on the home view.

**Comment by svprdga** [comment]
I've cloned the source code to try to fix it myself, but I'm seeing that the `main` branch only works with version `0.18`. How do you do it to debug? Do you run a local instance of `0.18`?

**Comment by twizmwazin** [comment]
voyager.lemmy.ml is a good place to debug.

**Comment by dessalines** [comment]
There are *some* global app settings, but for everything that's server based, account switching should reload those settings.
