### ISSUE TITLE
Does not work on new phones

### ISSUE THREAD

**Issue by Hristo1199** [dessalines/jerboa#823]
**Jerboa Version**
Type the version from the settings here.
0.0.33
**Describe the bug**
Does not open
**To Reproduce**
Umm poco x3

**In the case of a crash**
Phone does not allow me to see logs

Please include the logs.
See [this post](https://android.stackexchange.com/questions/14430/how-can-i-view-and-examine-the-android-log) to get the logs.
`adb logcat com.jerboa` Should give you the relevant logs.

**Comment by MV-GH** [comment]
0.33 0.34 will crash on startup as lemmy.ml has upgrade to 0.18 which Jerboa doesn't support into those version, I recommend downloading the 0.35 apk from the release

**Comment by Hristo1199** [comment]
Thx
