### ISSUE TITLE
Opening Inbox shows all messages (read/unread)

### ISSUE THREAD

**Issue by Generator** [dessalines/jerboa#824]
**Jerboa Version**
v.0.0.35-alpha

Android: 13 (AOSP)

**Describe the bug**
When opening Inbox always shows all messages both  read and unread.   
Need to filter "unread" to show only unread messages.  
This happens even without unread messages.

Instance: lemmy.pt 
BE: 0.18.0-rc.5

**To Reproduce**

1. Mark all message as read
2. Re-open Inbox

**Comment by MV-GH** [comment]
Fixed with #1007
