### ISSUE TITLE
Post scrolling issues

### ISSUE THREAD

**Issue by Generator** [dessalines/jerboa#825]
**Jerboa Version**
v0.0.35-alpha

Android: 13 (AOSP)

**Describe the bug**
Some posts with embed images it's impossible to scroll up after reaching the bottom 

**To Reproduce**

1. Go to https://lemmy.pt/post/453555
2. Scroll all to botton
3. Scroll down back up

Video:  

https://github.com/dessalines/jerboa/assets/44146/34566ac7-cf70-4248-a299-b1a68ceb9b69

**Comment by shodanx2** [comment]
It may or may not be related, but I also noticed a scrolling related bug. 
While scrolling sometimes images will jump up and down like a flicker while scrolling.

**Comment by twizmwazin** [comment]
@shodanx2 This was known in 0.0.33, has it happened for you in newer versions?

**Comment by shodanx2** [comment]
I will let you know once 0.0.33 is available on fdroid. For now I have only tried with 0.0.32
