### ISSUE TITLE
Show presence of unread message when there are none left

### ISSUE THREAD

**Issue by shodanx2** [dessalines/jerboa#828]
**Jerboa Version**
0.032

**Describe the bug**
Show presence of unread message when there are none left
This clears by killing the app and restarting it

**To Reproduce**
Don't know, happens occasionnaly

Please include the logs.
Unable to copy logs from phone to PC

**Comment by beatgammit** [comment]
We really should be smarter about this. I'm guessing some shared state isn't getting refreshed properly.

**Comment by MV-GH** [comment]
Fixed with #1007
