### ISSUE TITLE
Long press and image, video and other embed content should open context menu

### ISSUE THREAD

**Issue by shodanx2** [dessalines/jerboa#829]
Long pressing an image in most application brings up a context menu

with options like 
copy link
copy image
share link 
share image

Personnally I always click share image and paste to my friends private chat (as opposed to posting link, which will break eventually)

It would be nice to also have "copy video" "share video" but that's probably too advanced technology for android

**Comment by MV-GH** [comment]
see #651

**Comment by shodanx2** [comment]
Yes this but not just links and download but 

copy image 
share image 

copying to clipboard, not just the link, but the actual content

extra 1

link to image vs link to associated post

extra 2

also support video
copy video
share video

Extra 3

Support media other than images (video, STLs, audio files, excel, .txt etc.. ) , should be format agnostic, a file is a file

**Comment by shodanx2** [comment]
Example
![Screenshot_20230622-175124](https://github.com/dessalines/jerboa/assets/10621885/4fe60793-75e8-4314-8df4-6bbc995616ef)

**Comment by shodanx2** [comment]
I've just got the update !
Thank you thank you thank you thank you

![Screenshot_20230909-183741](https://github.com/dessalines/jerboa/assets/10621885/9b431028-baf0-424a-9bcd-98ceb1c87da1)
