### ISSUE TITLE
Organize settings page

### ISSUE THREAD

**Issue by jordan1776** [dessalines/jerboa#840]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

On 0.0.35 , it seems that the 'Look and Feel' settings page is getting fairly long with many unrelated options. I propose that the page get split up (or at the least have headered groups of options). This probably should be setup sooner than later so new settings get placed where appropriate.

**Comment by twizmwazin** [comment]
I highly agree, I'm guilty of some of the settings that don't really belong there, it was just convenient to get the feature implemented without further refactoring. I think it would be a good idea to try and plan what settings we want to support in the near future and sketch out a layout based on that. It would allow us to enumerate a whole bunch of relatively easy tasks that contributors could check off independently.

**Comment by beatgammit** [comment]
Yes please. And fix scrolling while we're at it.

**Comment by sockenklaus** [comment]
I have two suggestions for better user experience on the settings page:
1. Replace the current save button either with a save button in to top bar or with a FAB. I think I'd prefer a button in top bar. It's tedious to scroll down to the bottom to save the settings.
2. After saving the settings transition somewhere or at least display a toast message that the settings have been saved successfully. At the moment you don't get any useful whether settings have been saved or not.

**Comment by nahwneeth** [comment]
> After saving the settings transition somewhere or at least display a toast message that the settings have been saved successfully. At the moment you don't get any useful whether settings have been saved or not.

Linking #886 as related.

**Comment by dessalines** [comment]
Stale issue, but if someone wants to work on this, I can re-open.
