### ISSUE TITLE
Screen position auto-shift when inputting comment text

### ISSUE THREAD

**Issue by Snapz54** [dessalines/jerboa#841]
**Jerboa Version**
0.0.34

**Describe the bug**
When entering comment text in input box text eventually falls behind keyboard and obscures view of message.

**To Reproduce**

1. Go to any post
2. Click on reply icon
3. Input lines of text until you fill the visible box on screen

**Comment by beatgammit** [comment]
Yeah, this is annoying.

I wanted to add that we should consider pinning the action bar to the bottom as well, which would be pretty easy to do when redoing this.

**Comment by MV-GH** [comment]
https://issuetracker.google.com/issues/266094055

**Comment by dessalines** [comment]
Not us, but jetpack-compose.
