### ISSUE TITLE
Ability to save comment versions while composing a comment

### ISSUE THREAD

**Issue by takeda** [dessalines/jerboa#842]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **
While working on mobile, and need to type a longer comment. The nature of using a mobile device is that you typically might do something else and might need to put your phone down. Sometimes you might also want to try to edit it, and undo function isn't as popular as on the desktop.

RiF solved that issue, by providing "save" button in the compose window. That writes down what's currently typed. You can also click other button to restore draft and select which saved version you want to use. The saves are also stored even if you cancel composing (this allows to browse to another post/comment if you need to copy something from there).

The drafts are purged once the comment is submitted. Note, the same mechanism is available when updating existing comment.

**Comment by beatgammit** [comment]
Dup of #356.

I also coincidentally have this nearly completed, just fixing some issues with deleting and saving comments populating properly.
