### ISSUE TITLE
open YouTube links with specific app

### ISSUE THREAD

**Issue by Buchhems** [dessalines/jerboa#847]
One should be able to choose the desired YT app like Newpipe, YT Rev. or the original app in the settings.
Then when a YT link is clicked the app will open the chosen YT app.

**Comment by Eeyoresyndrome** [comment]
> One should be able to choose the desired YT app like Newpipe, YT Rev. or the original app in the settings. Then when a YT link is clicked the app will open the chosen YT app.

That could be more up to your app settings.
My links open in Newpipe, because I have it set to open YouTube links etc in its own app settings.

![Screenshot_20230625-012005](https://github.com/dessalines/jerboa/assets/20648889/87b53b9a-c744-48a4-be74-6c0b69b67c93)

**Comment by dessalines** [comment]
See above.
