### ISSUE TITLE
Jerboa wants Lemmy 0.18 which isn't released

### ISSUE THREAD

**Issue by jonsparks** [dessalines/jerboa#851]
**Jerboa Version**
0.0.35-alpha

**Describe the bug**
App throws an error on launch asking for a newer version of Lemmy server. I'm currently running 0.17.4 which is the latest release on https://github.com/LemmyNet/lemmy. App should not be ahead of the Lemmy releases, I'm certainly not updating my instance to a beta RC.

**To Reproduce**
Update to latest app version and connect to literally any Lemmy server aside from lemmy.ml.

**In the case of a crash**

Please include the logs.
N/A

**Comment by MV-GH** [comment]
Lemmy 0.18 is supposed to release today, we did a release yesterday so that it would at least be available already on fdroid

**Comment by beatgammit** [comment]
Released half hour ago. 😄

**Comment by twizmwazin** [comment]
The backwards incompatible changes in Lemmy 0.18 have frustrated a lot of people, myself included. Hopefully the main Lemmy folks will take note of this and avoid breaking the API in the next version, at least allowing one version of backwards compatibility to allow for a smooth transitions for users. Unfortunately there's not much that we can do about it right now, so hopefully this can be a lesson for the next cycle.

**Comment by MJBrune** [comment]
If you can detect the version why not support the other API version? Seems very short sighed to blindly roll forward breaking the app for the majority of users.
