### ISSUE TITLE
Change default server

### ISSUE THREAD

**Issue by beatgammit** [dessalines/jerboa#856]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

Related: #848

**Comment by twizmwazin** [comment]
It might be a good idea to even add "anonymous" accounts that have a server but no credentials.

**Comment by beatgammit** [comment]
I actually have some code that does this, but it has probably bit-rotted by now. Basically, I'd make username and password optional fields when logging in, and those would show up as just the instance name in the account list.

Maybe I'll rework it if I get time this weekend.

**Comment by dessalines** [comment]
A better solution is #1336 . Otherwise, just log in to the server you want.
