### ISSUE TITLE
App crashes at launching on fresh install

### ISSUE THREAD

**Issue by flAmEDIEU** [dessalines/jerboa#859]
**Jerboa Version**

v0.0.35-alpha
v0.0.34-alpha
v0.0.33-alph

**Describe the bug**

App crashes seconds after lauching

**Comment by tibert01** [comment]
I don't have the issue on version 0.35.

However it's downloaded directly from the github, and I also removed all the data and cache before uninstalling the play store version 0.33.

Oxygen os 13.

**Comment by Aevyz** [comment]
Have the same problem. Only started yesterday. What would be the best way of collecting logs for the devs? 

Version 0.0.34 (Fdroid)

Xiao MI Civi 2, Android 12

**Comment by MV-GH** [comment]
0.34 is expected to crash rn, it doesn't support 0.18. Update to 0.35

For the poster, since yours still crashes with 0.35. I will need the logs. see https://android.stackexchange.com/questions/14430/how-can-i-view-and-examine-the-android-log

**Comment by RobertChrist** [comment]
I tried capturing the logs with logcat extreme, but nothing appears in com.jerboa.

I also have this issue

**Comment by MV-GH** [comment]
If your phone isn't rooted there is no otherway.

**Comment by dginovker** [comment]
I was having this issue as well. Updating to the latest release on GitHub fixed it.

**Comment by MV-GH** [comment]
@RobertChrist  Do you have an issue with 0.35 if so can you try this ?

<details><summary>Guide to get logs</summary>


Follow these steps (skip the ones you already have done):
- Enable developer options and USB DEBUGGING
- Install ADB on your PC
- Connect your phone to your PC
- Execute this command on PC

### To enable developer options and USD DEBUGGING

[Follow this article](https://developer.android.com/studio/debug/dev-options)
In essence you find the build number in About section of settings page and tap it a few times
Then open developer options and enable USB DEBUGGING

### Install ADB on your PC

Download ADB from here [https://adbinstaller.com/](https://adbinstaller.com/)

Unzip it

[(Click here if you wanna know more about ADB)](https://developer.android.com/tools/adb)

### Connect your phone to your PC

Use a USB cable to connect your phone to your PC

### Execute this command on PC
On windows open Powershell in the directory with the adb.exe (where you unzipped it, if you didn't add it to the PATH)

On Unix open a shell in the directory with the adb (where you unzipped it, if you didn't add it to the PATH)

To test if this is working type `adb devices`, this should output a device

Then execute this command `adb shell logcat --pid $(adb shell "timeout 5s logcat | sed -En 's/.*com.jerboa.*, PID: (\S*)/\1/p'| tail -1")`
The above command will print the logs of the latest execution of Jerboa (regardless of which version/build).

That should look like something like this.
![example_cmd.png](../../media/example_cmd.png)

Copy the full output. (If not possible just include the few lines below `FATAL EXCEPTION: main` )

Either include it as a file or past it here

```
<details><summary>LOGS</summary>
PASTE HERE AND REMOVE THE ABOVE GUIDE
</details>
```

</details>

**Comment by PurpleCodingWizard** [comment]
In my case it crashes because it cannot access lemmy.ml I tried uninstall but it's the same.  I also discovered that the app cannot be launched when offline. 
![Screenshot_20230624_213020_Market Feedback Agent](https://github.com/dessalines/jerboa/assets/34276732/c19a7c14-6339-487b-abb2-d046781e50dd)

**Comment by MV-GH** [comment]
Can you connect to lemmy.ml from a browser?

**Comment by Apollo3zehn** [comment]
v0.0.35-alpha solves the problem for me

**Comment by IvanyaK** [comment]
Have the same problem.
v0.0.35, Fdroid
Redmi Note 7, Android 10

**Comment by MV-GH** [comment]
> Have the same problem. v0.0.35, Fdroid Redmi Note 7, Android 10

The failed to connect to lemmy.ml or crash on startup on 0.35? If the latter can you post the logs here.

**Comment by IvanyaK** [comment]
> 

Oh, I reinstalled the app and all is well

**Comment by IvanyaK** [comment]
> > Have the same problem. v0.0.35, Fdroid Redmi Note 7, Android 10
> 
> The failed to connect to lemmy.ml or crash on startup on 0.35? If the latter can you post the logs here.

Oh, I reinstalled the app and all is well

**Comment by RobertChrist** [comment]
I uninstalled Jerboa, and reinstalled with the latest on the play store (The about page says version 0.0.35), and the issue disappeared

**Comment by PurpleCodingWizard** [comment]
> Can you connect to lemmy.ml from a browser?

I'm afraid not. I tried the cloud flare 1.1.1.1 app and then it connects successfully.

**Comment by iSaluki** [comment]
This issue occurs for me with the F-Droid version, switching to the Play Store version via Aurora Store fixed the crashing.

**Comment by MV-GH** [comment]
0.35 Was only available yesterday on Fdroid

**Comment by FedericoCeratto** [comment]
Uninstalling and reinstalling multiple times from f-droid did not solve the crash. Installing from google play did.

**Comment by MV-GH** [comment]
Could you get the logs from those crashes?
