### ISSUE TITLE
Adopt single activity pattern?

### ISSUE THREAD

**Issue by sockenklaus** [dessalines/jerboa#865]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **
Jerboa uses multiple activities. The single activity pattern has been around for some time and is promoted by Google as the preferred method to develop apps, especially with Jetpack Compose.

To be honest I don't know anything about multiple activity apps because I never wrote anything with multiple activities, but as far as I understand correctly, single activity apps have some advantages over multiple activity apps.

I.e.:
* simpler transitions between navigation target
* easier to share state between composable than between acitiviey
* easier deep linking with Jetpacks Navigation library

Has anyone experience with the single activity pattern Vs. multiple activities?

**Comment by nahwneeth** [comment]
The current app is a single activity app. Only `MainActivity` extends `Activity`. All the other activities (like HomeActivity, CommunityActivity, etc) are misnomers and are actually composables within the `MainActivity`.

**Comment by sockenklaus** [comment]
Oh thank you for pointing that out, I honestly didn't notice and only went by the filenames. 😶
