### ISSUE TITLE
"please check your spam/junk folder" text floating on top of screen.

### ISSUE THREAD

**Issue by RoosDaniel** [dessalines/jerboa#866]
**Jerboa Version**
0.0.35

**Android version + phone**
Pixel 7 using Android 13

**Describe the bug**
"please check your spam/junk folder" text floating on top of screen. I'm guessing this is related to unverified email addresses somehow.

[Screenshot showing the text](https://imgur.com/a/xPDGnQ0)

**To Reproduce**

1. Go to Home-screen
2. Scroll so that the top-header hides

**Comment by cyberfeign** [comment]
I've seen the same, the introduction/description or whatever of an instance is glitching and stays on top in the background, behind images and text when you scroll.

**Comment by MV-GH** [comment]
I think this is related to #821

**Comment by beatgammit** [comment]
Yes, this should be closed.
