### ISSUE TITLE
2fa support

### ISSUE THREAD

**Issue by burtek** [dessalines/jerboa#867]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

Lemmy UI 0.18 supports 2FA. Once I set it up, I can't login to my Lemmy account anymore from jerboa. Please add support for 2FA

**Comment by dp138504** [comment]
I am seeing the same behavior.
