### ISSUE TITLE
Instance information is displayed in the background

### ISSUE THREAD

**Issue by tibert01** [dessalines/jerboa#878]
**Jerboa Version**
0.0.35-alpha github

**Android version + phone**
Oxygen os 13 - android 13 / OnePlus 8 pro. (language change has not been implemented by the brand) 

**Describe the bug**
The compuverse.uk server information is displayed in the background of all the posts, and follows on the screen. (screenshot : text compuverse.uk is a... At the top) .
The issue wasn't happening on version 0.0.33 play store, before the server updated to 0.18.
(also the French UI is bugged on the oneplus 8 pro) 

![Screenshot_2023-06-24-00-22-29-71_a10f969cf1c4adf2c503042b459b8476](https://github.com/dessalines/jerboa/assets/58490865/b89ca5cb-5f6f-441e-b0b9-c80e32a902b6)

**To Reproduce**
1- Connect to compuverse.uk account. Or another with similar server, with the same text. 
2- start scrolling to see the bug. And text follow.

**Comment by MV-GH** [comment]
Duplicate #821 and is fixed
