### ISSUE TITLE
Improve login form

### ISSUE THREAD

**Issue by sockenklaus** [dessalines/jerboa#879]
**Jerboa Version**
Main

**Android version + phone**
Oneplus 5t, Android 10.1

**Describe the bug**
The login form has some cosmetic and usability issues:

1. The drop-down with suggested instances stays on top of a "change input language"-dialog.
2. Suggested instances don't filter when typing
3. When entering long passwords the password field expands to MaxWidth
4. The CircularProgressIndicator is bigger than the login button. When pressed, the login button resizes twice which looks wonky.

**To Reproduce**

5. Click on '....'
6. Scroll down to '....'
7. See error

**In the case of a crash**

Please include the logs.

<details><summary>Click here if you don't know how to get the logs</summary>

Follow these steps (skip the ones you already have done):
- Enable developer options and USB DEBUGGING
- Install ADB on your PC
- Connect your phone to your PC
- Execute this command on PC

### To enable developer options and USD DEBUGGING

[Follow this article](https://developer.android.com/studio/debug/dev-options)
In essence you find the build number in About section of settings page and tap it a few times
Then open developer options and enable USB DEBUGGING

### Install ADB on your PC

Download ADB from here [https://adbinstaller.com/](https://adbinstaller.com/)

Unzip it

[(Click here if you wanna know more about ADB)](https://developer.android.com/tools/adb)

### Connect your phone to your PC

Use a USB cable to connect your phone to your PC

### Execute this command on PC
On windows open Powershell in the directory with the adb.exe (where you unzipped it, if you didn't add it to the PATH)

On Unix open a shell in the directory with the adb (where you unzipped it, if you didn't add it to the PATH)

To test if this is working type `adb devices`, this should output a device

Then execute this command `adb shell logcat --pid $(adb shell "timeout 5s logcat | sed -En 's/.*com.jerboa.*, PID: (\S*)/\1/p'| tail -1")`
The above command will print the logs of the latest execution of Jerboa (regardless of which version/build).

That should look like something like this.
![example_cmd.png](../../media/example_cmd.png)

Copy the full output. (If not possible just include the few lines below `FATAL EXCEPTION: main` )

Either include it as a file or past it here

```
<details><summary>LOGS</summary>
PASTE HERE AND REMOVE THE ABOVE GUIDE
</details>
```

</details>

**Comment by Douile** [comment]
Also the login fields don't seem to have the attributes required to allow autofill from password managers to work.

**Comment by sockenklaus** [comment]
> Also the login fields don't seem to have the attributes required to allow autofill from password managers to work.

How does this show? I use Keepass to fill the autologin form and it works just fine. Which password manager are you using? I'd like to reproduce this.

**Comment by Douile** [comment]
Weird I'm using KeepassDX and it doesn't show up

**Comment by sockenklaus** [comment]
> Weird I'm using KeepassDX and it doesn't show up

Can confirm. I'm planning to work on the login form but haven't started yet. Maybe I can find a solution your issue.
