### ISSUE TITLE
Translation of content into the native language

### ISSUE THREAD

**Issue by SocialSavvy** [dessalines/jerboa#880]
Twitter has a google translate plugin that translates foreign-language content into the native language. In the picture, it says translate tweet in the marked place. 
![Screenshot_20230625-152352_Twitter](https://github.com/hjiangsu/thunder/assets/107673019/1b413698-f596-4eb1-a81a-95294869a721)
In the picture here, the content seems to have been translated. 
![Screenshot_20230625-152402_Twitter](https://github.com/hjiangsu/thunder/assets/107673019/6a6e4e07-b492-4c57-8a2a-6d62f4f2614e)
It would be very nice if a feature like this was made. Thank you for your efforts.

**Comment by dessalines** [comment]
If someone wants to add this, I can re-open.
