### ISSUE TITLE
Gracefully handle user 404s

### ISSUE THREAD

**Issue by rcmaehl** [dessalines/jerboa#882]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

Currently, not found users are not gracefully handled. Causing the following view:

![image](https://github.com/dessalines/jerboa/assets/716581/50e586f2-e60b-47b0-a9aa-1c7bf0cdede8)

I'd like to see these handled better in a future version.

**Comment by dessalines** [comment]
How could they be handled better?

**Comment by rcmaehl** [comment]
> How could they be handled better?

Maybe a toast instead of underscored_placeholder_text

**Comment by dessalines** [comment]
Its a matter of preference I spose, but you could open a PR if you like.
