### ISSUE TITLE
Badly formatted community@instance

### ISSUE THREAD

**Issue by MV-GH** [dessalines/jerboa#885]
**Jerboa Version**
latest main

**Android version + phone**
Android 11

**Describe the bug**
A community@instance link is badly formatted

![Screenshot_2023-06-26-05-02-55-185_com.jerboa.jpg](https://github.com/dessalines/jerboa/assets/67873169/6b47ebd0-f1bd-49cc-9e6b-e9e4eb9db898)

https://lemm.ee/comment/423673
 

Raw source comment

![Screenshot_2023-06-26-05-09-20-622_com.jerboa.jpg](https://github.com/dessalines/jerboa/assets/67873169/bf6745bf-1ab6-47d9-aad4-2c45bd68819d)

The exclaimationmark is technically wrong but maybe we should correctly handle it but the com@instance should be properly formatted now it only links to the Community part (which is valid community)

**To Reproduce**
 go here https://lemmy.world/post/595099 then to the comment in the pic

**Comment by MV-GH** [comment]
Looks like it doesn't automatically add the bug flair in the app.

**Comment by twizmwazin** [comment]
Shouldn't communities be prefixed with a `!`? Otherwise they're ambiguous from email addresses.

**Comment by MV-GH** [comment]
We don't format email address so atm they are not

**Comment by MV-GH** [comment]
But what i ment was we can check for whitespace between a ! and the remaining tag and correct it. not correct all community@instance links (But i wouldnt be against it)

**Comment by twizmwazin** [comment]
Oh I see. I'm unsure that we should be fixing malformed links. Exclamation marks end sentences, but even if we check that the exclamation is surrounded by whitespace, some people prefer to place a space before an exclamation at the end of a sentence for extra effect, which would lead to a lot of false positives.

**Comment by MV-GH** [comment]
I meant more for only the ! community@instance case not the general ! community. But the other thing i find weird is how `! community@instance` only the `! community` got turned into a link it should been all or none, not a partial. 

![image](https://github.com/dessalines/jerboa/assets/67873169/e6dc313c-b923-4c10-9db9-314ccc591b85)
In the browser it does show as !community@instance. So it was a correctly formed link even. I find this strange behaviour.

**Comment by MV-GH** [comment]
```
"content":"I think that if there is no one from your instance (which also happens to be my instance) is subscribed to a community on an instance other than your own then you have to search for it in the search bar (using the url or !community@lemmyinstance) before you will be able to interact with it. Lemmy doesn’t synchronize everything between all instances by default, only what is needed to save on resources. \n\n"
```|
The raw text, in case someone wanted it

**Comment by MV-GH** [comment]
I don't think is a bug anymore. This is intended behaviour, unless we don't want to match partials like this. It matches because `@` is a wordbreak thus it seen as separate `!community` link

What do you think @twizmwazin ?

**Comment by twizmwazin** [comment]
If we really wanted to make a change here, a domain doesn't actually have to have a dot in it, technically if someone controlled a tld they should be able to set a Lemmy instance up on it, though this is generally frowned on by ICANN. I think the current behavior is fine, matching partials is fine as it is especially useful in some cases like private non-federated instances.
