### ISSUE TITLE
(0.0.36) Login only gets represented in app after reopening 

### ISSUE THREAD

**Issue by sockenklaus** [dessalines/jerboa#888]
**Jerboa Version**
0.0.36 GitHub release

**Android version + phone**
OnePlus 5t, Android 10.1

**Describe the bug**
You only show as logged in after reopening the app 

* Login doesn't seem work anymore. After logging in you see the default local feed, profile page shows "Value record of type java.lang.String cannot be converted to JSONObject"
* Closing and opening the app refreshes the account data and the app shows you as logged in 

https://streamable.com/xvlqfz

**Comment by twizmwazin** [comment]
Giving this a test now. What I've found so far is if you log into an account, you need to quit and reopen the app to be logged in.

**Comment by twizmwazin** [comment]
The issue here seems not to be authentication but stale view models being used that don't have the new account information. Should be fixed with https://github.com/dessalines/jerboa/pull/817, and then we should do a 0.0.37 as soon as possible after.

**Comment by sockenklaus** [comment]
Great find! I can reproduce this.
________________________________

**Comment by sockenklaus** [comment]
> The issue here seems not to be authentication but stale view models being used that don't have the new account information. Should be fixed with #817, and then we should do a 0.0.37 as soon as possible after.

I couldn't investigate further but looks like you're correct. I could reproduce the behaviour your described.

Therefore I changed the issue's title and description and updated it with another behaviour that is most likely related with this issue.

**Comment by scme0** [comment]
I can confirm this is fixed in #817, at least for me (Pixel 6).

**Comment by ContentSpy** [comment]
Is this error also related to the fact that when I switch between accounts it sometimes displays a random persons account and not mine?

**Comment by sockenklaus** [comment]
> I can confirm this is fixed in #817, at least for me (Pixel 6).

I can confirm. Login works again without hiccups on the current main branch. with @nahwneeth's viewmodel changes. Without further in depth testing I consider this issue solved.
