### ISSUE TITLE
Changing sort type reverts to Local Active

### ISSUE THREAD

**Issue by ghoool** [dessalines/jerboa#890]
v0.0.36

Using Android 13 on Samsung A72

When changing post sorting, it reverts to Local Active automatically.

1. Log in via a Lemmy account (in this case lemmy.world)
2. Select Local instance
3. Change sort to 'New'
4. Allow posts to load, noting the sort resets after a second

Video attached:
https://github.com/dessalines/jerboa/assets/38882113/9d36278b-078d-459f-98f1-08ce554863ee

**Comment by ghoool** [comment]
I also noticed I can't change from Local to All or Subscribed, regardless of sort order.

**Comment by Stugist** [comment]
I'm stuck on All/New

**Comment by ghoool** [comment]
Rolled back to v0.0.35, this bug renders the latest alpha unusable.

**Comment by tolookah** [comment]
Mine refuses to leave subscribed hot, which is what my default sort type is set to.  Changing it to subscribed new, and restarting the app changed the sort I'm stuck on to subscribed new.

**Comment by lungdart** [comment]
Same issue here. I'm stuck on local active, even though my preference is all hot.

**Comment by mjhouse** [comment]
Same issue here. Also, if you change your default sort in profile settings and then restart, it will go to whichever sort you set, it's just not possible to change the sorting through the UI.

**Comment by Stugist** [comment]
I've tried, it doesn't work for me, still stuck on All/New

**Comment by takeda** [comment]
Is there a way to revert to old version? I really regret updating it

**Comment by takeda** [comment]
I think https://github.com/dessalines/jerboa/issues/887 might be the same issue?

**Comment by ghoool** [comment]
@takeda to revert you have to uninstall and download the v0.0.35 apk.

And yes this is a duplicate of #887 and #886 but I don't know how to link issues. Any guidance on that would be appreciated.

**Comment by tolookah** [comment]
Looks like it fixed for me on version 0.0.37 this morning

**Comment by M-Reimer** [comment]
The latest version doesn't work for me at all. Just crashes immediately. I'm giving up for now and use the webinterface.

**Comment by takeda** [comment]
> [...] I don't know how to link issues. Any guidance on that would be appreciated.

github automatically replaces URL to the issue with the link to it, so it just worked.

**Comment by Pome-ro** [comment]
> The latest version doesn't work for me at all. Just crashes immediately. I'm giving up for now and use the webinterface.

Is your home instance on v0.18.0 by any chance?

**Comment by M-Reimer** [comment]
> Is your home instance on v0.18.0 by any chance?

No. Lemmy.world had issues updating to 0.18.1rc1. Who knows when they will be able to update to something newer.

**Comment by MV-GH** [comment]
Solved in 0.37
