### ISSUE TITLE
Downvoting a post actually upvotes it

### ISSUE THREAD

**Issue by pure-bliss** [dessalines/jerboa#891]
**Jerboa Version**
0.0.35

**Android version + phone**
13, Xiaomi Redmi

**Describe the bug**
Downvoting a post actually upvotes it

**To Reproduce**

1. Go to any lemmy instance, find a post, open it on jerboa, and web browser
2. Tap on downvote
3. Refresh post in browser / on phone
4. Post is upvoted instead of downvoted

How does these PRs actually pass reviews? Do developers actually read it? jerboa is not trustable, this way anything goes

**Comment by MV-GH** [comment]
https://github.com/dessalines/jerboa/assets/67873169/f5710ed3-b027-4d9b-8555-ac2964e8af1e

Can't reproduce. If you think you can do a better job, contributions are always welcome 🤗. Keep in mind this a alpha build, bound to have bugs

**Comment by nahwneeth** [comment]
> Can't reproduce

I think the post has to be opened.

https://github.com/dessalines/jerboa/blob/0557d7fe2264fb7bb2d4d057c1b476879cbc0c68/app/src/main/java/com/jerboa/ui/components/post/PostActivity.kt#L335

**Comment by pure-bliss** [comment]
https://github.com/dessalines/jerboa/assets/83361786/7c5bc8bd-26e8-4723-b43e-ad668e2d9eee

**Comment by MV-GH** [comment]
> > Can't reproduce
> 
> I think the post has to be opened.
> 
> https://github.com/dessalines/jerboa/blob/0557d7fe2264fb7bb2d4d057c1b476879cbc0c68/app/src/main/java/com/jerboa/ui/components/post/PostActivity.kt#L335

Ah i see, simple fix.

**Comment by MV-GH** [comment]
That code is from 05fda4af, and did not go through any PR as dessalines was the sole contributor at the time.

**Comment by pure-bliss** [comment]
> That code is from [05fda4a](https://github.com/dessalines/jerboa/commit/05fda4af1326a2f531a89542d07371b3ab8e7c4e), and did not go through any PR as dessalines was the sole contributor at the time.

Blame shows this diff: https://github.com/dessalines/jerboa/commit/7d9c5a68c47f568d5a17f6630450e2bd267220ac
