### ISSUE TITLE
Not able to search for communities on other instances on the local one

### ISSUE THREAD

**Issue by iasad12** [dessalines/jerboa#902]
Version: 0.0.36

**Android version + phone**
android 10 + Samsung Galaxy J4

**Describe the bug**
If I try to search for communities on other instances while logged in to a local one, it doesn't show up in the search results. 

**To Reproduce**

1. Log in to a Lemmy Instance like Lemmy dot ml
2. Tap on Search icon and type android@kbin.social
3. Nothing shows up in the results. 
I have also tried adding /c/ but no luck. 

Though I am able to browse other instances fine on their website. 

Here is the screenshot 

![Screenshot_20230628-172513_Jerboa for Lemmy](https://github.com/dessalines/jerboa/assets/22590571/f7ca1b51-eb5e-4851-958c-84c46c4fe7d1)

**Comment by dessalines** [comment]
This is fixed.
