### ISSUE TITLE
Network error if upvote couldn't be processed before closing the post

### ISSUE THREAD

**Issue by Snow4DV** [dessalines/jerboa#913]
**Jerboa Version**
Latest from main [0dab56d](https://github.com/dessalines/jerboa/commit/0dab56d8cc9bf79057d7810a561c813d345baae1)

**Android version + phone**
Android 12/ OP7Pro

**Describe the bug**
Toast "Network error" will be displayed if you upvote post and close it before request to API could be processed.

**To Reproduce**

1. Go to feed
2. Open any post
3. Upvote and go back to feed instantly
4. See toast "network error" displayed by API ErrorHandler

**Comment by dessalines** [comment]
This seems fixed now.
