### ISSUE TITLE
Make all `List`s into `ImmutableList`

### ISSUE THREAD

**Issue by dessalines** [dessalines/jerboa#916]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

Context: https://github.com/dessalines/jerboa/pull/809

https://issuetracker.google.com/issues/199496149

**Comment by MV-GH** [comment]
Note that only lists passed as argument to a composable function needs to be changed.

**Comment by dessalines** [comment]
This isn't the preferred way anymore.
