### ISSUE TITLE
App crashing on launch with most recent update

### ISSUE THREAD

**Issue by NaitsirkC** [dessalines/jerboa#917]
**Jerboa Version**
0.0.37

**Android version + phone**
Android 13 S23+ oneui 5.1

**Describe the bug**
The app crashes when opening. It starts on the main feed (no feed though, just black, but you can still see the top and bottom bars), it loads for a second or two then crashes

**To Reproduce**

Open the app

**Comment by Rustmilian** [comment]
Clear the storage of the app completely.

**Comment by Arian04** [comment]
Duplicate of #911

**Comment by NaitsirkC** [comment]
I did that and now I can't log in at all. I can still log in with no issue
on the website or in other apps.

**Comment by MV-GH** [comment]
Closing as no longer relevant
