### ISSUE TITLE
Can't login to instances below v0.18 like Lemmy.world / App crash.

### ISSUE THREAD

**Issue by Rustmilian** [dessalines/jerboa#920]
Lemmy.world is having trouble updating to v0.18 , I believe this ties into the app crashing issues with the latest release as you could login with previous releases. But as this new release seems to have dropped support for versions prior to v0.18 the Lemmy.world accounts saved in the app would cause it to crash if it's the first to load. If the account isn't the first to load, it'll be removed from the account list.

To Fix the app crashing clear app data completely.

Log related to crash :
```java
FATAL EXCEPTION: main
Process: com.jerboa, PID: 8825
java.lang.NullPointerException: Parameter specified as non-null is null: method com.jerboa.ui.components.home.SiteViewModel$getSite$1.invokeSuspend, parameter sortType
	at com.jerboa.ui.components.home.SiteViewModel$getSite$1.invokeSuspend(Unknown Source:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:109)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@35f6836, Dispatchers.Main.immediate]
```

**Comment by MV-GH** [comment]
Actually i believe this happens for all accounts that are logged in that are from below (18.0). It doesn't properly check if a logged in account is within the supported minimum.

**Comment by Rustmilian** [comment]
> Actually i believe this happens for all accounts that are logged in that are from below (18.0). It doesn't properly check if a logged in account is within the supported minimum.

Ofc, I was just using it more so as an example as it's the largest one that having trouble updating to v0.18 and so it'd draw more users to this issue. I'll edit the issue name and to specify.

**Comment by MV-GH** [comment]
No i mean if u were logged in with a account from 0.17.X. And updated to 0.35 you could see the feed and open posts. Now in 0.37 It causes a crash as it doesn't default anymore.

**Comment by Rustmilian** [comment]
> No i mean if u were logged in with a account from 0.17.X. And updated to 0.35 you could see the feed and open posts. Now in 0.37 It causes a crash as it doesn't default anymore.

Oh, I get what you mean now.

**Comment by takeda** [comment]
This is discouraging.

I was using lemmy fine with previous version then after upgrading it there was an issue with selecting front page as well as sorting. I noticed that this apparently was fixed, so I upgraded it, but the app started crashing immediately after start.

After guidance here i cleared all data, which solved crashing, but now I can't log in. I have 3 accounts on 3 different servers (I didn't know at first which one I want to use), but I can't log in to any of those. Google Play also doesn't let me revert to the working version that I used.

This is a bit ironic, as I switched to lemmy because of mobile app on reddit :(

**Comment by Rustmilian** [comment]
> This is discouraging.
> 
> I was using lemmy fine with previous version then after upgrading it there was an issue with selecting front page as well as sorting. I noticed that this apparently was fixed, so I upgraded it, but the app started crashing immediately after start.
> 
> After guidance here i cleared all data, which solved crashing, but now I can't log in. I have 3 accounts on 3 different servers (I didn't know at first which one I want to use), but I can't log in to any of those. Google Play also doesn't let me revert to the working version that I used.
> 
> This is a bit ironic, as I switched to lemmy because of mobile app on reddit :(

You can revert using the [Github Releases](https://github.com/dessalines/jerboa/releases)

**Comment by takeda** [comment]
@Rustmilian thank you

**Comment by Rustmilian** [comment]
> @Rustmilian thank you. What are others, I heard about sync, and signed up for notification when it is ready, but am also interested in hearing about others.

[Liftoff](https://github.com/liftoff-app/liftoff/) & [Thunder](https://apt.izzysoft.de/fdroid/index/apk/com.hjiangsu.thunder) are 2 that come to mind, but there's a few more that don't have a release on android quite yet.
