### ISSUE TITLE
Default comment sorting

### ISSUE THREAD

**Issue by 1Phase1** [dessalines/jerboa#921]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **
Add the ability to set default comment sorting the same way you can set default post sorting. As it is in 0.0.37, comment sorting resets to hot on every post. In 0.0.36, it was possible to set it to top, and it would stay that way for every post until the app was restarted. Now it resets to hot every time. I'm not sure if this is a bug, but default comment sorting options would be nice to have either way.

**Comment by dessalines** [comment]
This is fixed now.
