### ISSUE TITLE
NSFW images are blurred, but NSFW community logos are not

### ISSUE THREAD

**Issue by calculuschild** [dessalines/jerboa#925]
**Jerboa Version**
0.0.36

**Android version + phone**
Android 13 + Galaxy S22

**Describe the bug**
I have the setting enabled to blur NSFW images. However, certain communities have started appearing when browsing "All" that have an NSFW image as the logo, which is not blurred. Came as a bit of a shock when I was casually scrolling on my phone in a public space. These communities appear to be mostly hosted at lemmynsfw.com. I can block them manually, but new ones are always popping up.

Not sure if this is something I should raise with Lemmy itself, if it is a moderator/admin issue, or if it's an option Jerboa can have to blur logos of NSFW communities, but seemed like a UI issue so I'm trying here first.

**To Reproduce**

1. Go to any instance and filter by "all". You will probably find the issue faster if you start from an NSFW instance.
2. Just scroll down for a couple minutes
3. Boobs!

**Screenshot (drawn over so I'm not showing nudity here on Github)**

<img src='https://github.com/dessalines/jerboa/assets/5878534/b48118b5-b4b8-4ce2-b6ef-0d21af49752a' width='200px'>

**Comment by MV-GH** [comment]
Fixed in 0.37 see #896
