### ISSUE TITLE
Unable to collapse comment

### ISSUE THREAD

**Issue by waldyrious** [dessalines/jerboa#935]
**Jerboa Version**
0.0.37

**Android version + phone**
Android 13 @ Google Pixel 4a

**Describe the bug**
I have toggled the Settings > Look and feel > Show content for collapsed comments, but regardless of it being on or off, the content of a collapsed comment (after long-press) is shown — only the buttons (upvote/downvote, bookmark, etc.) get collapsed/expanded when I long-press a comment.

**To Reproduce**

1. Go to Settings > Look and feel and ensure the "Show content for collapsed comments" option is off 
2. Go to any thread with comments
3. Long-press a comment
4. Verify that the contents of the comment is still shown and only the buttons below it are hidden.

**Comment by waldyrious** [comment]
By the way, what exactly is the usefulness of collapsing only the buttons (assuming this is the intended behavior for when "Show content for collapsed comments" is off)? It seems to make almost no difference.

**Comment by MV-GH** [comment]
To collapse comments you need to do a short tap.

**Comment by twizmwazin** [comment]
> By the way, what exactly is the usefulness of collapsing only the buttons (assuming this is the intended behavior for when "Show content for collapsed comments" is off)? It seems to make almost no difference.

This is primarily used by users who do show the comment action bar by default. It provides a much cleaner and compact view, and since the majority of comments aren't interacted with, it isn't a problem to long-press to show the bar in the first place. Secondarily, a lot of features such as this one are implemented to mirror behaviors in other apps that users are used to, like Boost.

**Comment by waldyrious** [comment]
> To collapse comments you need to do a short tap.

Oh, wow, I totally missed that! Sorry for the noise.

I wonder if it would be worth considering an actual icon to perform this action, so that it is accessible to those who don't know the gesture. I'll open a separate issue to propose that.

@twizmwazin, thanks for the context! I suppose you mean "users who don't show the comment action bar by default", right?

**Comment by twizmwazin** [comment]
Yes, that is correct
