### ISSUE TITLE
Side Menu Should Always be Accessable if Bottom Navigation Bar is Visible

### ISSUE THREAD

**Issue by 0hCome0n** [dessalines/jerboa#939]
- [✓] Did you check to see if this issue already exists?
- [✓] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

Swiping from the left edge of the screen should pull out the side menu whenever the lower navigation bar is visible, not just when the navigation bar is set to the home screen.

![Screenshot_20230701-135617](https://github.com/dessalines/jerboa/assets/135261443/5c5518de-aebe-4f92-b6d0-6c50840b8e68)

**Comment by MV-GH** [comment]
Fixed in #991
