### ISSUE TITLE
Side Menu Items Disappear When Account Switcher Slides Down

### ISSUE THREAD

**Issue by 0hCome0n** [dessalines/jerboa#940]
**Jerboa Version**
0.0.37

**Android version + phone**
14 (UPB3.230519.014)

**Describe the bug**
It's hard to decide if this is a bug or a UI oversight.

In the side menu you can tap on your username to show a drop-down menu that lets you switch accounts. But, the drop-down makes the rest of the side menu disappear instead of just pushing it down or drawing over it. The disappearance suggests that it's supposed to be a new layer, but hitting the Android UI Back Button doesn't take you to the original side menu, it behaves the same as if the original side menus is still there. The menu sliding back into place suggests it's supposed to remain visible.

Is this a bug? That is, is the rest of the menu supposed to remain visible? The smooth drop down animation of the accounts list suggests that it is, but I could also see this just being a feature that's not yet implemented.

If the account switching menu is *supposed* to be a different layer, then hitting the back button should take you to the main side menu. If it's supposed to be embedded in the main side menu, then the rest of the menu should slide down instead of disappearing.

![Screenshot_20230701-135951](https://github.com/dessalines/jerboa/assets/135261443/c5f14cf4-0cd1-4cea-9ddb-72b6b289aaed)

**To Reproduce**

1. Open app
2. Swipe right to reveal left side menu
3. Click on you username to reveal list of alternate accounts
4. Notice how the rest of the menu disappears, but the drop-down animation suggests that it shouldn't.

**Comment by 0hCome0n** [comment]
![Screenshot_20230701-135835](https://github.com/dessalines/jerboa/assets/135261443/94d3167a-647a-4a90-877d-40678454c789)
Added same image twice by accident

**Comment by 0hCome0n** [comment]
[bugreport-panther_beta-UPB3.230519.014-2023-07-01-14-43-45-dumpstate_log-16502.txt](https://github.com/dessalines/jerboa/files/11926908/bugreport-panther_beta-UPB3.230519.014-2023-07-01-14-43-45-dumpstate_log-16502.txt)
[dumpstate-stats.txt](https://github.com/dessalines/jerboa/files/11926909/dumpstate-stats.txt)
[bugreport-panther_beta-UPB3.230519.014-2023-07-01-14-43-44.zip](https://github.com/dessalines/jerboa/files/11926910/bugreport-panther_beta-UPB3.230519.014-2023-07-01-14-43-44.zip)

Bug reports generated locally

**Comment by MV-GH** [comment]
This is indeed intended behavior but I do think, it would be better if it slides down the existing stuff.

**Comment by 0hCome0n** [comment]
I can resubmit as a feature request, if preferred.

**Comment by MV-GH** [comment]
just edit this one
