### ISSUE TITLE
Make it possible to sort by Top: Hour/6hours/12hours

### ISSUE THREAD

**Issue by ppjpat** [dessalines/jerboa#950]
- [x ] Did you check to see if this issue already exists?
- [x ] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **
Add the options to sort by:
Top: Hour
Top: 6 hours
Top: 12 hours

Similar to the options already available on the web front end:
![image](https://github.com/dessalines/jerboa/assets/138362039/0ffc8655-d505-4afb-bffc-ef00eafd2679)

**Comment by MV-GH** [comment]
Already added see #918
