### ISSUE TITLE
Uploading image creates post without image

### ISSUE THREAD

**Issue by AnyOldName3** [dessalines/jerboa#954]
**Jerboa Version**
0.0.33, unless there was an automatic update since last night.

**Android version + phone**
8.0.0, Galaxy S7 Edge

**Describe the bug**
Last night, I made this post: https://lemmy.world/post/924162. The image was added to the post in Jerboa, so I expected it to appear as part of the post, but it didn't when I checked back later (and there were comments complaining about it being missing). I then edited the post to attach the image again, but ended up with the same result.

Later, I edited the post to include an imgur link, and then when I was back at my desktop, uploaded the image via the web interface, so it's there now.

**To Reproduce**

1. Go to a community.
2. Click on the `+` button in the bottom right.
3. Add a title.
4. Press *Upload Image*.
5. Pick an image.
6. Observe that the image is shown in the form.
7. Press the `+` button in the top right.
8. Come back later.
9. Observe comments complaining that you've not actually uploaded an image.

Note that I've not actually tried these since last night as I don't know how to connect Jerboa to a test instance, and since then, I think lemmy.world has updated, so they might not work anymore.

**Comment by dessalines** [comment]
I can't repro

**Comment by AnyOldName3** [comment]
Fair enough - the report was months ago and Jerboa no longer even launches on that phone without crashing, so there's a pretty good chance this was fixed while working on something else, or only ever happened on an old and unsupported Android version.

**Comment by dessalines** [comment]
No probs.
