### ISSUE TITLE
Add a second NSFW Blur toggle which applies only to NSFW communities

### ISSUE THREAD

**Issue by MrMusAddict** [dessalines/jerboa#957]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

Ideally it'd be great if we could keep NSFW content blurred while browsing mixed communities (all, local, non-NSFW communities that allow NSFW posts), BUT to not blur NSFW content while in a NSFW community. 

I'm thinking we should have 2 toggles;

1. Blur NSFW content on non-NSFW communities, and mixed content pages (all / local, etc)
2. Blur NSFW content on NSFW communities

Or, perhaps a single drop-down to select one of the 3 options;

1. Do not blur
2. Blur everywhere except NSFW Communities
3. Blur everywhere

**Comment by MakcNmyc** [comment]
It's also needed change nsfw type on server

**Comment by dessalines** [comment]
Fixed by above.
