### ISSUE TITLE
Cannot display any content in app

### ISSUE THREAD

**Issue by Nihth** [dessalines/jerboa#958]
**Jerboa Version**
0.0.37

**Android version + phone**
Android 13, Galaxy s20 Fe 5g

**Describe the bug**
The app displays the error message "
Value <! DOCTYPE of type java.lang.String cannot be converted to JSONObject". 
This happens at the tab inbox, saved and profile. Home and search works but are empty. Settings still work except the lemmy settings seem to be default values. 

**To Reproduce**
Just opening the app. Killing the app and reopening still displays the bug

**Comment by MV-GH** [comment]
Are you logged in, if so with which server? It looks like its getting HTML responses instead of JSON

**Comment by Nihth** [comment]
Yes I was logged in to a user in Programming.dev

It seems to be working again now, not sure what caused it and why its working again now

**Comment by Nihth** [comment]
Yes I was logged in to a user in Programming.dev

It seems to be working again now, not sure what caused it and why its working again now

**Comment by MV-GH** [comment]
I think this was caused by programming.dev themselves. I had some reports that users couldnt log in from that instance too in matrix. But it seems to work now.
