### ISSUE TITLE
Allow setting to swap voting & thumbnail locations

### ISSUE THREAD

**Issue by GRJ463** [dessalines/jerboa#964]
- Could not find an existing feature request.
- This is a single feature request.
- This is neither a question or discussion.

** Describe the feature request below **

Similar to the functionality in the reddit is fun application, it would be nice to be able to switch the positions of the voting and thumbnails. This could be called left handed mode, or just "swap voting & thumbnails".

The end of fact would have the thumbnails on the left side of the text, and the voting on the right side of the text of a post.

**Comment by ToNIX-** [comment]
I agree! I was about to open a new request for this, but found yours.

I think both options should be separated in the settings:
"Show thumbnail on the left"
"Show vote button on the right".

**Comment by dessalines** [comment]
If someone wants to add this, I can re-open.
