### ISSUE TITLE
Back and download buttons difficult to click due to status bar overlapping them (when viewing images)

### ISSUE THREAD

**Issue by lawrence0arabia** [dessalines/jerboa#966]
Jerboa v0.0.38

Android 13, OnePlus 7 Pro (Pixel Experience)

Status bar covers back button and download button at the top of the screen, making it very difficult to click these buttons. 

**To Reproduce**

1. Open any image in Jerboa
2. Tap to expose back button and download button
3. Try to click either button (and note the majority of the button is unclickable due to the status bar).

**Comment by MV-GH** [comment]
Include screenshots

**Comment by lawrence0arabia** [comment]
![Screenshot_20230705-222854_Jerboa.png](https://github.com/dessalines/jerboa/assets/67545734/947caf79-76d1-482f-bc45-0fb8f7ab144b)

![Screenshot_20230705-222854_Jerboa~3.png](https://github.com/dessalines/jerboa/assets/67545734/358ddb05-d264-404d-a762-aa109e96949f)

![Screenshot_20230705-222854_Jerboa~2.png](https://github.com/dessalines/jerboa/assets/67545734/b86f7aca-330c-4c3b-8431-e239a35d4469)

Note how you can see the edge of the battery percentage overlapping the download button, and the edge of the clock overlapping the back button.
