### ISSUE TITLE
Visible icon for collapsing/expanding comment threads

### ISSUE THREAD

**Issue by waldyrious** [dessalines/jerboa#974]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

I am aware that a single tap can collapse/expand a comment thread, but the gesture is not discoverable (unless you assume it is there, perhaps having prior experience with similar apps, or you perform it by accident); furthermore, the lack of an explicit indicator/actuator can be an accessibility problem.

It would be nice if there was an explicit icon for collapsing/expanding comments — it could be, for example, something like `[+]`/`[-]`, as is common in other threaded commenting platforms. This way the feature would be discoverable by people who aren't familiar with the pattern. (And that would avoid a potential stumbling block for newcomers, as happened to me in #935).

**Comment by dessalines** [comment]
Most apps don't have this, and neither do we.
