### ISSUE TITLE
Default comment sort option

### ISSUE THREAD

**Issue by tjkirch** [dessalines/jerboa#976]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **
I'd like a setting to change the default sort type for comments on a post.  Every time I open a post, the comments are sorted by "Hot" but I normally prefer "Top".

**Comment by twizmwazin** [comment]
Duplicate of #921
