### ISSUE TITLE
Unreasonable aspect ratio / height cap limit for images in feeds

### ISSUE THREAD

**Issue by enki1337** [dessalines/jerboa#981]
**Jerboa Version**
v0.0.38-alpha

**Android version + phone**
Not relevant.

**Describe the bug**
Very tall images do not have a reasonable height cap, and result in the need for excessive scrolling to get to the next post in the feed.

**To Reproduce**

1. See [this post](https://sh.itjust.works/post/786167) in your feed.
2. Scroll down.
3. Scroll down some more.
4. Why am I still scrolling? >:(
5. Finally get to the next post.

**Comment by MV-GH** [comment]
https://github.com/dessalines/jerboa/blob/4fc09124b8db64b1b18cb70f5d913ebb21605970/app/src/main/java/com/jerboa/ui/theme/Sizes.kt#L31-L32 

We do have currently a limit. 

I think the bigger problem is that we dont enforce this for non pictrs image links

https://github.com/dessalines/jerboa/blob/4fc09124b8db64b1b18cb70f5d913ebb21605970/app/src/main/java/com/jerboa/Utils.kt#L442-L462

**Comment by dessalines** [comment]
^^

**Comment by MV-GH** [comment]
This is not fixed for non pictrs pictures. And is not enforced. Pictrs could return bigger. version than we request and we would display that.
