### ISSUE TITLE
Left sidebar community names cutoff awkwardly

### ISSUE THREAD

**Issue by Die4Ever** [dessalines/jerboa#983]
**Jerboa Version**
v0.0.37 from F-Droid and also v0.0.38 Alpha from Github

**Android version + phone**
Android 13, Pixel 7a

**Describe the bug**
EDIT: don't waste your time reading all below, just need to fix the overflow to ellipsis...

Community names in my sidebar seem cutoff very short possibly due to the word Randomizer, I have multiple examples here https://lemmy.mods4ever.com/communities (the Stauf's Mansion one works fine though, possibly because it doesn't have Randomizer in the name)

They work correctly if I switch to my admin account on that instance. They're only broken when viewing from my programming.dev account (which is a moderator on them all)

Programming.dev is running v0.18.0, mods4ever is running UI: 0.18.1-rc.11 BE: 0.18.1-rc.10

The programming.dev website is showing the community names correctly so I think it's something in Jerboa.

**To Reproduce**

1. Go to https://lemmy.mods4ever.com/communities
2. Subscribe to some of the communities
3. Check the left sidebar in Jerboa and see that their names are cutoff completely leaving out the word "Randomizer" even when there's plenty of room

In this screenshot, see Build Engine, Deus Ex, and Duke Nukem Forever (2001) are all missing the word Randomizer

![Screenshot_20230707-012750](https://github.com/dessalines/jerboa/assets/30947252/5635cc5f-c48c-4fd5-a9dd-65264c15a4c6)

In this screenshot see RollerCoaster Tycoon and StarCraft 2 both missing the word Randomizer, but my own Stauf's Mansion community has a long name and isn't cutoff like the others are

![Screenshot_20230707-013925](https://github.com/dessalines/jerboa/assets/30947252/0bee4394-2a9b-4d37-886a-bf3912ca1c42)

I tried searching for "rand" in your code but didn't see anything suspicious.

Doesn't seem to be an issue with my hostname because the Meta community shows correctly

![Screenshot_20230707-014638](https://github.com/dessalines/jerboa/assets/30947252/3e5651c1-91aa-411d-bb85-7c7285c11ee9)

**Comment by MV-GH** [comment]
The way text clipping works in jetpack compose is that its clips to the nearest whitespace that fits. Thus you will see longer community names while others get clipped much earlier due to this. There is no "selective" clipping for communities with certain names.

**Comment by MV-GH** [comment]
The other option is that we do ... and than you will see a bunch of Ra... Or we put too long community names on multiple lines but this can look quite ugly

**Comment by Die4Ever** [comment]
Oh because the @ isn't a word break, gotcha... Should I put a space at the end of my community names?

**Comment by MV-GH** [comment]
What is a id in this case? We had a sorta "hack" that added a a null width space (which counted as whitespace that is not visible) that was added around @. But dessalines not like it. So it did not get merged see https://github.com/dessalines/jerboa/pull/778

**Comment by Die4Ever** [comment]
> What is a id in this case? We had a sorta "hack" that added a a null width space (which counted as whitespace that is not visible) that was added around @. But dessalines not like it. So it did not get merged see #778

by id I mean the non-fancy name, like !deus_ex_randomizer@lemmy.mods4ever.com

ellipsis will be a good improvement

**Comment by Die4Ever** [comment]
Another option would be to always put the @domain.name on the line below the community name, maybe in a slightly smaller font

Combined with ellipsis, I think even the longest of community names and domain names would still look good

**Comment by MV-GH** [comment]
Sure but you will have to make a separate issue for that.
