### ISSUE TITLE
Redundant Titles and Body

### ISSUE THREAD

**Issue by Villhelm-E** [dessalines/jerboa#993]
**Jerboa Version**
0.0.38

**Android version + phone**
Android 13 on Pixel 6 Pro

**Describe the bug**
Sometimes the title or body of a post appear twice. In this case, both appear twice:
![Screenshot_20230706-161918](https://github.com/dessalines/jerboa/assets/25539368/59da09fb-826c-4680-96ae-e8002c14d194)

**To Reproduce**

Just go to the post. At first I thought it was due to linking an article (the post and the headline havinf the same title) but not all posts have this issue.

**Comment by MV-GH** [comment]
Can you link this post. And does it do consistently for this post?

**Comment by Villhelm-E** [comment]
Yes it does it consistently with every post I've found like this. I wasn't able to search for the original post in Jerboa for some reason (search could use some work). The link is https://lemmy.world/post/1114813. In the browser, only the body is duplicated, not the title:
<img width="995" alt="image" src="https://github.com/dessalines/jerboa/assets/25539368/5b4ed6fc-5874-474f-8c4d-41a7d0897108">
Which tells me it's at least partially a Lemmy thing.
Using Firefox 114.0.2 for MacOS (Ventura 13.4.1 using OpenCore Patcher)

Here's another post. It's almost every single post with a link to an article: 
![image](https://github.com/dessalines/jerboa/assets/25539368/84f05bd8-2c7f-4b04-bd8e-527ad884d003)
link: https://lemmy.world/post/1246165

But not all: 
![image](https://github.com/dessalines/jerboa/assets/25539368/aca2fbe9-7264-4dec-bcf2-41fbfdf737a1)
link: https://lemdro.id/post/23178

and again, the title is not duplicated in the browser: 
<img width="994" alt="image" src="https://github.com/dessalines/jerboa/assets/25539368/d0398634-559c-4faa-b7ce-e13abcc3c975">


Here's one where only the title is duplicated: 
![image](https://github.com/dessalines/jerboa/assets/25539368/e987ad97-5f0c-44b1-b565-b8baef9bda5f)
link: https://lemmy.world/post/1240435

No duplicate in the browser: 
<img width="1014" alt="image" src="https://github.com/dessalines/jerboa/assets/25539368/6552636e-0208-40e0-ae22-7d057e1a60b3">

Happens in a completely different Instance as well: 
![image](https://github.com/dessalines/jerboa/assets/25539368/48d47d61-b3d0-4fb6-baa9-fa4c225123b4)

**Comment by twizmwazin** [comment]
This is a speculation, but I think what is going on is the but in the outlined box is an article preview, showing the article title and short description. It's convention for users to name their post the same as the link's title. In your last screenshot, you can see that the user appended the site name to their title, for example. In the case where both the title and description were duplicates, the user copied the description into their post body. If what I'm saying is true, the best solution here would just be an option to disable showing previews.

**Comment by MV-GH** [comment]
I think the same as twizmwazin but my approach would be automatically hide the meta description if its the same as the meta title, and the meta title if its the same as the post title.
